# 0- Imports

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

# 1- Base

Dados de entrada

In [2]:
df_prod = pd.read_excel('../../01-Data/Dados - desafio disciplina RPVMM.xlsx')
df_prod

,Ordem de produção,Data da ordem de produção,Produto,Comprimento unit,Largura unit,Altura unit,Peso unit,Peças,Caixa padrão,Loja,Classe de onda,Tipo de buffer,Item pai,Cor,Tamanho,Inner
0,1,2023-11-07,549326104,472,232,24,0.130,5,CARTON_M,1,1,EN,1,1.0,1,1
1,2,2023-11-14,828646451,284,131,50,0.250,3,CARTON_M,2,2,CX,2,2.0,2,1
2,3,2023-11-09,605410977,250,100,14,0.120,1,CARTON_M,3,1,CX,3,3.0,3,1
3,4,2023-11-20,847250347,460,267,52,0.570,2,CARTON_M,4,3,EN,4,4.0,4,1
4,5,2023-11-17,840651501,480,235,67,0.340,3,CARTON_M,5,4,EN,5,5.0,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,11716,2023-11-27,882142923,545,320,34,0.300,1,CARTON_M,147,4,EN,506,9.0,6,1
99996,11428,2023-11-27,837646815,493,220,50,0.303,1,CARTON_M,12,4,EN,1212,4.0,3,1
99997,11460,2023-11-17,882141251,459,333,21,0.307,1,CARTON_M,129,4,EN,2334,9.0,6,1
99998,11542,2023-11-17,882141269,472,332,22,0.287,2,CARTON_M,37,4,EN,2334,9.0,1,1
99999,11696,2023-11-27,881474521,191,306,33,0.280,2,CARTON_M,50,4,EN,1581,486.0,3,1

In [3]:
df_prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Ordem de produção          100000 non-null  int64
 1   Data da ordem de produção  100000 non-null  datetime64[ns]
 2   Produto                    100000 non-null  int64
 3   Comprimento unit           100000 non-null  int64
 4   Largura unit               100000 non-null  int64
 5   Altura unit                100000 non-null  int64
 6   Peso unit                  100000 non-null  float64
 7   Peças                      100000 non-null  int64
 8   Caixa padrão               100000 non-null  object
 9   Loja                       100000 non-null  int64
 10  Classe de onda             100000 non-null  int64
 11  Tipo de buffer             100000 non-null  object
 12  Item pai                   100000 non-null  int64
 13  Cor                        94042 non-null   float64
 14  Tamanho                    100000 non-null  int64
 15  Inner                      100000 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(11), object(2)
memory usage: 12.2+ MB

In [4]:
vars_string = ['Produto','Caixa padrão', 'Loja', 'Classe de onda', 
               'Tipo de buffer', 'Item pai', 'Cor', 'Tamanho']

df_prod[vars_string] = df_prod[vars_string].astype('string')

Dados de restrição de capacidade

In [5]:
df_rotas_capacidade = pd.read_excel('../../01-Data/Dados - desafio disciplina RPVMM.xlsx', sheet_name='Rotas_capacidade')
df_rotas_capacidade

    Rota    Capacidade
0      1           inf
1      2  2.720000e+10
2      3           inf
3      4           inf
4      5  2.720000e+10
5      6  2.720000e+10
6      7  4.000000e+10
7      8  4.000000e+10
8      9  2.720000e+10
9     10  2.720000e+10
10    11  2.720000e+10
11    12  1.600000e+10
12    13  2.720000e+10
13    14  7.600000e+10
14    15  4.000000e+10
15    16  2.240000e+10
16    17  2.720000e+10
17    18  2.720000e+10

In [6]:
df_rotas_capacidade['Rota'] = df_rotas_capacidade['Rota'].astype('string')

In [7]:
df_rotas_lojas = pd.read_excel('../../01-Data/Dados - desafio disciplina RPVMM.xlsx', sheet_name='Rotas_lojas')
df_rotas_lojas

     Rota  Loja
0       1    44
1       2     8
2       3    70
3       4   123
4       3   122
..    ...   ...
152     4   102
153     4    32
154     4   144
155     3   151
156     4    29

[157 rows x 2 columns]

In [8]:
df_rotas_lojas[['Rota', 'Loja']] = df_rotas_lojas[['Rota', 'Loja']].astype('string')

## 1.1 Juntar bases

In [9]:
df_rotas = df_rotas_lojas.merge(df_rotas_capacidade, how='left', on='Rota')
df_rotas

    Rota Loja    Capacidade
0      1   44           inf
1      2    8  2.720000e+10
2      3   70           inf
3      4  123           inf
4      3  122           inf
..   ...  ...           ...
152    4  102           inf
153    4   32           inf
154    4  144           inf
155    3  151           inf
156    4   29           inf

[157 rows x 3 columns]

In [10]:
df_prod_completo = df_prod.merge(df_rotas, how='left', on='Loja')
df_prod_completo

,Ordem de produção,Data da ordem de produção,Produto,Comprimento unit,Largura unit,Altura unit,Peso unit,Peças,Caixa padrão,Loja,Classe de onda,Tipo de buffer,Item pai,Cor,Tamanho,Inner,Rota,Capacidade
0,1,2023-11-07,549326104,472,232,24,0.130,5,CARTON_M,1,1,EN,1,1.0,1,1,3,inf
1,2,2023-11-14,828646451,284,131,50,0.250,3,CARTON_M,2,2,CX,2,2.0,2,1,11,2.720000e+10
2,3,2023-11-09,605410977,250,100,14,0.120,1,CARTON_M,3,1,CX,3,3.0,3,1,5,2.720000e+10
3,4,2023-11-20,847250347,460,267,52,0.570,2,CARTON_M,4,3,EN,4,4.0,4,1,14,7.600000e+10
4,5,2023-11-17,840651501,480,235,67,0.340,3,CARTON_M,5,4,EN,5,5.0,5,1,4,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,11716,2023-11-27,882142923,545,320,34,0.300,1,CARTON_M,147,4,EN,506,9.0,6,1,3,inf
99996,11428,2023-11-27,837646815,493,220,50,0.303,1,CARTON_M,12,4,EN,1212,4.0,3,1,3,inf
99997,11460,2023-11-17,882141251,459,333,21,0.307,1,CARTON_M,129,4,EN,2334,9.0,6,1,4,inf
99998,11542,2023-11-17,882141269,472,332,22,0.287,2,CARTON_M,37,4,EN,2334,9.0,1,1,4,inf
99999,11696,2023-11-27,881474521,191,306,33,0.280,2,CARTON_M,50,4,EN,1581,486.0,3,1,3,inf

# 2- Pré-processamanto

A quantidade máxima de **peças em caixas** precisa ser:
<ul>
    <li>120.000 peças para o “Tipo de buffer” CX e </li>
    <li>100.000 peças para o “Tipo de buffer” EN.</li>
 </ul>

In [11]:
df_prod_completo.columns = df_prod_completo.columns.str.replace(' ', '_')

In [12]:
df_prod_completo['Cor'] = df_prod_completo['Cor'].fillna('0')

In [13]:
df_prod_completo['pai_cor'] = df_prod_completo['Item_pai'] + '_' + df_prod_completo['Cor']
df_prod_completo['pai_cor']

0             1_1.0
1             2_2.0
2             3_3.0
3             4_4.0
4             5_5.0
            ...
99995       506_9.0
99996      1212_4.0
99997      2334_9.0
99998      2334_9.0
99999    1581_486.0
Name: pai_cor, Length: 100000, dtype: string

In [14]:
df_prod_completo['chave_loja_buffer_onda'] = df_prod_completo['Loja'] + '_' + df_prod_completo['Tipo_de_buffer'] + '_' + df_prod_completo['Classe_de_onda']

In [15]:
df_prod_completo['Volume_unit'] = df_prod_completo['Comprimento_unit'] * df_prod_completo['Largura_unit'] * df_prod_completo['Altura_unit']

In [16]:
df_completo_FIFO = df_prod_completo.sort_values(by=['Data_da_ordem_de_produção', 'Ordem_de_produção', 'Loja','Classe_de_onda', 'Tipo_de_buffer','pai_cor'])

In [17]:
with pd.option_context('display.max_columns', None):
    display(df_completo_FIFO.head())

,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,Loja,Classe_de_onda,Tipo_de_buffer,Item_pai,Cor,Tamanho,Inner,Rota,Capacidade,pai_cor,chave_loja_buffer_onda,Volume_unit
25664,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,26,5,CX,1865,6.0,27,1,1,inf,1865_6.0,26_CX_5,3092300
58831,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,26,5,CX,1865,6.0,21,1,1,inf,1865_6.0,26_CX_5,3321500
71019,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,26,5,CX,1865,6.0,4,1,1,inf,1865_6.0,26_CX_5,3537200
47494,7475,2023-10-16,804068393,104,121,20,0.083,7,CARTON_S,19,6,CX,2489,637.0,179,1,1,inf,2489_637.0,19_CX_6,251680
61825,8653,2023-10-16,804068334,116,106,19,0.082,5,CARTON_S,26,6,CX,2489,674.0,179,1,1,inf,2489_674.0,26_CX_6,233624

Quantidade total de peças por tipo de buffer

In [18]:
df_completo_FIFO.loc[df_completo_FIFO['Tipo_de_buffer'] == 'EN', 'Peças'].sum()

149582

In [19]:
df_completo_FIFO.loc[df_completo_FIFO['Tipo_de_buffer'] == 'CX', 'Peças'].sum()

220000

Observa-se que a base completa tem mais itens do que o limite de produção diário. Por isso, iremos reduzir a quantidae de itens.

## 2.1- Limite buffer

Selecionar o limite do buffer tipo CX

In [20]:
soma = 0
indices = []
tipo_buffer = 'CX'
max = 120000

for index, value in df_completo_FIFO[df_completo_FIFO['Tipo_de_buffer'] == tipo_buffer]['Peças'].items():
    soma += value
    if soma == max:
        indices.append(index)
        break
    elif soma > max:
        soma -= value
        break
    else:
        indices.append(index)

df_limite_buffer_CX = df_completo_FIFO.loc[indices]
df_limite_buffer_CX['Peças'].sum()

119999

Selecionar o limite do buffer tipo EN

In [21]:
soma = 0
indices = []
tipo_buffer = 'EN'
max = 100000

for index, value in df_completo_FIFO[df_completo_FIFO['Tipo_de_buffer'] == tipo_buffer]['Peças'].items():
    soma += value
    if soma == max:
        indices.append(index)
        break
    elif soma > max:
        soma -= value
        break
    else:
        indices.append(index)

df_limite_buffer_EN = df_completo_FIFO.loc[indices]
df_limite_buffer_EN['Peças'].sum()

100000

In [22]:
df_limite_buffer = pd.concat([df_limite_buffer_CX, df_limite_buffer_EN], ignore_index=True)
df_limite_buffer

,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,Loja,...,Tipo_de_buffer,Item_pai,Cor,Tamanho,Inner,Rota,Capacidade,pai_cor,chave_loja_buffer_onda,Volume_unit
0,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,26,...,CX,1865,6.0,27,1,1,inf,1865_6.0,26_CX_5,3092300
1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,26,...,CX,1865,6.0,21,1,1,inf,1865_6.0,26_CX_5,3321500
2,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,26,...,CX,1865,6.0,4,1,1,inf,1865_6.0,26_CX_5,3537200
3,7475,2023-10-16,804068393,104,121,20,0.083,7,CARTON_S,19,...,CX,2489,637.0,179,1,1,inf,2489_637.0,19_CX_6,251680
4,8653,2023-10-16,804068334,116,106,19,0.082,5,CARTON_S,26,...,CX,2489,674.0,179,1,1,inf,2489_674.0,26_CX_6,233624
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62172,7305,2023-11-22,882056566,473,326,25,0.520,2,CARTON_M,35,...,EN,2445,268.0,6,1,3,inf,2445_268.0,35_EN_4,3854950
62173,7305,2023-11-22,882056566,473,326,25,0.520,2,CARTON_M,36,...,EN,2445,268.0,6,1,4,inf,2445_268.0,36_EN_4,3854950
62174,7305,2023-11-22,882056566,473,326,25,0.520,2,CARTON_M,42,...,EN,2445,268.0,6,1,7,4.000000e+10,2445_268.0,42_EN_4,3854950
62175,7305,2023-11-22,882056566,473,326,25,0.520,2,CARTON_M,45,...,EN,2445,268.0,6,1,4,inf,2445_268.0,45_EN_4,3854950
62176,7305,2023-11-22,882056566,473,326,25,0.520,2,CARTON_M,46,...,EN,2445,268.0,6,1,4,inf,2445_268.0,46_EN_4,3854950

In [23]:
df_limite_buffer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62177 entries, 0 to 62176
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Ordem_de_produção          62177 non-null  int64
 1   Data_da_ordem_de_produção  62177 non-null  datetime64[ns]
 2   Produto                    62177 non-null  string
 3   Comprimento_unit           62177 non-null  int64
 4   Largura_unit               62177 non-null  int64
 5   Altura_unit                62177 non-null  int64
 6   Peso_unit                  62177 non-null  float64
 7   Peças                      62177 non-null  int64
 8   Caixa_padrão               62177 non-null  string
 9   Loja                       62177 non-null  string
 10  Classe_de_onda             62177 non-null  string
 11  Tipo_de_buffer             62177 non-null  string
 12  Item_pai                   62177 non-null  string
 13  Cor                        62177 non-null  string
 14  Tamanho                    62177 non-null  string
 15  Inner                      62177 non-null  int64
 16  Rota                       62177 non-null  string
 17  Capacidade                 62177 non-null  float64
 18  pai_cor                    62177 non-null  string
 19  chave_loja_buffer_onda     62177 non-null  string
 20  Volume_unit                62177 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(7), string(11)
memory usage: 10.0 MB

Exportar para excel

In [24]:
#df_limite_buffer.to_excel('../../01-Data/ordens_pre_process_revisado.xlsx')