# 0- Imports

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

# 1- Base

Dados de entrada

In [2]:
df_prod = pd.read_excel('../../01-Data/Dados - desafio disciplina RPVMM.xlsx')
df_prod

,Ordem de produção,Data da ordem de produção,Produto,Comprimento unit,Largura unit,Altura unit,Peso unit,Peças,Caixa padrão,Loja,Classe de onda,Tipo de buffer,Item pai,Cor,Tamanho,Inner
0,1,2023-11-07,549326104,472,232,24,0.130,5,CARTON_M,1,1,EN,1,1.0,1,1
1,2,2023-11-14,828646451,284,131,50,0.250,3,CARTON_M,2,2,CX,2,2.0,2,1
2,3,2023-11-09,605410977,250,100,14,0.120,1,CARTON_M,3,1,CX,3,3.0,3,1
3,4,2023-11-20,847250347,460,267,52,0.570,2,CARTON_M,4,3,EN,4,4.0,4,1
4,5,2023-11-17,840651501,480,235,67,0.340,3,CARTON_M,5,4,EN,5,5.0,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,11716,2023-11-27,882142923,545,320,34,0.300,1,CARTON_M,147,4,EN,506,9.0,6,1
99996,11428,2023-11-27,837646815,493,220,50,0.303,1,CARTON_M,12,4,EN,1212,4.0,3,1
99997,11460,2023-11-17,882141251,459,333,21,0.307,1,CARTON_M,129,4,EN,2334,9.0,6,1
99998,11542,2023-11-17,882141269,472,332,22,0.287,2,CARTON_M,37,4,EN,2334,9.0,1,1
99999,11696,2023-11-27,881474521,191,306,33,0.280,2,CARTON_M,50,4,EN,1581,486.0,3,1

In [3]:
vars_string = ['Ordem de produção', 'Produto','Caixa padrão', 'Loja', 'Classe de onda', 
               'Tipo de buffer', 'Item pai', 'Cor', 'Tamanho']

df_prod[vars_string] = df_prod[vars_string].astype('string')

Dados de restrição de capacidade

In [4]:
df_rotas_capacidade = pd.read_excel('../../01-Data/Dados - desafio disciplina RPVMM.xlsx', sheet_name='Rotas_capacidade')
df_rotas_capacidade

    Rota    Capacidade
0      1           inf
1      2  2.720000e+10
2      3           inf
3      4           inf
4      5  2.720000e+10
5      6  2.720000e+10
6      7  4.000000e+10
7      8  4.000000e+10
8      9  2.720000e+10
9     10  2.720000e+10
10    11  2.720000e+10
11    12  1.600000e+10
12    13  2.720000e+10
13    14  7.600000e+10
14    15  4.000000e+10
15    16  2.240000e+10
16    17  2.720000e+10
17    18  2.720000e+10

In [5]:
df_rotas_capacidade['Rota'] = df_rotas_capacidade['Rota'].astype('string')

In [6]:
df_rotas_lojas = pd.read_excel('../../01-Data/Dados - desafio disciplina RPVMM.xlsx', sheet_name='Rotas_lojas')
df_rotas_lojas

     Rota  Loja
0       1    44
1       2     8
2       3    70
3       4   123
4       3   122
..    ...   ...
152     4   102
153     4    32
154     4   144
155     3   151
156     4    29

[157 rows x 2 columns]

In [7]:
df_rotas_lojas[['Rota', 'Loja']] = df_rotas_lojas[['Rota', 'Loja']].astype('string')

## 1.1 Juntar bases

In [8]:
df_rotas = df_rotas_lojas.merge(df_rotas_capacidade, how='left', on='Rota')
df_rotas

    Rota Loja    Capacidade
0      1   44           inf
1      2    8  2.720000e+10
2      3   70           inf
3      4  123           inf
4      3  122           inf
..   ...  ...           ...
152    4  102           inf
153    4   32           inf
154    4  144           inf
155    3  151           inf
156    4   29           inf

[157 rows x 3 columns]

In [9]:
df_prod_completo = df_prod.merge(df_rotas, how='left', on='Loja')
df_prod_completo

,Ordem de produção,Data da ordem de produção,Produto,Comprimento unit,Largura unit,Altura unit,Peso unit,Peças,Caixa padrão,Loja,Classe de onda,Tipo de buffer,Item pai,Cor,Tamanho,Inner,Rota,Capacidade
0,1,2023-11-07,549326104,472,232,24,0.130,5,CARTON_M,1,1,EN,1,1.0,1,1,3,inf
1,2,2023-11-14,828646451,284,131,50,0.250,3,CARTON_M,2,2,CX,2,2.0,2,1,11,2.720000e+10
2,3,2023-11-09,605410977,250,100,14,0.120,1,CARTON_M,3,1,CX,3,3.0,3,1,5,2.720000e+10
3,4,2023-11-20,847250347,460,267,52,0.570,2,CARTON_M,4,3,EN,4,4.0,4,1,14,7.600000e+10
4,5,2023-11-17,840651501,480,235,67,0.340,3,CARTON_M,5,4,EN,5,5.0,5,1,4,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,11716,2023-11-27,882142923,545,320,34,0.300,1,CARTON_M,147,4,EN,506,9.0,6,1,3,inf
99996,11428,2023-11-27,837646815,493,220,50,0.303,1,CARTON_M,12,4,EN,1212,4.0,3,1,3,inf
99997,11460,2023-11-17,882141251,459,333,21,0.307,1,CARTON_M,129,4,EN,2334,9.0,6,1,4,inf
99998,11542,2023-11-17,882141269,472,332,22,0.287,2,CARTON_M,37,4,EN,2334,9.0,1,1,4,inf
99999,11696,2023-11-27,881474521,191,306,33,0.280,2,CARTON_M,50,4,EN,1581,486.0,3,1,3,inf

# 2- Pré-processamanto

A quantidade máxima de **peças em caixas** precisa ser:
<ul>
    <li>120.000 peças para o “Tipo de buffer” CX e </li>
    <li>100.000 peças para o “Tipo de buffer” EN.</li>
 </ul>

In [10]:
df_prod_completo.columns = df_prod_completo.columns.str.replace(' ', '_')

In [11]:
df_prod_completo['Cor'] = df_prod_completo['Cor'].fillna('0')

In [12]:
df_prod_completo['pai_cor'] = df_prod_completo['Item_pai'] + '_' + df_prod_completo['Cor']
df_prod_completo['pai_cor']

0             1_1.0
1             2_2.0
2             3_3.0
3             4_4.0
4             5_5.0
            ...
99995       506_9.0
99996      1212_4.0
99997      2334_9.0
99998      2334_9.0
99999    1581_486.0
Name: pai_cor, Length: 100000, dtype: string

In [13]:
df_prod_completo['chave_loja_buffer_onda'] = df_prod_completo['Loja'] + '_' + df_prod_completo['Tipo_de_buffer'] + '_' + df_prod_completo['Classe_de_onda']

In [14]:
df_completo_FIFO = df_prod_completo.sort_values(by=['Data_da_ordem_de_produção', 'Loja','Classe_de_onda', 'Tipo_de_buffer','pai_cor'])

In [15]:
with pd.option_context('display.max_columns', None):
    display(df_completo_FIFO.head())

,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,Loja,Classe_de_onda,Tipo_de_buffer,Item_pai,Cor,Tamanho,Inner,Rota,Capacidade,pai_cor,chave_loja_buffer_onda
25664,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,26,5,CX,1865,6.0,27,1,1,inf,1865_6.0,26_CX_5
58831,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,26,5,CX,1865,6.0,21,1,1,inf,1865_6.0,26_CX_5
71019,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,26,5,CX,1865,6.0,4,1,1,inf,1865_6.0,26_CX_5
60906,9002,2023-10-16,804068334,116,106,19,0.082,1,CARTON_S,116,6,CX,2489,674.0,179,1,3,inf,2489_674.0,116_CX_6
95321,11552,2023-10-16,825051881,235,110,30,0.092,10,CARTON_M,16,2,CX,2988,451.0,109,1,1,inf,2988_451.0,16_CX_2

Quantidade total de peças por tipo de buffer

In [17]:
df_completo_FIFO.loc[df_completo_FIFO['Tipo_de_buffer'] == 'EN', 'Peças'].sum()

149582

In [18]:
df_completo_FIFO.loc[df_completo_FIFO['Tipo_de_buffer'] == 'CX', 'Peças'].sum()

220000

Observa-se que a base completa tem mais itens do que o limite de produção diário. Por isso, iremos reduzir a quantidae de itens.

## 2.1- Limite buffer

Selecionar o limite do buffer tipo CX

In [20]:
soma = 0
indices = []
tipo_buffer = 'CX'
max = 120000

for index, value in df_completo_FIFO[df_completo_FIFO['Tipo_de_buffer'] == tipo_buffer]['Peças'].items():
    soma += value
    if soma == max:
        indices.append(index)
        break
    elif soma > max:
        soma -= value
        break
    else:
        indices.append(index)

df_limite_buffer_CX = df_completo_FIFO.loc[indices]
df_limite_buffer_CX['Peças'].sum()

119996

Selecionar o limite do buffer tipo EN

In [21]:
soma = 0
indices = []
tipo_buffer = 'EN'
max = 100000

for index, value in df_completo_FIFO[df_completo_FIFO['Tipo_de_buffer'] == tipo_buffer]['Peças'].items():
    soma += value
    if soma == max:
        indices.append(index)
        break
    elif soma > max:
        soma -= value
        break
    else:
        indices.append(index)

df_limite_buffer_EN = df_completo_FIFO.loc[indices]
df_limite_buffer_EN['Peças'].sum()

99999

In [22]:
df_limite_buffer = pd.concat([df_limite_buffer_CX, df_limite_buffer_EN], ignore_index=True)
df_limite_buffer

,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,Loja,Classe_de_onda,Tipo_de_buffer,Item_pai,Cor,Tamanho,Inner,Rota,Capacidade,pai_cor,chave_loja_buffer_onda
0,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,26,5,CX,1865,6.0,27,1,1,inf,1865_6.0,26_CX_5
1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,26,5,CX,1865,6.0,21,1,1,inf,1865_6.0,26_CX_5
2,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,26,5,CX,1865,6.0,4,1,1,inf,1865_6.0,26_CX_5
3,9002,2023-10-16,804068334,116,106,19,0.082,1,CARTON_S,116,6,CX,2489,674.0,179,1,3,inf,2489_674.0,116_CX_6
4,11552,2023-10-16,825051881,235,110,30,0.092,10,CARTON_M,16,2,CX,2988,451.0,109,1,1,inf,2988_451.0,16_CX_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62226,6095,2023-11-22,623412941,420,278,28,0.213,2,CARTON_M,48,2,EN,1863,2.0,38,1,15,4.000000e+10,1863_2.0,48_EN_2
62227,5591,2023-11-22,623412950,427,305,31,0.233,1,CARTON_M,48,2,EN,1863,2.0,58,1,15,4.000000e+10,1863_2.0,48_EN_2
62228,11858,2023-11-22,623412933,408,264,30,0.195,2,CARTON_M,48,2,EN,1863,2.0,16,1,15,4.000000e+10,1863_2.0,48_EN_2
62229,10583,2023-11-22,622808371,371,233,49,0.323,1,CARTON_M,48,2,EN,713,275.0,16,1,15,4.000000e+10,713_275.0,48_EN_2
62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,48,3,EN,15,9.0,6,1,15,4.000000e+10,15_9.0,48_EN_3

Exportar para excel

In [24]:
#df_limite_buffer.to_excel('../../01-Data/ordens_pre_process_revisado.xlsx')