# 0- Imports

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
try:
    from amplpy import AMPL, tools
except ImportError:
    # Caso ocorra um erro ao importar, instala amplpy e tenta importar novamente
    %pip install amplpy
    from amplpy import AMPL, tools

In [3]:
licenca ="default"

In [4]:

ampl = tools.ampl_notebook(
    modules=["highs", "gcg", "gurobi", "cplex"],  # Módulos a serem instalados
    license_uuid=licenca,  # Licença a ser utilizada
    g=globals()  # Instancia o objeto AMPL e registra os comandos mágicos
)

AMPL Development Version 20240606 (MSVC 19.40.33811.0, 64-bit)
Demo license with maintenance expiring 20260131.
Using license file "c:\Users\canda\Desktop\CANDACE\GITHUB\Resolucao_Problemas\.venv\Lib\site-packages\ampl_module_base\bin\ampl.lic".

# 1- Base

Importando a base pré-processada com o limite de produção diário de:
<ul>
    <li>120.000 peças para o “Tipo de buffer” CX e </li>
    <li>100.000 peças para o “Tipo de buffer” EN.</li>
 </ul>

In [5]:
df_process = pd.read_excel('../../01-Data/ordens_pre_process_revisado.xlsx')

df_process

,Unnamed: 0,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Tipo_de_buffer,Item_pai,Cor,Tamanho,Inner,Rota,Capacidade,pai_cor,chave_loja_buffer_onda,Volume_unit
0,0,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,...,CX,1865,6.0,27,1,1,inf,1865_6.0,26_CX_5,3092300
1,1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,...,CX,1865,6.0,21,1,1,inf,1865_6.0,26_CX_5,3321500
2,2,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,...,CX,1865,6.0,4,1,1,inf,1865_6.0,26_CX_5,3537200
3,3,9002,2023-10-16,804068334,116,106,19,0.082,1,CARTON_S,...,CX,2489,674.0,179,1,3,inf,2489_674.0,116_CX_6,233624
4,4,11552,2023-10-16,825051881,235,110,30,0.092,10,CARTON_M,...,CX,2988,451.0,109,1,1,inf,2988_451.0,16_CX_2,775500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62226,62226,6095,2023-11-22,623412941,420,278,28,0.213,2,CARTON_M,...,EN,1863,2.0,38,1,15,4.000000e+10,1863_2.0,48_EN_2,3269280
62227,62227,5591,2023-11-22,623412950,427,305,31,0.233,1,CARTON_M,...,EN,1863,2.0,58,1,15,4.000000e+10,1863_2.0,48_EN_2,4037285
62228,62228,11858,2023-11-22,623412933,408,264,30,0.195,2,CARTON_M,...,EN,1863,2.0,16,1,15,4.000000e+10,1863_2.0,48_EN_2,3231360
62229,62229,10583,2023-11-22,622808371,371,233,49,0.323,1,CARTON_M,...,EN,713,275.0,16,1,15,4.000000e+10,713_275.0,48_EN_2,4235707
62230,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,EN,15,9.0,6,1,15,4.000000e+10,15_9.0,48_EN_3,3156208

In [6]:
df_process = df_process.rename(columns={'Unnamed: 0': "Id"})

In [7]:
df_process = df_process.rename(columns={'Capacidade': "Capacidade_rota"})

In [8]:
df_process.columns

Index(['Id', 'Ordem_de_produção', 'Data_da_ordem_de_produção', 'Produto',
       'Comprimento_unit', 'Largura_unit', 'Altura_unit', 'Peso_unit', 'Peças',
       'Caixa_padrão', 'Loja', 'Classe_de_onda', 'Tipo_de_buffer', 'Item_pai',
       'Cor', 'Tamanho', 'Inner', 'Rota', 'Capacidade_rota', 'pai_cor',
       'chave_loja_buffer_onda', 'Volume_unit'],
      dtype='object')

In [9]:
df_process['tempo_espera_dias'] = (df_process['Data_da_ordem_de_produção'].max() - df_process['Data_da_ordem_de_produção']).dt.days.astype('int16')

In [10]:
# Definir a função para calcular a prioridade
def calcular_prioridade(delta_t):
    diferenca = delta_t_maximo - delta_t
    if diferenca <= 5:
        return delta_t_maximo
    elif diferenca <= 10:
        return delta_t_maximo - 10
    else:
        return delta_t_maximo - 20

In [11]:
delta_t_maximo = df_process['tempo_espera_dias'].max()
df_process['prioridade'] = df_process['tempo_espera_dias'].apply(calcular_prioridade)
df_process

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Cor,Tamanho,Inner,Rota,Capacidade_rota,pai_cor,chave_loja_buffer_onda,Volume_unit,tempo_espera_dias,prioridade
0,0,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,...,6.0,27,1,1,inf,1865_6.0,26_CX_5,3092300,98,98
1,1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,...,6.0,21,1,1,inf,1865_6.0,26_CX_5,3321500,98,98
2,2,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,...,6.0,4,1,1,inf,1865_6.0,26_CX_5,3537200,98,98
3,3,9002,2023-10-16,804068334,116,106,19,0.082,1,CARTON_S,...,674.0,179,1,3,inf,2489_674.0,116_CX_6,233624,37,78
4,4,11552,2023-10-16,825051881,235,110,30,0.092,10,CARTON_M,...,451.0,109,1,1,inf,2988_451.0,16_CX_2,775500,37,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62226,62226,6095,2023-11-22,623412941,420,278,28,0.213,2,CARTON_M,...,2.0,38,1,15,4.000000e+10,1863_2.0,48_EN_2,3269280,0,78
62227,62227,5591,2023-11-22,623412950,427,305,31,0.233,1,CARTON_M,...,2.0,58,1,15,4.000000e+10,1863_2.0,48_EN_2,4037285,0,78
62228,62228,11858,2023-11-22,623412933,408,264,30,0.195,2,CARTON_M,...,2.0,16,1,15,4.000000e+10,1863_2.0,48_EN_2,3231360,0,78
62229,62229,10583,2023-11-22,622808371,371,233,49,0.323,1,CARTON_M,...,275.0,16,1,15,4.000000e+10,713_275.0,48_EN_2,4235707,0,78
62230,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,9.0,6,1,15,4.000000e+10,15_9.0,48_EN_3,3156208,0,78

In [12]:
(df_process['Data_da_ordem_de_produção'].max() - df_process['Data_da_ordem_de_produção']).dt.days.astype('int16').head(300)

0      98
1      98
2      98
3      37
4      37
       ..
295    20
296    20
297    20
298    20
299    20
Name: Data_da_ordem_de_produção, Length: 300, dtype: int16

In [13]:
df_process.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62231 entries, 0 to 62230
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         62231 non-null  int64
 1   Ordem_de_produção          62231 non-null  int64
 2   Data_da_ordem_de_produção  62231 non-null  datetime64[ns]
 3   Produto                    62231 non-null  int64
 4   Comprimento_unit           62231 non-null  int64
 5   Largura_unit               62231 non-null  int64
 6   Altura_unit                62231 non-null  int64
 7   Peso_unit                  62231 non-null  float64
 8   Peças                      62231 non-null  int64
 9   Caixa_padrão               62231 non-null  object
 10  Loja                       62231 non-null  int64
 11  Classe_de_onda             62231 non-null  int64
 12  Tipo_de_buffer             62231 non-null  object
 13  Item_pai                   62231 non-null  int64
 14  Cor                        62231 non-null  float64
 15  Tamanho                    62231 non-null  int64
 16  Inner                      62231 non-null  int64
 17  Rota                       62231 non-null  int64
 18  Capacidade_rota            62231 non-null  float64
 19  pai_cor                    62231 non-null  object
 20  chave_loja_buffer_onda     62231 non-null  object
 21  Volume_unit                62231 non-null  int64
 22  tempo_espera_dias          62231 non-null  int16
 23  prioridade                 62231 non-null  int16
dtypes: datetime64[ns](1), float64(3), int16(2), int64(14), object(4)
memory usage: 10.7+ MB

In [14]:
df_process

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Cor,Tamanho,Inner,Rota,Capacidade_rota,pai_cor,chave_loja_buffer_onda,Volume_unit,tempo_espera_dias,prioridade
0,0,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,...,6.0,27,1,1,inf,1865_6.0,26_CX_5,3092300,98,98
1,1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,...,6.0,21,1,1,inf,1865_6.0,26_CX_5,3321500,98,98
2,2,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,...,6.0,4,1,1,inf,1865_6.0,26_CX_5,3537200,98,98
3,3,9002,2023-10-16,804068334,116,106,19,0.082,1,CARTON_S,...,674.0,179,1,3,inf,2489_674.0,116_CX_6,233624,37,78
4,4,11552,2023-10-16,825051881,235,110,30,0.092,10,CARTON_M,...,451.0,109,1,1,inf,2988_451.0,16_CX_2,775500,37,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62226,62226,6095,2023-11-22,623412941,420,278,28,0.213,2,CARTON_M,...,2.0,38,1,15,4.000000e+10,1863_2.0,48_EN_2,3269280,0,78
62227,62227,5591,2023-11-22,623412950,427,305,31,0.233,1,CARTON_M,...,2.0,58,1,15,4.000000e+10,1863_2.0,48_EN_2,4037285,0,78
62228,62228,11858,2023-11-22,623412933,408,264,30,0.195,2,CARTON_M,...,2.0,16,1,15,4.000000e+10,1863_2.0,48_EN_2,3231360,0,78
62229,62229,10583,2023-11-22,622808371,371,233,49,0.323,1,CARTON_M,...,275.0,16,1,15,4.000000e+10,713_275.0,48_EN_2,4235707,0,78
62230,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,9.0,6,1,15,4.000000e+10,15_9.0,48_EN_3,3156208,0,78

## Caixa padrão

In [15]:
df_caixas_tipo = pd.read_excel('../../01-Data/Dados - desafio disciplina RPVMM_edit.xlsx', sheet_name='Tipos de caixa')
df_caixas_tipo

,Tipo,Tipo de buffer,Comprimento,Largura,Altura,Fator de ocupação,Peças max,Peso max (kg)
0,Caixa 1,CX,380,285,285,0.9,170,23
1,Caixa 2,CX,586,436,272,1.2,170,23
2,Caixa 3,CX,728,427,270,0.9,170,23
3,Caixa 1,EN,380,285,285,0.9,512,23
4,Caixa 2,EN,586,436,272,1.2,512,23
5,Caixa 3,EN,728,427,270,0.9,512,23

In [16]:
df_caixas_tipo.columns = df_caixas_tipo.columns.str.replace(' ', '_')

In [17]:
df_caixas_tipo['volume_util_caixa'] = df_caixas_tipo['Comprimento'] * df_caixas_tipo['Largura'] * df_caixas_tipo['Altura'] * df_caixas_tipo['Fator_de_ocupação']

df_caixas_tipo

,Tipo,Tipo_de_buffer,Comprimento,Largura,Altura,Fator_de_ocupação,Peças_max,Peso_max_(kg),volume_util_caixa
0,Caixa 1,CX,380,285,285,0.9,170,23,27778950.0
1,Caixa 2,CX,586,436,272,1.2,170,23,83393894.4
2,Caixa 3,CX,728,427,270,0.9,170,23,75538008.0
3,Caixa 1,EN,380,285,285,0.9,512,23,27778950.0
4,Caixa 2,EN,586,436,272,1.2,512,23,83393894.4
5,Caixa 3,EN,728,427,270,0.9,512,23,75538008.0

In [18]:
df_caixas_tipo.pivot(index='Tipo_de_buffer', columns=['Tipo','volume_util_caixa'], values=['Peças_max', 'volume_util_caixa']).reset_index()

                  Tipo_de_buffer  Peças_max                        \
Tipo                                Caixa 1    Caixa 2    Caixa 3
volume_util_caixa                27778950.0 83393894.4 75538008.0
0                             CX      170.0      170.0      170.0
1                             EN      512.0      512.0      512.0

                  volume_util_caixa
Tipo                        Caixa 1     Caixa 2     Caixa 3
volume_util_caixa        27778950.0  83393894.4  75538008.0
0                        27778950.0  83393894.4  75538008.0
1                        27778950.0  83393894.4  75538008.0

In [19]:
df_caixas_tipo.pivot(index='Tipo_de_buffer', columns='Tipo', values='volume_util_caixa').add_prefix('volume_util_caixa_').reset_index()

Tipo,Tipo_de_buffer,volume_util_caixa_Caixa 1,volume_util_caixa_Caixa 2,volume_util_caixa_Caixa 3
0,CX,27778950.0,83393894.4,75538008.0
1,EN,27778950.0,83393894.4,75538008.0

In [20]:
df_caixas_tipo.pivot(index='Tipo_de_buffer', columns='Tipo', values='Peças_max').add_prefix('Peças_max_').reset_index()

Tipo Tipo_de_buffer  Peças_max_Caixa 1  Peças_max_Caixa 2  Peças_max_Caixa 3
0                CX                170                170                170
1                EN                512                512                512

In [21]:
df_caixas_tipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tipo               6 non-null      object
 1   Tipo_de_buffer     6 non-null      object
 2   Comprimento        6 non-null      int64
 3   Largura            6 non-null      int64
 4   Altura             6 non-null      int64
 5   Fator_de_ocupação  6 non-null      float64
 6   Peças_max          6 non-null      int64
 7   Peso_max_(kg)      6 non-null      int64
 8   volume_util_caixa  6 non-null      float64
dtypes: float64(2), int64(5), object(2)
memory usage: 564.0+ bytes

In [22]:
df_caixas_tipo.columns

Index(['Tipo', 'Tipo_de_buffer', 'Comprimento', 'Largura', 'Altura',
       'Fator_de_ocupação', 'Peças_max', 'Peso_max_(kg)', 'volume_util_caixa'],
      dtype='object')

Temos um tipo de caixa padrão para cada tipo de buffer

In [23]:
df_caixas_padrao = df_caixas_tipo.loc[[1, 5]]
df_caixas_padrao

,Tipo,Tipo_de_buffer,Comprimento,Largura,Altura,Fator_de_ocupação,Peças_max,Peso_max_(kg),volume_util_caixa
1,Caixa 2,CX,586,436,272,1.2,170,23,83393894.4
5,Caixa 3,EN,728,427,270,0.9,512,23,75538008.0

Levar a capacidade das caixas para cada ordem de produção:

O **número de peças máximo** varia com o buffer. Já o *volume* é igual para ambos os tipos, mudando apenas para o **tipo de caixa**

In [24]:
df_caixa_volume_max= df_caixas_tipo.pivot(index='Tipo_de_buffer', columns='Tipo', values='volume_util_caixa').add_prefix('volume_util_caixa_').reset_index()

df_caixa_volume_max

Tipo,Tipo_de_buffer,volume_util_caixa_Caixa 1,volume_util_caixa_Caixa 2,volume_util_caixa_Caixa 3
0,CX,27778950.0,83393894.4,75538008.0
1,EN,27778950.0,83393894.4,75538008.0

In [25]:
df_process_capacitado = df_process.merge(df_caixa_volume_max, on='Tipo_de_buffer', how='inner')

df_process_capacitado

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Rota,Capacidade_rota,pai_cor,chave_loja_buffer_onda,Volume_unit,tempo_espera_dias,prioridade,volume_util_caixa_Caixa 1,volume_util_caixa_Caixa 2,volume_util_caixa_Caixa 3
0,0,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,...,1,inf,1865_6.0,26_CX_5,3092300,98,98,27778950.0,83393894.4,75538008.0
1,1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,...,1,inf,1865_6.0,26_CX_5,3321500,98,98,27778950.0,83393894.4,75538008.0
2,2,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,...,1,inf,1865_6.0,26_CX_5,3537200,98,98,27778950.0,83393894.4,75538008.0
3,3,9002,2023-10-16,804068334,116,106,19,0.082,1,CARTON_S,...,3,inf,2489_674.0,116_CX_6,233624,37,78,27778950.0,83393894.4,75538008.0
4,4,11552,2023-10-16,825051881,235,110,30,0.092,10,CARTON_M,...,1,inf,2988_451.0,16_CX_2,775500,37,78,27778950.0,83393894.4,75538008.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62226,62226,6095,2023-11-22,623412941,420,278,28,0.213,2,CARTON_M,...,15,4.000000e+10,1863_2.0,48_EN_2,3269280,0,78,27778950.0,83393894.4,75538008.0
62227,62227,5591,2023-11-22,623412950,427,305,31,0.233,1,CARTON_M,...,15,4.000000e+10,1863_2.0,48_EN_2,4037285,0,78,27778950.0,83393894.4,75538008.0
62228,62228,11858,2023-11-22,623412933,408,264,30,0.195,2,CARTON_M,...,15,4.000000e+10,1863_2.0,48_EN_2,3231360,0,78,27778950.0,83393894.4,75538008.0
62229,62229,10583,2023-11-22,622808371,371,233,49,0.323,1,CARTON_M,...,15,4.000000e+10,713_275.0,48_EN_2,4235707,0,78,27778950.0,83393894.4,75538008.0
62230,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,15,4.000000e+10,15_9.0,48_EN_3,3156208,0,78,27778950.0,83393894.4,75538008.0

In [26]:
df_process_capacitado.columns = df_process_capacitado.columns.str.replace(' ', '_')

In [27]:
import numpy as np
df_process_capacitado['volume_util_padrao'] = np.where(df_process_capacitado['Tipo_de_buffer'] == "EN", df_process_capacitado['volume_util_caixa_Caixa_3'], df_process_capacitado['volume_util_caixa_Caixa_2'])

In [28]:
df_process_capacitado = df_process_capacitado.merge(df_caixas_padrao[['Tipo_de_buffer', 'Peças_max']], on='Tipo_de_buffer', how='inner')
df_process_capacitado

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,pai_cor,chave_loja_buffer_onda,Volume_unit,tempo_espera_dias,prioridade,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max
0,0,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,...,1865_6.0,26_CX_5,3092300,98,98,27778950.0,83393894.4,75538008.0,83393894.4,170
1,1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,...,1865_6.0,26_CX_5,3321500,98,98,27778950.0,83393894.4,75538008.0,83393894.4,170
2,2,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,...,1865_6.0,26_CX_5,3537200,98,98,27778950.0,83393894.4,75538008.0,83393894.4,170
3,3,9002,2023-10-16,804068334,116,106,19,0.082,1,CARTON_S,...,2489_674.0,116_CX_6,233624,37,78,27778950.0,83393894.4,75538008.0,83393894.4,170
4,4,11552,2023-10-16,825051881,235,110,30,0.092,10,CARTON_M,...,2988_451.0,16_CX_2,775500,37,78,27778950.0,83393894.4,75538008.0,83393894.4,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62226,62226,6095,2023-11-22,623412941,420,278,28,0.213,2,CARTON_M,...,1863_2.0,48_EN_2,3269280,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512
62227,62227,5591,2023-11-22,623412950,427,305,31,0.233,1,CARTON_M,...,1863_2.0,48_EN_2,4037285,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512
62228,62228,11858,2023-11-22,623412933,408,264,30,0.195,2,CARTON_M,...,1863_2.0,48_EN_2,3231360,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512
62229,62229,10583,2023-11-22,622808371,371,233,49,0.323,1,CARTON_M,...,713_275.0,48_EN_2,4235707,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512
62230,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,15_9.0,48_EN_3,3156208,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512

In [29]:
df_process_capacitado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62231 entries, 0 to 62230
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         62231 non-null  int64
 1   Ordem_de_produção          62231 non-null  int64
 2   Data_da_ordem_de_produção  62231 non-null  datetime64[ns]
 3   Produto                    62231 non-null  int64
 4   Comprimento_unit           62231 non-null  int64
 5   Largura_unit               62231 non-null  int64
 6   Altura_unit                62231 non-null  int64
 7   Peso_unit                  62231 non-null  float64
 8   Peças                      62231 non-null  int64
 9   Caixa_padrão               62231 non-null  object
 10  Loja                       62231 non-null  int64
 11  Classe_de_onda             62231 non-null  int64
 12  Tipo_de_buffer             62231 non-null  object
 13  Item_pai                   62231 non-null  int64
 14  Cor                        62231 non-null  float64
 15  Tamanho                    62231 non-null  int64
 16  Inner                      62231 non-null  int64
 17  Rota                       62231 non-null  int64
 18  Capacidade_rota            62231 non-null  float64
 19  pai_cor                    62231 non-null  object
 20  chave_loja_buffer_onda     62231 non-null  object
 21  Volume_unit                62231 non-null  int64
 22  tempo_espera_dias          62231 non-null  int16
 23  prioridade                 62231 non-null  int16
 24  volume_util_caixa_Caixa_1  62231 non-null  float64
 25  volume_util_caixa_Caixa_2  62231 non-null  float64
 26  volume_util_caixa_Caixa_3  62231 non-null  float64
 27  volume_util_padrao         62231 non-null  float64
 28  Peças_max                  62231 non-null  int64
dtypes: datetime64[ns](1), float64(7), int16(2), int64(15), object(4)
memory usage: 13.1+ MB

In [30]:
df_process_capacitado['chave_loja_buffer_onda'].nunique()

1508

In [31]:
df_sorted_pecas = df_process_capacitado.groupby('chave_loja_buffer_onda')['Peças'].sum()
df_sorted_pecas = df_sorted_pecas.reset_index()
df_sorted_pecas

     chave_loja_buffer_onda  Peças
0                  100_CX_4     17
1                  100_CX_5      2
2                  100_CX_6     43
3                  100_CX_7      5
4                  100_CX_9     28
...                     ...    ...
1503                 9_EN_2    225
1504                 9_EN_3   1127
1505                 9_EN_4   1464
1506                 9_EN_5     32
1507                 9_EN_9      4

[1508 rows x 2 columns]

In [32]:
df_sorted_pecas.query('Peças >= 200').sort_values(by='Peças', ascending=True).head(20)

     chave_loja_buffer_onda  Peças
636                 25_EN_2    200
401                143_EN_1    201
635                 25_EN_1    203
876                 44_CX_3    203
1453                95_EN_4    203
653                 27_CX_3    205
1300                82_EN_1    205
461                 14_CX_3    205
1361                88_CX_4    207
687                 29_EN_3    207
620                 24_CX_9    209
608                 23_EN_2    209
816                  3_CX_3    210
1251                78_EN_3    211
166                119_EN_1    211
1137                67_EN_4    212
1090                63_CX_4    213
1111                65_CX_6    213
1497                 9_CX_5    220
1015                56_CX_4    222

In [33]:
list(df_sorted_pecas.query('Peças >= 400').sort_values(by='Peças', ascending=True).head(20)['chave_loja_buffer_onda'])

['14_EN_4',
 '48_EN_3',
 '34_EN_4',
 '24_EN_3',
 '23_CX_1',
 '44_CX_4',
 '25_EN_3',
 '62_EN_4',
 '21_EN_3',
 '11_EN_3',
 '30_EN_3',
 '17_CX_9',
 '73_EN_4',
 '17_EN_4',
 '9_CX_7',
 '65_EN_4',
 '13_EN_4',
 '20_CX_4',
 '56_EN_4',
 '27_CX_7']

In [34]:
# Selecionar as n lojas maiores de um único buffer
n = 5
lojas_selecionadas_pequenas = list(df_sorted_pecas.query('Peças >= 400').sort_values(by='Peças', ascending=True).head(n)['chave_loja_buffer_onda'])
lojas_selecionadas_pequenas

['14_EN_4', '48_EN_3', '34_EN_4', '24_EN_3', '23_CX_1']

In [35]:
df_process_capacitado.query(f"chave_loja_buffer_onda in ({lojas_selecionadas_pequenas})")

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,pai_cor,chave_loja_buffer_onda,Volume_unit,tempo_espera_dias,prioridade,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max
82,82,47,2023-10-24,534996762,364,167,90,0.090,1,CARTON_M,...,777_1.0,23_CX_1,5470920,29,78,27778950.0,83393894.4,75538008.0,83393894.4,170
83,83,47,2023-10-24,552747022,250,100,9,0.108,2,CARTON_M,...,777_3.0,23_CX_1,225000,29,78,27778950.0,83393894.4,75538008.0,83393894.4,170
84,84,47,2023-10-24,534996800,365,230,45,0.220,4,CARTON_M,...,777_3.0,23_CX_1,3777750,29,78,27778950.0,83393894.4,75538008.0,83393894.4,170
85,85,47,2023-10-24,539354355,250,100,70,0.200,1,CARTON_M,...,777_95.0,23_CX_1,1750000,29,78,27778950.0,83393894.4,75538008.0,83393894.4,170
86,86,47,2023-10-24,539354339,250,100,58,0.175,1,CARTON_M,...,777_95.0,23_CX_1,1450000,29,78,27778950.0,83393894.4,75538008.0,83393894.4,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61794,61794,1157,2023-11-22,873049031,450,306,23,0.287,4,CARTON_M,...,943_18.0,34_EN_4,3167100,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512
61795,61795,8666,2023-11-22,873049102,450,315,20,0.307,2,CARTON_M,...,943_18.0,34_EN_4,2835000,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512
61796,61796,9502,2023-11-22,873049049,450,329,25,0.280,3,CARTON_M,...,943_18.0,34_EN_4,3701250,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512
61797,61797,10907,2023-11-22,873049057,450,326,25,0.273,1,CARTON_M,...,943_18.0,34_EN_4,3667500,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512
62230,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,15_9.0,48_EN_3,3156208,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512

In [36]:
df_process_capacitado.query(f"chave_loja_buffer_onda in ({lojas_selecionadas_pequenas})")['Peças'].sum()

np.int64(2081)

In [37]:
df_process_capacitado["Volume_total"] = df_process_capacitado["Volume_unit"] * df_process_capacitado["Peças"]
df_process_capacitado["Peso_total"] = df_process_capacitado["Peso_unit"] * df_process_capacitado["Peças"]

## Rotas

In [38]:
df_rotas = df_process_capacitado[['Rota', 'Capacidade_rota']].drop_duplicates()
df_rotas

       Rota  Capacidade_rota
0         1              inf
3         3              inf
9        10     2.720000e+10
14        8     4.000000e+10
26        6     2.720000e+10
45       13     2.720000e+10
71       11     2.720000e+10
76       12     1.600000e+10
116       5     2.720000e+10
147      15     4.000000e+10
153       7     4.000000e+10
155       9     2.720000e+10
166       2     2.720000e+10
227      14     7.600000e+10
229       4              inf
1206     17     2.720000e+10
10767    16     2.240000e+10
11023    18     2.720000e+10

# 2- Modelagem

## 2.1- HEURÍSTICA - FFD

First Fit Decreasing

In [39]:
import pandas as pd

def first_fit_decreasing(df, bin_restrictions, route_restrictions):
    # Sort items in decreasing order of volume and increasing order of date (FIFO)
    df_sorted = df.copy()
    df_sorted['Inv_Volume_total'] = (1 / df_sorted['Volume_total']).replace(np.inf, 0)
    df_sorted = df_sorted.sort_values(by=['Data_da_ordem_de_produção', 'Inv_Volume_total'], ascending=True)
    
    # Initialize bins list
    bins = []
    leftover_items = pd.DataFrame(columns=df_sorted.columns)  # Initialize leftover items DataFrame
    
    # Flag to track if a split was made
    split_made = True
    items_to_drop = []
    df_sorted = df_sorted.reset_index(drop=True)
    items_to_add = []

    while len(df_sorted) != 0:
        split_made = False
        df_sorted = df_sorted[~df_sorted.index.isin(items_to_drop)]

        # Add needed items to df_sorted
        if len(items_to_add) != 0:
            df_sorted = pd.concat([df_sorted, pd.DataFrame(items_to_add)])
        items_to_add = []
        df_sorted = df_sorted.reset_index(drop=True)
        items_to_drop = []
        
        # Make a copy of the sorted DataFrame
        df_sorted_copy = df_sorted.copy()
        
        # Iterate over items in the copy of the sorted DataFrame
        for index, item in df_sorted_copy.iterrows():
            # Flag to check if the item is placed
            placed = False
            
            # Try to place the item in existing bins
            for bin in bins:
                if (bin['Volume'] + item['Volume_total']) <= bin["vol_limit"] \
                    and (bin['Peso_total'] + item['Peso_total']) <= 23 \
                    and bin['Amt.Items'] + item['Peças'] <= bin["item_limit"] \
                    and item["Loja"] == bin["Loja"] \
                    and item["Rota"] == bin["Rota"] \
                    and item["Tipo_de_buffer"] == bin["Buffer"] \
                    and item["Classe_de_onda"] == bin["Wave"]:
                    
                    bin['Items'].append(index)
                    bin['Volume'] += item['Volume_total']
                    bin['Peso_total'] += item['Peso_total']
                    bin['Amt.Items'] += item['Peças']

                    # Remove the item from the original DataFrame
                    items_to_drop.append(index)
                    placed = True
                    break
            
            # If the item couldn't be placed entirely, reduce it by "inner" means until it fits into a bin
            while not placed and item['Peças'] > item['Inner']:
                # Reduce the item to its inner size
                detached_portion = item.copy()
                detached_portion['Peças'] = item['Inner']
                detached_portion['Volume_total'] = item['Volume_unit'] * item['Inner']
                detached_portion['Peso_total'] = item['Peso_unit'] * item['Inner']
                
                # Update the remaining portion of the item
                item['Peças'] -= item['Inner']
                item['Volume_total'] -= item['Volume_unit'] * item['Inner']
                item['Peso_total'] -= item['Peso_unit'] * item['Inner']
                
                # Concatenate the reduced portion back to the original DataFrame
                items_to_add.append(detached_portion)
                split_made = True
                
                # Try to place the reduced item in existing bins
                for bin in bins:
                    if (bin['Volume'] + item['Volume_total']) <= bin["vol_limit"] \
                        and (bin['Peso_total'] + item['Peso_total']) <= 23 \
                        and bin['Amt.Items'] + item['Peças'] <= bin["item_limit"] \
                        and item["Loja"] == bin["Loja"] \
                        and item["Rota"] == bin["Rota"] \
                        and item["Tipo_de_buffer"] == bin["Buffer"] \
                        and item["Classe_de_onda"] == bin["Wave"]:
                        
                        bin['Items'].append(index)  # Append index of the appended reduced item
                        bin['Volume'] += item['Volume_total']
                        bin['Peso_total'] += item['Peso_total']
                        bin['Amt.Items'] += item['Peças']

                        items_to_drop.append(index) # Remove the reduced item from the original DataFrame
                        placed = True
                        break
            
            # If the item still couldn't be placed, create a new bin
            if not placed:
                # Check if creating a new bin exceeds route capacity
                if len([bin for bin in bins if bin['Rota'] == item["Rota"]]) >= route_restrictions[route_restrictions["Rota"] == item["Rota"]]["Capacidade_rota"].values[0]:
                    leftover_items = leftover_items.append(item)  # Add item to leftover items DataFrame
                else:
                    bins.append({
                        'Items': [index],
                        'Volume': item['Volume_total'],
                        'Peso_total': item['Peso_total'],
                        'Amt.Items': item['Peças'],
                        "Loja": item["Loja"],
                        "Rota": item["Rota"],
                        "Buffer": item["Tipo_de_buffer"],
                        "Wave": item["Classe_de_onda"],
                        "vol_limit": bin_restrictions[bin_restrictions["Tipo_de_buffer"] == item["Tipo_de_buffer"]]["volume_util_caixa"].values[0],
                        "item_limit": bin_restrictions[bin_restrictions["Tipo_de_buffer"] == item["Tipo_de_buffer"]]["Peças_max"].values[0]
                    })
                    items_to_drop.append(index)
                    placed = True
                    break
    
    return bins, leftover_items

In [40]:
def add_item_loja_column(df):
    # Group by 'Loja' and 'Produto' and use cumcount to assign a sequential number starting from 1
    df['item_loja'] = df.groupby(['Loja']).cumcount() + 1
    return df

### 2.1.1- Situação 1

In [41]:
df_ffd_s1 = df_process_capacitado
df_ffd_s1

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Volume_unit,tempo_espera_dias,prioridade,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max,Volume_total,Peso_total
0,0,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,...,3092300,98,98,27778950.0,83393894.4,75538008.0,83393894.4,170,6184600,1.120
1,1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,...,3321500,98,98,27778950.0,83393894.4,75538008.0,83393894.4,170,9964500,1.800
2,2,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,...,3537200,98,98,27778950.0,83393894.4,75538008.0,83393894.4,170,3537200,0.580
3,3,9002,2023-10-16,804068334,116,106,19,0.082,1,CARTON_S,...,233624,37,78,27778950.0,83393894.4,75538008.0,83393894.4,170,233624,0.082
4,4,11552,2023-10-16,825051881,235,110,30,0.092,10,CARTON_M,...,775500,37,78,27778950.0,83393894.4,75538008.0,83393894.4,170,7755000,0.920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62226,62226,6095,2023-11-22,623412941,420,278,28,0.213,2,CARTON_M,...,3269280,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,6538560,0.426
62227,62227,5591,2023-11-22,623412950,427,305,31,0.233,1,CARTON_M,...,4037285,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,4037285,0.233
62228,62228,11858,2023-11-22,623412933,408,264,30,0.195,2,CARTON_M,...,3231360,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,6462720,0.390
62229,62229,10583,2023-11-22,622808371,371,233,49,0.323,1,CARTON_M,...,4235707,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,4235707,0.323
62230,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,3156208,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,9468624,0.780

In [42]:
df_ffd_s1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62231 entries, 0 to 62230
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         62231 non-null  int64
 1   Ordem_de_produção          62231 non-null  int64
 2   Data_da_ordem_de_produção  62231 non-null  datetime64[ns]
 3   Produto                    62231 non-null  int64
 4   Comprimento_unit           62231 non-null  int64
 5   Largura_unit               62231 non-null  int64
 6   Altura_unit                62231 non-null  int64
 7   Peso_unit                  62231 non-null  float64
 8   Peças                      62231 non-null  int64
 9   Caixa_padrão               62231 non-null  object
 10  Loja                       62231 non-null  int64
 11  Classe_de_onda             62231 non-null  int64
 12  Tipo_de_buffer             62231 non-null  object
 13  Item_pai                   62231 non-null  int64
 14  Cor                        62231 non-null  float64
 15  Tamanho                    62231 non-null  int64
 16  Inner                      62231 non-null  int64
 17  Rota                       62231 non-null  int64
 18  Capacidade_rota            62231 non-null  float64
 19  pai_cor                    62231 non-null  object
 20  chave_loja_buffer_onda     62231 non-null  object
 21  Volume_unit                62231 non-null  int64
 22  tempo_espera_dias          62231 non-null  int16
 23  prioridade                 62231 non-null  int16
 24  volume_util_caixa_Caixa_1  62231 non-null  float64
 25  volume_util_caixa_Caixa_2  62231 non-null  float64
 26  volume_util_caixa_Caixa_3  62231 non-null  float64
 27  volume_util_padrao         62231 non-null  float64
 28  Peças_max                  62231 non-null  int64
 29  Volume_total               62231 non-null  int64
 30  Peso_total                 62231 non-null  float64
dtypes: datetime64[ns](1), float64(8), int16(2), int64(16), object(4)
memory usage: 14.0+ MB

In [43]:
df_ffd_s1['Peças'].sum()

np.int64(219995)

In [44]:
df_ffd_s1['Volume_total'].sum()

np.int64(700949695185)

In [45]:
df_caixas_padrao

,Tipo,Tipo_de_buffer,Comprimento,Largura,Altura,Fator_de_ocupação,Peças_max,Peso_max_(kg),volume_util_caixa
1,Caixa 2,CX,586,436,272,1.2,170,23,83393894.4
5,Caixa 3,EN,728,427,270,0.9,512,23,75538008.0

In [46]:
backlog = df_ffd_s1.copy()
backlog = backlog.reset_index(drop=True)
backlog = add_item_loja_column(backlog)
packed_bins, leftovers = first_fit_decreasing(df_ffd_s1, bin_restrictions=df_caixas_padrao, route_restrictions=df_rotas)
print("Packed bins (new method):")
for i, bin in enumerate(packed_bins):
    print(f"Bin {i+1}: Amt. Items {bin['Amt.Items']} (Total Volume: {bin['Volume']} cubic mm | Total Weight: {bin['Peso_total'] :.4f}kg)")

print(f"\nLeftover items: {leftovers['Peças'].sum()} items")

In [ ]:
from datetime import datetime
import pytz

In [ ]:
SPTz = pytz.timezone("America/Sao_Paulo")
start_time = datetime.now(SPTz)
print(f"Início: {start_time.strftime('%Y-%m-%d %H:%M:%S %Z%z')}")


backlog = df_ffd_s1.copy()
backlog = backlog.reset_index(drop=True)
backlog = add_item_loja_column(backlog)
packed_bins, leftovers = first_fit_decreasing(df_ffd_s1, bin_restrictions=df_caixas_padrao, route_restrictions=df_rotas)
print("Packed bins (new method):")
for i, bin in enumerate(packed_bins):
    print(f"Bin {i+1}: Amt. Items {bin['Amt.Items']} (Total Volume: {bin['Volume']} cubic mm | Total Weight: {bin['Peso_total'] :.4f}kg)")

print(f"\nLeftover items: {leftovers['Peças'].sum()} items")


end_time = datetime.now(SPTz)
duration = end_time - start_time
print(f"Término: {end_time.strftime('%Y-%m-%d %H:%M:%S %Z%z')}")
print(f"Duração: {duration}")

In [ ]:
dgfdgffgd

### 2.1.2- Situação 2

In [46]:
df_ffd_s2 = df_process_capacitado.query("chave_loja_buffer_onda in ('95_EN_4', '25_EN_1', '82_EN_1', '27_CX_3', '14_CX_3')")

df_ffd_s2

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Volume_unit,tempo_espera_dias,prioridade,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max,Volume_total,Peso_total
3419,3419,325,2023-11-07,548143470,304,322,17,0.186,1,CARTON_M,...,1664096,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,1664096,0.186
3420,3420,325,2023-11-07,548143488,296,280,13,0.155,1,CARTON_M,...,1077440,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,1077440,0.155
3421,3421,325,2023-11-07,548143496,313,308,13,0.145,3,CARTON_M,...,1253252,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,3759756,0.435
3422,3422,325,2023-11-07,817850051,418,243,24,0.168,1,CARTON_M,...,2437776,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,2437776,0.168
3423,3423,325,2023-11-07,548143437,316,194,20,0.140,1,CARTON_M,...,1226080,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,1226080,0.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59941,59941,9768,2023-11-21,879747307,320,147,42,0.217,3,CARTON_M,...,1975680,1,78,27778950.0,83393894.4,75538008.0,75538008.0,512,5927040,0.651
59942,59942,9431,2023-11-21,879747260,314,155,67,0.290,3,CARTON_M,...,3260890,1,78,27778950.0,83393894.4,75538008.0,75538008.0,512,9782670,0.870
61368,61368,3016,2023-11-22,883911579,346,184,18,0.090,5,CARTON_M,...,1145952,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,5729760,0.450
61369,61369,8459,2023-11-22,883911587,349,180,19,0.090,9,CARTON_M,...,1193580,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,10742220,0.810
61370,61370,9346,2023-11-22,883911544,342,192,18,0.090,7,CARTON_M,...,1181952,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,8273664,0.630

In [47]:
df_ffd_s2['Peças'].sum()

1021

In [48]:
df_ffd_s2['Volume_total'].sum()

3066413006

In [49]:
backlog = df_ffd_s2.copy()
backlog = backlog.reset_index(drop=True)
backlog = add_item_loja_column(backlog)
packed_bins, leftovers = first_fit_decreasing(df_ffd_s2, bin_restrictions=df_caixas_padrao, route_restrictions=df_rotas)
print("Packed bins (new method):")
for i, bin in enumerate(packed_bins):
    print(f"Bin {i+1}: Amt. Items {bin['Amt.Items']} (Total Volume: {bin['Volume']} cubic mm | Total Weight: {bin['Peso_total'] :.4f}kg)")

print(f"\nLeftover items: {leftovers['Peças'].sum()} items")

Packed bins (new method):
Bin 1: Amt. Items 13 (Total Volume: 75450094 cubic mm | Total Weight: 4.7120kg)
Bin 2: Amt. Items 42 (Total Volume: 83326834 cubic mm | Total Weight: 10.1830kg)
Bin 3: Amt. Items 42 (Total Volume: 83374873 cubic mm | Total Weight: 10.0610kg)
Bin 4: Amt. Items 21 (Total Volume: 75054764 cubic mm | Total Weight: 4.2900kg)
Bin 5: Amt. Items 17 (Total Volume: 74811118 cubic mm | Total Weight: 4.6750kg)
Bin 6: Amt. Items 41 (Total Volume: 75418398 cubic mm | Total Weight: 7.3590kg)
Bin 7: Amt. Items 11 (Total Volume: 75347361 cubic mm | Total Weight: 3.7930kg)
Bin 8: Amt. Items 48 (Total Volume: 75498215 cubic mm | Total Weight: 9.4760kg)
Bin 9: Amt. Items 18 (Total Volume: 74508296 cubic mm | Total Weight: 5.7890kg)
Bin 10: Amt. Items 40 (Total Volume: 82894156 cubic mm | Total Weight: 4.7860kg)
Bin 11: Amt. Items 39 (Total Volume: 83263898 cubic mm | Total Weight: 4.5690kg)
Bin 12: Amt. Items 40 (Total Volume: 83025096 cubic mm | Total Weight: 3.9600kg)
Bin 13: Amt. Items 40 (Total Volume: 83025096 cubic mm | Total Weight: 3.9600kg)
Bin 14: Amt. Items 33 (Total Volume: 83241625 cubic mm | Total Weight: 11.0850kg)
Bin 15: Amt. Items 36 (Total Volume: 82951580 cubic mm | Total Weight: 10.8460kg)
Bin 16: Amt. Items 21 (Total Volume: 75377987 cubic mm | Total Weight: 6.1480kg)
Bin 17: Amt. Items 31 (Total Volume: 74947406 cubic mm | Total Weight: 4.5980kg)
Bin 18: Amt. Items 51 (Total Volume: 80862300 cubic mm | Total Weight: 7.1720kg)
Bin 19: Amt. Items 26 (Total Volume: 74344553 cubic mm | Total Weight: 7.1440kg)
Bin 20: Amt. Items 32 (Total Volume: 75471122 cubic mm | Total Weight: 4.0370kg)
Bin 21: Amt. Items 36 (Total Volume: 75373416 cubic mm | Total Weight: 5.1000kg)
Bin 22: Amt. Items 21 (Total Volume: 75206541 cubic mm | Total Weight: 5.1100kg)
Bin 23: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 24: Amt. Items 27 (Total Volume: 74123758 cubic mm | Total Weight: 6.6700kg)
Bin 25: Amt. Items 40 (Total Volume: 74983347 cubic mm | Total Weight: 5.6590kg)
Bin 26: Amt. Items 41 (Total Volume: 75420053 cubic mm | Total Weight: 6.7160kg)
Bin 27: Amt. Items 30 (Total Volume: 75502064 cubic mm | Total Weight: 7.3170kg)
Bin 28: Amt. Items 32 (Total Volume: 75480067 cubic mm | Total Weight: 4.1470kg)
Bin 29: Amt. Items 47 (Total Volume: 75072750 cubic mm | Total Weight: 5.9570kg)
Bin 30: Amt. Items 13 (Total Volume: 74902904 cubic mm | Total Weight: 3.9070kg)
Bin 31: Amt. Items 25 (Total Volume: 51155365 cubic mm | Total Weight: 3.7530kg)
Bin 32: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 33: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 34: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 35: Amt. Items 10 (Total Volume: 62981054 cubic mm | Total Weight: 2.6800kg)
Bin 36: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 37: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 38: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 39: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 40: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 41: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 42: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 43: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 44: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 45: Amt. Items 40 (Total Volume: 62950911 cubic mm | Total Weight: 7.1900kg)

Leftover items: 0 items

### 2.1.3- Situação 3

In [50]:
df_ffd_s3 = df_process_capacitado.query("chave_loja_buffer_onda in ('14_EN_4', '48_EN_3', '34_EN_4', '24_EN_3')")
df_ffd_s3

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Volume_unit,tempo_espera_dias,prioridade,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max,Volume_total,Peso_total
33666,33666,3135,2023-10-18,799851462,532,230,37,0.283,3,CARTON_M,...,4527320,35,78,27778950.0,83393894.4,75538008.0,75538008.0,512,13581960,0.849
33667,33667,10032,2023-10-18,799851471,519,218,38,0.263,3,CARTON_M,...,4299396,35,78,27778950.0,83393894.4,75538008.0,75538008.0,512,12898188,0.789
33668,33668,11487,2023-10-18,799851497,547,198,41,0.247,2,CARTON_M,...,4440546,35,78,27778950.0,83393894.4,75538008.0,75538008.0,512,8881092,0.494
33669,33669,496,2023-10-18,595814344,505,206,40,0.237,3,CARTON_M,...,4161200,35,78,27778950.0,83393894.4,75538008.0,75538008.0,512,12483600,0.711
33670,33670,376,2023-10-18,595814281,494,209,38,0.267,3,CARTON_M,...,3923348,35,78,27778950.0,83393894.4,75538008.0,75538008.0,512,11770044,0.801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61794,61794,1157,2023-11-22,873049031,450,306,23,0.287,4,CARTON_M,...,3167100,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,12668400,1.148
61795,61795,8666,2023-11-22,873049102,450,315,20,0.307,2,CARTON_M,...,2835000,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,5670000,0.614
61796,61796,9502,2023-11-22,873049049,450,329,25,0.280,3,CARTON_M,...,3701250,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,11103750,0.840
61797,61797,10907,2023-11-22,873049057,450,326,25,0.273,1,CARTON_M,...,3667500,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,3667500,0.273
62230,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,3156208,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,9468624,0.780

In [51]:
df_ffd_s3['Peças'].sum()

1660

In [52]:
df_ffd_s3['Volume_total'].sum()

7156157465

In [53]:
backlog = df_ffd_s3.copy()
backlog = backlog.reset_index(drop=True)
backlog = add_item_loja_column(backlog)
packed_bins, leftovers = first_fit_decreasing(df_ffd_s3, bin_restrictions=df_caixas_padrao, route_restrictions=df_rotas)
print("Packed bins (new method):")
for i, bin in enumerate(packed_bins):
    print(f"Bin {i+1}: Amt. Items {bin['Amt.Items']} (Total Volume: {bin['Volume']} cubic mm | Total Weight: {bin['Peso_total'] :.4f}kg)")

print(f"\nLeftover items: {leftovers['Peças'].sum()} items")

Packed bins (new method):
Bin 1: Amt. Items 20 (Total Volume: 75351100 cubic mm | Total Weight: 5.0520kg)
Bin 2: Amt. Items 17 (Total Volume: 75385572 cubic mm | Total Weight: 4.4920kg)
Bin 3: Amt. Items 29 (Total Volume: 75111013 cubic mm | Total Weight: 5.0600kg)
Bin 4: Amt. Items 15 (Total Volume: 75475524 cubic mm | Total Weight: 4.8800kg)
Bin 5: Amt. Items 21 (Total Volume: 75244900 cubic mm | Total Weight: 4.3750kg)
Bin 6: Amt. Items 19 (Total Volume: 75148112 cubic mm | Total Weight: 4.5680kg)
Bin 7: Amt. Items 17 (Total Volume: 75517682 cubic mm | Total Weight: 6.7960kg)
Bin 8: Amt. Items 14 (Total Volume: 75536610 cubic mm | Total Weight: 4.2790kg)
Bin 9: Amt. Items 18 (Total Volume: 75519972 cubic mm | Total Weight: 5.6830kg)
Bin 10: Amt. Items 22 (Total Volume: 74907849 cubic mm | Total Weight: 5.2990kg)
Bin 11: Amt. Items 18 (Total Volume: 75405462 cubic mm | Total Weight: 5.3950kg)
Bin 12: Amt. Items 24 (Total Volume: 74361392 cubic mm | Total Weight: 5.4940kg)
Bin 13: Amt. Items 24 (Total Volume: 75028837 cubic mm | Total Weight: 5.1750kg)
Bin 14: Amt. Items 28 (Total Volume: 74193908 cubic mm | Total Weight: 4.9180kg)
Bin 15: Amt. Items 19 (Total Volume: 75198106 cubic mm | Total Weight: 8.9890kg)
Bin 16: Amt. Items 14 (Total Volume: 74292768 cubic mm | Total Weight: 3.9150kg)
Bin 17: Amt. Items 13 (Total Volume: 74272776 cubic mm | Total Weight: 4.4300kg)
Bin 18: Amt. Items 26 (Total Volume: 75368515 cubic mm | Total Weight: 6.1420kg)
Bin 19: Amt. Items 24 (Total Volume: 74396698 cubic mm | Total Weight: 4.4020kg)
Bin 20: Amt. Items 15 (Total Volume: 74687758 cubic mm | Total Weight: 4.2640kg)
Bin 21: Amt. Items 13 (Total Volume: 75322870 cubic mm | Total Weight: 4.1150kg)
Bin 22: Amt. Items 14 (Total Volume: 74814048 cubic mm | Total Weight: 4.2270kg)
Bin 23: Amt. Items 10 (Total Volume: 74728384 cubic mm | Total Weight: 4.1700kg)
Bin 24: Amt. Items 15 (Total Volume: 75157236 cubic mm | Total Weight: 4.5220kg)
Bin 25: Amt. Items 13 (Total Volume: 74107477 cubic mm | Total Weight: 4.5790kg)
Bin 26: Amt. Items 11 (Total Volume: 74259190 cubic mm | Total Weight: 4.1500kg)
Bin 27: Amt. Items 13 (Total Volume: 74111766 cubic mm | Total Weight: 4.0950kg)
Bin 28: Amt. Items 21 (Total Volume: 75295134 cubic mm | Total Weight: 6.6860kg)
Bin 29: Amt. Items 14 (Total Volume: 74120415 cubic mm | Total Weight: 4.9690kg)
Bin 30: Amt. Items 16 (Total Volume: 74470637 cubic mm | Total Weight: 4.8960kg)
Bin 31: Amt. Items 26 (Total Volume: 74404960 cubic mm | Total Weight: 5.4200kg)
Bin 32: Amt. Items 23 (Total Volume: 75177784 cubic mm | Total Weight: 6.7140kg)
Bin 33: Amt. Items 30 (Total Volume: 75495952 cubic mm | Total Weight: 5.3920kg)
Bin 34: Amt. Items 29 (Total Volume: 74379491 cubic mm | Total Weight: 8.0040kg)
Bin 35: Amt. Items 19 (Total Volume: 75329263 cubic mm | Total Weight: 5.9830kg)
Bin 36: Amt. Items 25 (Total Volume: 75338128 cubic mm | Total Weight: 7.0380kg)
Bin 37: Amt. Items 20 (Total Volume: 74943258 cubic mm | Total Weight: 5.8670kg)
Bin 38: Amt. Items 21 (Total Volume: 75068088 cubic mm | Total Weight: 7.4800kg)
Bin 39: Amt. Items 17 (Total Volume: 74726214 cubic mm | Total Weight: 6.7000kg)
Bin 40: Amt. Items 17 (Total Volume: 75177444 cubic mm | Total Weight: 5.0900kg)
Bin 41: Amt. Items 20 (Total Volume: 74152075 cubic mm | Total Weight: 5.5430kg)
Bin 42: Amt. Items 28 (Total Volume: 74909177 cubic mm | Total Weight: 7.4600kg)
Bin 43: Amt. Items 24 (Total Volume: 75226523 cubic mm | Total Weight: 5.2900kg)
Bin 44: Amt. Items 24 (Total Volume: 75042344 cubic mm | Total Weight: 6.8780kg)
Bin 45: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 46: Amt. Items 22 (Total Volume: 74543400 cubic mm | Total Weight: 6.1100kg)
Bin 47: Amt. Items 27 (Total Volume: 75307466 cubic mm | Total Weight: 5.5520kg)
Bin 48: Amt. Items 16 (Total Volume: 75429608 cubic mm | Total Weight: 5.6600kg)
Bin 49: Amt. Items 27 (Total Volume: 75338310 cubic mm | Total Weight: 6.1320kg)
Bin 50: Amt. Items 20 (Total Volume: 74462240 cubic mm | Total Weight: 5.9420kg)
Bin 51: Amt. Items 29 (Total Volume: 75321191 cubic mm | Total Weight: 7.0340kg)
Bin 52: Amt. Items 18 (Total Volume: 75308146 cubic mm | Total Weight: 5.5690kg)
Bin 53: Amt. Items 28 (Total Volume: 75048372 cubic mm | Total Weight: 5.5430kg)
Bin 54: Amt. Items 17 (Total Volume: 75077985 cubic mm | Total Weight: 5.9800kg)
Bin 55: Amt. Items 7 (Total Volume: 75005109 cubic mm | Total Weight: 3.0030kg)
Bin 56: Amt. Items 8 (Total Volume: 75393830 cubic mm | Total Weight: 2.8750kg)
Bin 57: Amt. Items 12 (Total Volume: 75340250 cubic mm | Total Weight: 3.8400kg)
Bin 58: Amt. Items 21 (Total Volume: 75094219 cubic mm | Total Weight: 6.2560kg)
Bin 59: Amt. Items 15 (Total Volume: 74909718 cubic mm | Total Weight: 4.5280kg)
Bin 60: Amt. Items 9 (Total Volume: 75297248 cubic mm | Total Weight: 2.8360kg)
Bin 61: Amt. Items 14 (Total Volume: 75533731 cubic mm | Total Weight: 5.3900kg)
Bin 62: Amt. Items 20 (Total Volume: 74502310 cubic mm | Total Weight: 6.0420kg)
Bin 63: Amt. Items 24 (Total Volume: 75437018 cubic mm | Total Weight: 7.2400kg)
Bin 64: Amt. Items 21 (Total Volume: 73889567 cubic mm | Total Weight: 6.3580kg)
Bin 65: Amt. Items 21 (Total Volume: 75093588 cubic mm | Total Weight: 5.4960kg)
Bin 66: Amt. Items 26 (Total Volume: 75126247 cubic mm | Total Weight: 6.5380kg)
Bin 67: Amt. Items 22 (Total Volume: 74368920 cubic mm | Total Weight: 6.4850kg)
Bin 68: Amt. Items 16 (Total Volume: 75261450 cubic mm | Total Weight: 4.8150kg)
Bin 69: Amt. Items 13 (Total Volume: 75281126 cubic mm | Total Weight: 3.5920kg)
Bin 70: Amt. Items 24 (Total Volume: 75234832 cubic mm | Total Weight: 4.6400kg)
Bin 71: Amt. Items 19 (Total Volume: 75421952 cubic mm | Total Weight: 3.3900kg)
Bin 72: Amt. Items 12 (Total Volume: 75091548 cubic mm | Total Weight: 3.4650kg)
Bin 73: Amt. Items 14 (Total Volume: 75535784 cubic mm | Total Weight: 3.9350kg)
Bin 74: Amt. Items 12 (Total Volume: 75300681 cubic mm | Total Weight: 3.8920kg)
Bin 75: Amt. Items 11 (Total Volume: 75027444 cubic mm | Total Weight: 4.3760kg)
Bin 76: Amt. Items 13 (Total Volume: 73597427 cubic mm | Total Weight: 4.8170kg)
Bin 77: Amt. Items 19 (Total Volume: 75212668 cubic mm | Total Weight: 6.0440kg)
Bin 78: Amt. Items 28 (Total Volume: 75262738 cubic mm | Total Weight: 8.3670kg)
Bin 79: Amt. Items 15 (Total Volume: 74196528 cubic mm | Total Weight: 7.4600kg)
Bin 80: Amt. Items 18 (Total Volume: 75106718 cubic mm | Total Weight: 4.7600kg)
Bin 81: Amt. Items 14 (Total Volume: 75139912 cubic mm | Total Weight: 5.1530kg)
Bin 82: Amt. Items 15 (Total Volume: 49459435 cubic mm | Total Weight: 4.0090kg)
Bin 83: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 84: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 85: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 86: Amt. Items 14 (Total Volume: 75510594 cubic mm | Total Weight: 3.5280kg)
Bin 87: Amt. Items 13 (Total Volume: 73807292 cubic mm | Total Weight: 2.9730kg)
Bin 88: Amt. Items 5 (Total Volume: 75463629 cubic mm | Total Weight: 1.8350kg)
Bin 89: Amt. Items 8 (Total Volume: 74170665 cubic mm | Total Weight: 2.3680kg)
Bin 90: Amt. Items 7 (Total Volume: 75453495 cubic mm | Total Weight: 2.6200kg)
Bin 91: Amt. Items 11 (Total Volume: 74757864 cubic mm | Total Weight: 2.9300kg)
Bin 92: Amt. Items 11 (Total Volume: 74784048 cubic mm | Total Weight: 3.4850kg)
Bin 93: Amt. Items 5 (Total Volume: 45315648 cubic mm | Total Weight: 1.0580kg)
Bin 94: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 95: Amt. Items 20 (Total Volume: 74755744 cubic mm | Total Weight: 6.6120kg)
Bin 96: Amt. Items 11 (Total Volume: 58016718 cubic mm | Total Weight: 3.8660kg)
Bin 97: Amt. Items 19 (Total Volume: 68624940 cubic mm | Total Weight: 5.5660kg)

Leftover items: 0 items

### 2.1.4- Situação 4

In [54]:
df_ffd_s4 = df_process_capacitado.query("chave_loja_buffer_onda in ('44_CX_4', '62_EN_4', '21_EN_3', '11_EN_3', '30_EN_3', '17_CX_9', '73_EN_4')")
df_ffd_s4

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Volume_unit,tempo_espera_dias,prioridade,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max,Volume_total,Peso_total
515,515,1490,2023-11-03,542140454,300,237,32,0.230,3,CARTON_M,...,2275200,19,78,27778950.0,83393894.4,75538008.0,83393894.4,170,6825600,0.690
516,516,1053,2023-11-03,542140454,300,237,32,0.230,2,CARTON_M,...,2275200,19,78,27778950.0,83393894.4,75538008.0,83393894.4,170,4550400,0.460
517,517,1490,2023-11-03,542140446,422,216,23,0.187,3,CARTON_M,...,2096496,19,78,27778950.0,83393894.4,75538008.0,83393894.4,170,6289488,0.561
518,518,1490,2023-11-03,542140462,300,295,19,0.153,1,CARTON_M,...,1681500,19,78,27778950.0,83393894.4,75538008.0,83393894.4,170,1681500,0.153
519,519,1053,2023-11-03,542140462,300,295,19,0.153,1,CARTON_M,...,1681500,19,78,27778950.0,83393894.4,75538008.0,83393894.4,170,1681500,0.153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60096,60096,15,2023-11-22,881488746,491,301,17,0.210,20,CARTON_M,...,2512447,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,50248940,4.200
60097,60097,207,2023-11-22,881488762,454,316,22,0.260,6,CARTON_M,...,3156208,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,18937248,1.560
60098,60098,4833,2023-11-22,881488720,481,294,18,0.240,7,CARTON_M,...,2545452,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,17818164,1.680
60099,60099,6014,2023-11-22,881488738,477,289,19,0.220,18,CARTON_M,...,2619207,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,47145726,3.960
60100,60100,7219,2023-11-22,881488754,473,281,20,0.210,7,CARTON_M,...,2658260,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,18607820,1.470

In [55]:
df_ffd_s4['Peças'].sum()

3085

In [56]:
df_ffd_s4['Volume_total'].sum()

12390885045

In [57]:
backlog = df_ffd_s4.copy()
backlog = backlog.reset_index(drop=True)
backlog = add_item_loja_column(backlog)
packed_bins, leftovers = first_fit_decreasing(df_ffd_s4, bin_restrictions=df_caixas_padrao, route_restrictions=df_rotas)
print("Packed bins (new method):")
for i, bin in enumerate(packed_bins):
    print(f"Bin {i+1}: Amt. Items {bin['Amt.Items']} (Total Volume: {bin['Volume']} cubic mm | Total Weight: {bin['Peso_total'] :.4f}kg)")

print(f"\nLeftover items: {leftovers['Peças'].sum()} items")

Packed bins (new method):
Bin 1: Amt. Items 17 (Total Volume: 74891729 cubic mm | Total Weight: 5.8050kg)
Bin 2: Amt. Items 30 (Total Volume: 75238598 cubic mm | Total Weight: 5.5460kg)
Bin 3: Amt. Items 11 (Total Volume: 75494333 cubic mm | Total Weight: 3.9650kg)
Bin 4: Amt. Items 31 (Total Volume: 75434990 cubic mm | Total Weight: 5.5320kg)
Bin 5: Amt. Items 21 (Total Volume: 75328971 cubic mm | Total Weight: 4.5250kg)
Bin 6: Amt. Items 30 (Total Volume: 75394246 cubic mm | Total Weight: 5.3650kg)
Bin 7: Amt. Items 37 (Total Volume: 83362406 cubic mm | Total Weight: 7.7560kg)
Bin 8: Amt. Items 31 (Total Volume: 83341198 cubic mm | Total Weight: 8.3240kg)
Bin 9: Amt. Items 26 (Total Volume: 83004168 cubic mm | Total Weight: 9.9640kg)
Bin 10: Amt. Items 29 (Total Volume: 82995984 cubic mm | Total Weight: 8.0560kg)
Bin 11: Amt. Items 8 (Total Volume: 74305674 cubic mm | Total Weight: 3.3350kg)
Bin 12: Amt. Items 12 (Total Volume: 75219962 cubic mm | Total Weight: 4.8700kg)
Bin 13: Amt. Items 23 (Total Volume: 75505610 cubic mm | Total Weight: 5.5620kg)
Bin 14: Amt. Items 13 (Total Volume: 75099462 cubic mm | Total Weight: 5.3700kg)
Bin 15: Amt. Items 22 (Total Volume: 82826631 cubic mm | Total Weight: 10.6880kg)
Bin 16: Amt. Items 24 (Total Volume: 75244615 cubic mm | Total Weight: 6.0480kg)
Bin 17: Amt. Items 16 (Total Volume: 74808502 cubic mm | Total Weight: 7.0810kg)
Bin 18: Amt. Items 14 (Total Volume: 74682244 cubic mm | Total Weight: 6.7100kg)
Bin 19: Amt. Items 33 (Total Volume: 83359535 cubic mm | Total Weight: 7.7640kg)
Bin 20: Amt. Items 22 (Total Volume: 74398812 cubic mm | Total Weight: 5.4410kg)
Bin 21: Amt. Items 29 (Total Volume: 75217443 cubic mm | Total Weight: 5.1380kg)
Bin 22: Amt. Items 15 (Total Volume: 74162151 cubic mm | Total Weight: 5.5680kg)
Bin 23: Amt. Items 25 (Total Volume: 74263754 cubic mm | Total Weight: 5.1470kg)
Bin 24: Amt. Items 17 (Total Volume: 75172546 cubic mm | Total Weight: 4.8890kg)
Bin 25: Amt. Items 16 (Total Volume: 75450976 cubic mm | Total Weight: 5.2480kg)
Bin 26: Amt. Items 24 (Total Volume: 82915932 cubic mm | Total Weight: 7.9760kg)
Bin 27: Amt. Items 24 (Total Volume: 75492227 cubic mm | Total Weight: 5.3510kg)
Bin 28: Amt. Items 32 (Total Volume: 83315752 cubic mm | Total Weight: 12.2240kg)
Bin 29: Amt. Items 42 (Total Volume: 82605698 cubic mm | Total Weight: 12.8900kg)
Bin 30: Amt. Items 26 (Total Volume: 75330798 cubic mm | Total Weight: 5.4880kg)
Bin 31: Amt. Items 20 (Total Volume: 75071841 cubic mm | Total Weight: 6.6460kg)
Bin 32: Amt. Items 14 (Total Volume: 82983672 cubic mm | Total Weight: 3.4500kg)
Bin 33: Amt. Items 15 (Total Volume: 83088592 cubic mm | Total Weight: 5.1880kg)
Bin 34: Amt. Items 18 (Total Volume: 74794614 cubic mm | Total Weight: 6.7600kg)
Bin 35: Amt. Items 14 (Total Volume: 75394289 cubic mm | Total Weight: 4.6400kg)
Bin 36: Amt. Items 14 (Total Volume: 74428778 cubic mm | Total Weight: 4.6700kg)
Bin 37: Amt. Items 48 (Total Volume: 82396696 cubic mm | Total Weight: 8.9200kg)
Bin 38: Amt. Items 27 (Total Volume: 83264717 cubic mm | Total Weight: 7.8950kg)
Bin 39: Amt. Items 24 (Total Volume: 74573225 cubic mm | Total Weight: 5.1550kg)
Bin 40: Amt. Items 38 (Total Volume: 82931929 cubic mm | Total Weight: 10.0900kg)
Bin 41: Amt. Items 28 (Total Volume: 82910966 cubic mm | Total Weight: 9.9660kg)
Bin 42: Amt. Items 21 (Total Volume: 83259876 cubic mm | Total Weight: 10.3900kg)
Bin 43: Amt. Items 31 (Total Volume: 82468726 cubic mm | Total Weight: 10.1200kg)
Bin 44: Amt. Items 32 (Total Volume: 82505632 cubic mm | Total Weight: 9.6300kg)
Bin 45: Amt. Items 28 (Total Volume: 83223346 cubic mm | Total Weight: 9.8160kg)
Bin 46: Amt. Items 37 (Total Volume: 82645268 cubic mm | Total Weight: 10.9450kg)
Bin 47: Amt. Items 52 (Total Volume: 82765303 cubic mm | Total Weight: 6.3190kg)
Bin 48: Amt. Items 21 (Total Volume: 82434585 cubic mm | Total Weight: 11.1900kg)
Bin 49: Amt. Items 10 (Total Volume: 75222212 cubic mm | Total Weight: 5.6800kg)
Bin 50: Amt. Items 16 (Total Volume: 75219160 cubic mm | Total Weight: 5.8050kg)
Bin 51: Amt. Items 26 (Total Volume: 74233660 cubic mm | Total Weight: 5.7500kg)
Bin 52: Amt. Items 9 (Total Volume: 74835166 cubic mm | Total Weight: 4.8300kg)
Bin 53: Amt. Items 20 (Total Volume: 74826380 cubic mm | Total Weight: 5.4050kg)
Bin 54: Amt. Items 21 (Total Volume: 75148930 cubic mm | Total Weight: 4.8090kg)
Bin 55: Amt. Items 17 (Total Volume: 75005814 cubic mm | Total Weight: 6.0100kg)
Bin 56: Amt. Items 52 (Total Volume: 83199019 cubic mm | Total Weight: 9.4210kg)
Bin 57: Amt. Items 21 (Total Volume: 75444787 cubic mm | Total Weight: 4.0860kg)
Bin 58: Amt. Items 26 (Total Volume: 82893546 cubic mm | Total Weight: 11.7480kg)
Bin 59: Amt. Items 19 (Total Volume: 73824472 cubic mm | Total Weight: 5.4090kg)
Bin 60: Amt. Items 30 (Total Volume: 75510484 cubic mm | Total Weight: 6.0560kg)
Bin 61: Amt. Items 23 (Total Volume: 74446017 cubic mm | Total Weight: 4.8960kg)
Bin 62: Amt. Items 23 (Total Volume: 75448811 cubic mm | Total Weight: 4.3610kg)
Bin 63: Amt. Items 23 (Total Volume: 74283083 cubic mm | Total Weight: 3.5930kg)
Bin 64: Amt. Items 20 (Total Volume: 82248592 cubic mm | Total Weight: 5.3200kg)
Bin 65: Amt. Items 11 (Total Volume: 74170293 cubic mm | Total Weight: 4.4850kg)
Bin 66: Amt. Items 14 (Total Volume: 75390053 cubic mm | Total Weight: 3.7610kg)
Bin 67: Amt. Items 13 (Total Volume: 74859576 cubic mm | Total Weight: 4.9180kg)
Bin 68: Amt. Items 17 (Total Volume: 74337728 cubic mm | Total Weight: 6.9890kg)
Bin 69: Amt. Items 13 (Total Volume: 74095864 cubic mm | Total Weight: 5.5470kg)
Bin 70: Amt. Items 19 (Total Volume: 75385237 cubic mm | Total Weight: 6.6650kg)
Bin 71: Amt. Items 27 (Total Volume: 83172847 cubic mm | Total Weight: 8.7830kg)
Bin 72: Amt. Items 12 (Total Volume: 75422974 cubic mm | Total Weight: 5.1700kg)
Bin 73: Amt. Items 20 (Total Volume: 75349244 cubic mm | Total Weight: 4.9550kg)
Bin 74: Amt. Items 19 (Total Volume: 75443898 cubic mm | Total Weight: 5.4270kg)
Bin 75: Amt. Items 22 (Total Volume: 75271148 cubic mm | Total Weight: 6.4460kg)
Bin 76: Amt. Items 27 (Total Volume: 75391176 cubic mm | Total Weight: 4.6160kg)
Bin 77: Amt. Items 20 (Total Volume: 75300972 cubic mm | Total Weight: 3.9350kg)
Bin 78: Amt. Items 23 (Total Volume: 75300076 cubic mm | Total Weight: 4.9090kg)
Bin 79: Amt. Items 25 (Total Volume: 74821823 cubic mm | Total Weight: 7.1600kg)
Bin 80: Amt. Items 24 (Total Volume: 75386605 cubic mm | Total Weight: 7.0080kg)
Bin 81: Amt. Items 28 (Total Volume: 74842136 cubic mm | Total Weight: 6.3740kg)
Bin 82: Amt. Items 23 (Total Volume: 75025277 cubic mm | Total Weight: 7.7230kg)
Bin 83: Amt. Items 12 (Total Volume: 74920606 cubic mm | Total Weight: 2.8380kg)
Bin 84: Amt. Items 12 (Total Volume: 74580968 cubic mm | Total Weight: 6.4700kg)
Bin 85: Amt. Items 20 (Total Volume: 75189222 cubic mm | Total Weight: 6.8060kg)
Bin 86: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 87: Amt. Items 13 (Total Volume: 75396219 cubic mm | Total Weight: 3.7470kg)
Bin 88: Amt. Items 17 (Total Volume: 74614650 cubic mm | Total Weight: 3.2900kg)
Bin 89: Amt. Items 26 (Total Volume: 75482832 cubic mm | Total Weight: 6.4000kg)
Bin 90: Amt. Items 26 (Total Volume: 74740796 cubic mm | Total Weight: 6.2200kg)
Bin 91: Amt. Items 34 (Total Volume: 74556603 cubic mm | Total Weight: 6.8630kg)
Bin 92: Amt. Items 27 (Total Volume: 75520363 cubic mm | Total Weight: 5.4600kg)
Bin 93: Amt. Items 23 (Total Volume: 75518586 cubic mm | Total Weight: 6.3310kg)
Bin 94: Amt. Items 19 (Total Volume: 75502883 cubic mm | Total Weight: 6.7260kg)
Bin 95: Amt. Items 40 (Total Volume: 75124769 cubic mm | Total Weight: 6.8030kg)
Bin 96: Amt. Items 29 (Total Volume: 74081246 cubic mm | Total Weight: 6.7450kg)
Bin 97: Amt. Items 27 (Total Volume: 75455234 cubic mm | Total Weight: 6.7630kg)
Bin 98: Amt. Items 34 (Total Volume: 74512260 cubic mm | Total Weight: 6.4620kg)
Bin 99: Amt. Items 22 (Total Volume: 74030734 cubic mm | Total Weight: 5.5430kg)
Bin 100: Amt. Items 30 (Total Volume: 74690293 cubic mm | Total Weight: 7.0950kg)
Bin 101: Amt. Items 32 (Total Volume: 74729749 cubic mm | Total Weight: 7.5450kg)
Bin 102: Amt. Items 30 (Total Volume: 74194941 cubic mm | Total Weight: 6.8200kg)
Bin 103: Amt. Items 22 (Total Volume: 75118854 cubic mm | Total Weight: 6.4760kg)
Bin 104: Amt. Items 26 (Total Volume: 75234296 cubic mm | Total Weight: 6.1610kg)
Bin 105: Amt. Items 17 (Total Volume: 75240780 cubic mm | Total Weight: 5.3410kg)
Bin 106: Amt. Items 17 (Total Volume: 74521016 cubic mm | Total Weight: 5.9160kg)
Bin 107: Amt. Items 25 (Total Volume: 75311807 cubic mm | Total Weight: 6.0240kg)
Bin 108: Amt. Items 13 (Total Volume: 75040686 cubic mm | Total Weight: 5.9000kg)
Bin 109: Amt. Items 20 (Total Volume: 74574315 cubic mm | Total Weight: 3.3710kg)
Bin 110: Amt. Items 11 (Total Volume: 75277174 cubic mm | Total Weight: 4.2160kg)
Bin 111: Amt. Items 16 (Total Volume: 75313495 cubic mm | Total Weight: 5.3110kg)
Bin 112: Amt. Items 19 (Total Volume: 75525384 cubic mm | Total Weight: 4.3150kg)
Bin 113: Amt. Items 26 (Total Volume: 68931480 cubic mm | Total Weight: 5.3780kg)
Bin 114: Amt. Items 13 (Total Volume: 83269656 cubic mm | Total Weight: 4.4850kg)
Bin 115: Amt. Items 8 (Total Volume: 59786648 cubic mm | Total Weight: 3.6000kg)
Bin 116: Amt. Items 20 (Total Volume: 83227816 cubic mm | Total Weight: 6.0470kg)
Bin 117: Amt. Items 17 (Total Volume: 74832130 cubic mm | Total Weight: 6.9100kg)
Bin 118: Amt. Items 16 (Total Volume: 41549118 cubic mm | Total Weight: 5.8170kg)
Bin 119: Amt. Items 9 (Total Volume: 74279470 cubic mm | Total Weight: 6.0400kg)
Bin 120: Amt. Items 11 (Total Volume: 73916384 cubic mm | Total Weight: 6.6100kg)
Bin 121: Amt. Items 13 (Total Volume: 75308676 cubic mm | Total Weight: 6.1700kg)
Bin 122: Amt. Items 19 (Total Volume: 74479306 cubic mm | Total Weight: 5.4550kg)
Bin 123: Amt. Items 18 (Total Volume: 73758592 cubic mm | Total Weight: 5.1850kg)
Bin 124: Amt. Items 13 (Total Volume: 75532621 cubic mm | Total Weight: 3.6780kg)
Bin 125: Amt. Items 15 (Total Volume: 75288084 cubic mm | Total Weight: 5.2420kg)
Bin 126: Amt. Items 17 (Total Volume: 74661440 cubic mm | Total Weight: 4.8550kg)
Bin 127: Amt. Items 14 (Total Volume: 75196309 cubic mm | Total Weight: 5.1970kg)
Bin 128: Amt. Items 19 (Total Volume: 75438264 cubic mm | Total Weight: 5.9130kg)
Bin 129: Amt. Items 18 (Total Volume: 62549674 cubic mm | Total Weight: 4.3530kg)
Bin 130: Amt. Items 8 (Total Volume: 37966006 cubic mm | Total Weight: 3.5550kg)
Bin 131: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 132: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 133: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 134: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 135: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 136: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 137: Amt. Items 12 (Total Volume: 75163594 cubic mm | Total Weight: 3.1100kg)
Bin 138: Amt. Items 12 (Total Volume: 74455494 cubic mm | Total Weight: 3.7000kg)
Bin 139: Amt. Items 15 (Total Volume: 75403972 cubic mm | Total Weight: 3.2100kg)
Bin 140: Amt. Items 14 (Total Volume: 74025138 cubic mm | Total Weight: 3.5150kg)
Bin 141: Amt. Items 10 (Total Volume: 69783886 cubic mm | Total Weight: 2.8190kg)
Bin 142: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 143: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 144: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 145: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 146: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 147: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 148: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 149: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 150: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 151: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 152: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 153: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 154: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 155: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 156: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 157: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 158: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 159: Amt. Items 12 (Total Volume: 75457268 cubic mm | Total Weight: 3.2200kg)
Bin 160: Amt. Items 13 (Total Volume: 74263120 cubic mm | Total Weight: 2.8800kg)
Bin 161: Amt. Items 14 (Total Volume: 73460068 cubic mm | Total Weight: 3.0200kg)
Bin 162: Amt. Items 12 (Total Volume: 74793472 cubic mm | Total Weight: 2.8900kg)
Bin 163: Amt. Items 6 (Total Volume: 48989870 cubic mm | Total Weight: 1.5300kg)
Bin 164: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 165: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 166: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 167: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 168: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 169: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 170: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 171: Amt. Items 17 (Total Volume: 74684274 cubic mm | Total Weight: 3.8670kg)
Bin 172: Amt. Items 20 (Total Volume: 74981658 cubic mm | Total Weight: 4.4130kg)
Bin 173: Amt. Items 28 (Total Volume: 75289261 cubic mm | Total Weight: 4.8070kg)
Bin 174: Amt. Items 29 (Total Volume: 74569123 cubic mm | Total Weight: 6.2500kg)
Bin 175: Amt. Items 1 (Total Volume: 2619207 cubic mm | Total Weight: 0.2200kg)

Leftover items: 0 items

### 2.1.5- Situação 5

In [58]:
df_ffd_s5 = df_process_capacitado.query("chave_loja_buffer_onda in ('65_EN_4', '9_CX_7', '13_EN_4', '20_CX_4', '31_CX_6')")
df_ffd_s5

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Volume_unit,tempo_espera_dias,prioridade,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max,Volume_total,Peso_total
204,204,1306,2023-10-31,585574931,450,300,24,0.880,4,CARTON_M,...,3240000,22,78,27778950.0,83393894.4,75538008.0,83393894.4,170,12960000,3.520
205,205,1487,2023-10-31,585574893,450,300,40,0.780,1,CARTON_M,...,5400000,22,78,27778950.0,83393894.4,75538008.0,83393894.4,170,5400000,0.780
206,206,1487,2023-10-31,585574906,450,300,25,0.820,1,CARTON_M,...,3375000,22,78,27778950.0,83393894.4,75538008.0,83393894.4,170,3375000,0.820
207,207,1306,2023-10-31,585574893,450,300,40,0.780,2,CARTON_M,...,5400000,22,78,27778950.0,83393894.4,75538008.0,83393894.4,170,10800000,1.560
208,208,1306,2023-10-31,585574906,450,300,25,0.820,1,CARTON_M,...,3375000,22,78,27778950.0,83393894.4,75538008.0,83393894.4,170,3375000,0.820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60700,60700,1157,2023-11-22,873049031,450,306,23,0.287,4,CARTON_M,...,3167100,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,12668400,1.148
60701,60701,5671,2023-11-22,873049065,450,279,23,0.260,2,CARTON_M,...,2887650,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,5775300,0.520
60702,60702,8666,2023-11-22,873049102,450,315,20,0.307,1,CARTON_M,...,2835000,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,2835000,0.307
60703,60703,9502,2023-11-22,873049049,450,329,25,0.280,4,CARTON_M,...,3701250,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,14805000,1.120
60704,60704,10907,2023-11-22,873049057,450,326,25,0.273,4,CARTON_M,...,3667500,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,14670000,1.092

In [59]:
df_ffd_s5['Peças'].sum()

2290

In [60]:
df_ffd_s5['Volume_total'].sum()

9012843586

In [61]:
backlog = df_ffd_s5.copy()
backlog = backlog.reset_index(drop=True)
backlog = add_item_loja_column(backlog)
packed_bins, leftovers = first_fit_decreasing(df_ffd_s5, bin_restrictions=df_caixas_padrao, route_restrictions=df_rotas)
print("Packed bins (new method):")
for i, bin in enumerate(packed_bins):
    print(f"Bin {i+1}: Amt. Items {bin['Amt.Items']} (Total Volume: {bin['Volume']} cubic mm | Total Weight: {bin['Peso_total'] :.4f}kg)")

print(f"\nLeftover items: {leftovers['Peças'].sum()} items")

Packed bins (new method):
Bin 1: Amt. Items 24 (Total Volume: 75423966 cubic mm | Total Weight: 8.9610kg)
Bin 2: Amt. Items 16 (Total Volume: 74463282 cubic mm | Total Weight: 4.9650kg)
Bin 3: Amt. Items 21 (Total Volume: 83232651 cubic mm | Total Weight: 11.8690kg)
Bin 4: Amt. Items 18 (Total Volume: 82695185 cubic mm | Total Weight: 10.0000kg)
Bin 5: Amt. Items 7 (Total Volume: 83324243 cubic mm | Total Weight: 3.9400kg)
Bin 6: Amt. Items 61 (Total Volume: 83384039 cubic mm | Total Weight: 22.7900kg)
Bin 7: Amt. Items 15 (Total Volume: 75230716 cubic mm | Total Weight: 4.8600kg)
Bin 8: Amt. Items 17 (Total Volume: 83213547 cubic mm | Total Weight: 9.7040kg)
Bin 9: Amt. Items 8 (Total Volume: 83276416 cubic mm | Total Weight: 7.6400kg)
Bin 10: Amt. Items 11 (Total Volume: 83080109 cubic mm | Total Weight: 6.2200kg)
Bin 11: Amt. Items 13 (Total Volume: 82778372 cubic mm | Total Weight: 5.3500kg)
Bin 12: Amt. Items 16 (Total Volume: 83368180 cubic mm | Total Weight: 10.9890kg)
Bin 13: Amt. Items 20 (Total Volume: 75472220 cubic mm | Total Weight: 5.2620kg)
Bin 14: Amt. Items 18 (Total Volume: 83320854 cubic mm | Total Weight: 6.9780kg)
Bin 15: Amt. Items 12 (Total Volume: 80659296 cubic mm | Total Weight: 7.5600kg)
Bin 16: Amt. Items 8 (Total Volume: 83002767 cubic mm | Total Weight: 7.6400kg)
Bin 17: Amt. Items 23 (Total Volume: 83351326 cubic mm | Total Weight: 7.6320kg)
Bin 18: Amt. Items 15 (Total Volume: 75032935 cubic mm | Total Weight: 4.9670kg)
Bin 19: Amt. Items 17 (Total Volume: 74896063 cubic mm | Total Weight: 4.8670kg)
Bin 20: Amt. Items 22 (Total Volume: 82551012 cubic mm | Total Weight: 9.8830kg)
Bin 21: Amt. Items 15 (Total Volume: 82488976 cubic mm | Total Weight: 7.1800kg)
Bin 22: Amt. Items 20 (Total Volume: 75273142 cubic mm | Total Weight: 7.9290kg)
Bin 23: Amt. Items 22 (Total Volume: 83375033 cubic mm | Total Weight: 8.1780kg)
Bin 24: Amt. Items 12 (Total Volume: 80870342 cubic mm | Total Weight: 4.2020kg)
Bin 25: Amt. Items 17 (Total Volume: 75403156 cubic mm | Total Weight: 5.4690kg)
Bin 26: Amt. Items 28 (Total Volume: 83274450 cubic mm | Total Weight: 9.8620kg)
Bin 27: Amt. Items 23 (Total Volume: 74358065 cubic mm | Total Weight: 5.4630kg)
Bin 28: Amt. Items 22 (Total Volume: 83286174 cubic mm | Total Weight: 8.0660kg)
Bin 29: Amt. Items 18 (Total Volume: 83222480 cubic mm | Total Weight: 4.6830kg)
Bin 30: Amt. Items 18 (Total Volume: 82933040 cubic mm | Total Weight: 6.7200kg)
Bin 31: Amt. Items 16 (Total Volume: 82296319 cubic mm | Total Weight: 7.7510kg)
Bin 32: Amt. Items 74 (Total Volume: 83389935 cubic mm | Total Weight: 16.8900kg)
Bin 33: Amt. Items 26 (Total Volume: 82316247 cubic mm | Total Weight: 4.4800kg)
Bin 34: Amt. Items 13 (Total Volume: 82429480 cubic mm | Total Weight: 7.5400kg)
Bin 35: Amt. Items 12 (Total Volume: 81044094 cubic mm | Total Weight: 6.2400kg)
Bin 36: Amt. Items 24 (Total Volume: 83253211 cubic mm | Total Weight: 9.3960kg)
Bin 37: Amt. Items 14 (Total Volume: 82603821 cubic mm | Total Weight: 8.4200kg)
Bin 38: Amt. Items 10 (Total Volume: 80973332 cubic mm | Total Weight: 8.8900kg)
Bin 39: Amt. Items 10 (Total Volume: 81612986 cubic mm | Total Weight: 9.1800kg)
Bin 40: Amt. Items 14 (Total Volume: 75434249 cubic mm | Total Weight: 4.6240kg)
Bin 41: Amt. Items 9 (Total Volume: 81407407 cubic mm | Total Weight: 8.4400kg)
Bin 42: Amt. Items 17 (Total Volume: 74771182 cubic mm | Total Weight: 6.0440kg)
Bin 43: Amt. Items 8 (Total Volume: 81508560 cubic mm | Total Weight: 7.6800kg)
Bin 44: Amt. Items 60 (Total Volume: 82617136 cubic mm | Total Weight: 10.5400kg)
Bin 45: Amt. Items 102 (Total Volume: 72331594 cubic mm | Total Weight: 22.9950kg)
Bin 46: Amt. Items 62 (Total Volume: 79344902 cubic mm | Total Weight: 8.1200kg)
Bin 47: Amt. Items 12 (Total Volume: 82472115 cubic mm | Total Weight: 6.2290kg)
Bin 48: Amt. Items 112 (Total Volume: 83348836 cubic mm | Total Weight: 15.3140kg)
Bin 49: Amt. Items 15 (Total Volume: 83353397 cubic mm | Total Weight: 5.9200kg)
Bin 50: Amt. Items 19 (Total Volume: 75419805 cubic mm | Total Weight: 5.6220kg)
Bin 51: Amt. Items 34 (Total Volume: 83192786 cubic mm | Total Weight: 9.3390kg)
Bin 52: Amt. Items 24 (Total Volume: 83346043 cubic mm | Total Weight: 8.6110kg)
Bin 53: Amt. Items 35 (Total Volume: 83220386 cubic mm | Total Weight: 11.6240kg)
Bin 54: Amt. Items 26 (Total Volume: 82979231 cubic mm | Total Weight: 9.1350kg)
Bin 55: Amt. Items 106 (Total Volume: 55366210 cubic mm | Total Weight: 22.7830kg)
Bin 56: Amt. Items 14 (Total Volume: 75209364 cubic mm | Total Weight: 4.9770kg)
Bin 57: Amt. Items 15 (Total Volume: 82781558 cubic mm | Total Weight: 9.2560kg)
Bin 58: Amt. Items 13 (Total Volume: 74848530 cubic mm | Total Weight: 5.3760kg)
Bin 59: Amt. Items 17 (Total Volume: 74908924 cubic mm | Total Weight: 5.3840kg)
Bin 60: Amt. Items 23 (Total Volume: 75503427 cubic mm | Total Weight: 7.0050kg)
Bin 61: Amt. Items 22 (Total Volume: 83122057 cubic mm | Total Weight: 13.3690kg)
Bin 62: Amt. Items 15 (Total Volume: 74413931 cubic mm | Total Weight: 4.7030kg)
Bin 63: Amt. Items 11 (Total Volume: 75508786 cubic mm | Total Weight: 3.5800kg)
Bin 64: Amt. Items 26 (Total Volume: 75054860 cubic mm | Total Weight: 7.4480kg)
Bin 65: Amt. Items 13 (Total Volume: 75387724 cubic mm | Total Weight: 3.9000kg)
Bin 66: Amt. Items 22 (Total Volume: 75451346 cubic mm | Total Weight: 6.3080kg)
Bin 67: Amt. Items 19 (Total Volume: 74201443 cubic mm | Total Weight: 5.5170kg)
Bin 68: Amt. Items 26 (Total Volume: 75296562 cubic mm | Total Weight: 6.7360kg)
Bin 69: Amt. Items 25 (Total Volume: 73885924 cubic mm | Total Weight: 6.3290kg)
Bin 70: Amt. Items 13 (Total Volume: 74861276 cubic mm | Total Weight: 3.5970kg)
Bin 71: Amt. Items 27 (Total Volume: 74290458 cubic mm | Total Weight: 6.9650kg)
Bin 72: Amt. Items 25 (Total Volume: 75421859 cubic mm | Total Weight: 6.7330kg)
Bin 73: Amt. Items 17 (Total Volume: 75190711 cubic mm | Total Weight: 4.4340kg)
Bin 74: Amt. Items 12 (Total Volume: 74729710 cubic mm | Total Weight: 3.5440kg)
Bin 75: Amt. Items 12 (Total Volume: 73681065 cubic mm | Total Weight: 3.4600kg)
Bin 76: Amt. Items 9 (Total Volume: 75087953 cubic mm | Total Weight: 2.6400kg)
Bin 77: Amt. Items 24 (Total Volume: 75429688 cubic mm | Total Weight: 6.0480kg)
Bin 78: Amt. Items 27 (Total Volume: 74021240 cubic mm | Total Weight: 5.9120kg)
Bin 79: Amt. Items 30 (Total Volume: 74933991 cubic mm | Total Weight: 7.2350kg)
Bin 80: Amt. Items 24 (Total Volume: 74838616 cubic mm | Total Weight: 6.0150kg)
Bin 81: Amt. Items 9 (Total Volume: 75492171 cubic mm | Total Weight: 3.0850kg)
Bin 82: Amt. Items 8 (Total Volume: 75176999 cubic mm | Total Weight: 3.1500kg)
Bin 83: Amt. Items 18 (Total Volume: 74446027 cubic mm | Total Weight: 5.5600kg)
Bin 84: Amt. Items 20 (Total Volume: 74019847 cubic mm | Total Weight: 7.2420kg)
Bin 85: Amt. Items 15 (Total Volume: 74030320 cubic mm | Total Weight: 5.4730kg)
Bin 86: Amt. Items 16 (Total Volume: 83165443 cubic mm | Total Weight: 6.6350kg)
Bin 87: Amt. Items 13 (Total Volume: 75031080 cubic mm | Total Weight: 3.9920kg)
Bin 88: Amt. Items 23 (Total Volume: 83383724 cubic mm | Total Weight: 7.5580kg)
Bin 89: Amt. Items 11 (Total Volume: 80600434 cubic mm | Total Weight: 3.2420kg)
Bin 90: Amt. Items 17 (Total Volume: 82097842 cubic mm | Total Weight: 6.7800kg)
Bin 91: Amt. Items 28 (Total Volume: 79608164 cubic mm | Total Weight: 5.5600kg)
Bin 92: Amt. Items 19 (Total Volume: 66812952 cubic mm | Total Weight: 7.4400kg)
Bin 93: Amt. Items 15 (Total Volume: 75077601 cubic mm | Total Weight: 4.3140kg)
Bin 94: Amt. Items 9 (Total Volume: 6943782 cubic mm | Total Weight: 3.2810kg)
Bin 95: Amt. Items 24 (Total Volume: 74637626 cubic mm | Total Weight: 8.6090kg)
Bin 96: Amt. Items 20 (Total Volume: 75239794 cubic mm | Total Weight: 6.1830kg)
Bin 97: Amt. Items 18 (Total Volume: 74782402 cubic mm | Total Weight: 5.3510kg)
Bin 98: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 99: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 100: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 101: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 102: Amt. Items 2 (Total Volume: 75134853 cubic mm | Total Weight: 0.5800kg)
Bin 103: Amt. Items 14 (Total Volume: 74275548 cubic mm | Total Weight: 3.3700kg)
Bin 104: Amt. Items 13 (Total Volume: 75295866 cubic mm | Total Weight: 3.6000kg)
Bin 105: Amt. Items 13 (Total Volume: 75305218 cubic mm | Total Weight: 3.2100kg)
Bin 106: Amt. Items 11 (Total Volume: 66971258 cubic mm | Total Weight: 2.6040kg)
Bin 107: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 108: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 109: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 110: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 111: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 112: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 113: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 114: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 115: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 116: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 117: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 118: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 119: Amt. Items 1 (Total Volume: 37836288 cubic mm | Total Weight: 0.3100kg)
Bin 120: Amt. Items 5 (Total Volume: 75376968 cubic mm | Total Weight: 1.7250kg)
Bin 121: Amt. Items 5 (Total Volume: 75376968 cubic mm | Total Weight: 1.7250kg)
Bin 122: Amt. Items 8 (Total Volume: 74068506 cubic mm | Total Weight: 3.0500kg)
Bin 123: Amt. Items 17 (Total Volume: 73434283 cubic mm | Total Weight: 5.5600kg)
Bin 124: Amt. Items 6 (Total Volume: 20310450 cubic mm | Total Weight: 1.9000kg)

Leftover items: 0 items

## 2.2- MODELO EXATO

Vamos adicionar uma condição em que o tipo de buffer varia conforme a chave da loja

<p>O peso máximo é mesmo, indenpendente o tipo de buffer. Além disso, nesse momento iremos utilizar o volume padrão para cada buffer</p>

Modelagem matemática 

Dado que temos $n$ tipos de itens $i$ para empacotar, para $k$ lojas, cada um com peso $w_{i k}$, um volume $v_{i k}$, um múltiplo $inner_{i k}$ da quantidade de itens a serem selecionados uma demanda $d_{i k}$, para todo $i \in \{1,...,n\}$ e $k \in \{1,...,r\}$, e um número $m$ de mochilas (caixas) diferentes com capacidade volumétrica $cv_{k}$, uma capacidade de peso $cp$ e uma capacidade em número de peças $np_{k}$, então temos:

$$
\begin{aligned}
\text{minimizar} \quad &\sum_{j = 1}^{m} \sum_{k = 1}^{r} y_{j k} \\
\text{sujeito a} \quad &\sum_{i = 1}^{n} w_{i k} \xi_{i j k}*inner_{i k} \leq cp*y_{j k} \quad \forall j \in \{1,...,m\} , k \in \{1,...,r\}\\
&\sum_{i = 1}^{n} v_{i k} \xi_{i j k} *inner_{i k} \leq cv_{k}*y_{j k} \quad \forall j \in \{1,...,m\} , k \in \{1,...,r\} \\
&\sum_{i = 1}^{n} \xi_{i j k} *inner_{i k} \leq np_{k}*y_{j k} \quad \forall j \in \{1,...,m\} , k \in \{1,...,r\} \\
&\sum_{j = 1}^{m} \xi_{i j k} *inner_{i k} = d_{i k} \quad \forall i \in \{1,...,n\}, k \in \{1,...,r\}\\
&\xi_{i j k} \geq0 \in \mathbb{Z} \quad \forall i \in \{1,...,n\}, j \in \{1,...,m\} , k \in \{1,...,r\} \\
&y_{j k} \in \{0,1\} \quad \forall j \in \{1,...,m\}, k \in \{1,...,r\}
\end{aligned}
$$


 Seja $\quad$ $\xi_{i j k}$= número de itens tipo $i$ adicionados na caixa $j$, para a loja $k$.

In [62]:
%%ampl_eval
reset;

param n;  # número de tipos de itens
param cp; # capacidade de peso de cada caixa
param r;  # número de lojas (rotas)

suffix master IN, binary;
suffix block IN, integer;

set I = 1..n ordered; # tipos de itens
set K = 1..r ordered; # lojas (rotas)
param w {I,K} >= 0; # peso do item tipo i para a loja k
param v {I,K} >= 0; # volume do item tipo i para a loja k
param inner{I,K} >= 0; # múltiplo da quantidade de itens a serem selecionados
param d {I,K} >= 0; # demanda de itens tipo i para a loja k

param cv {K} >= 0; # capacidade volumétrica de cada loja (rota)
param np {K} >= 0; # capacidade em número de peças para cada loja (rota)

param maxVal := max {i in I, k in K} w[i,k];

param maxVal_peso := max {i in I, k in K} w[i,k];
param pecas_caixa:= floor(cp / maxVal_peso);

param soma := sum{i in I, k in K} d[i, k];
param maxbins := ceil(soma / pecas_caixa);

set J = 1..maxbins ordered;

var e {I,J,K} integer >= 0; # número de itens tipo i na caixa j para a chave loja k
var y {J,K} binary; # 1 se a caixa j é usada para a loja k

minimize FO:  sum {j in J, k in K} y[j,k];

s.t. R1_capacidade_mochila_peso {j in J, k in K}:
   sum {i in I} w[i,k] * e[i,j,k] * inner[i,k] <= cp * y[j,k] suffix block j;

s.t. R2_capacidade_mochila_volume {j in J, k in K}:
   sum {i in I} v[i,k] * e[i,j,k] * inner[i,k] <= cv[k] * y[j,k] suffix block j;
   
s.t. R3_capacidade_mochila_pecas {j in J, k in K}:
   sum {i in I} e[i,j,k] * inner[i,k] <= np[k] * y[j,k] suffix block j;

s.t. R4_quantidade_demanda {i in I, k in K}:
   sum {j in J} e[i,j,k]* inner[i,k] = d[i,k] suffix master 1;

### 2.2.1- Situação 1

In [63]:
df_process_situacao1 = df_ffd_s1

df_process_situacao1

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Volume_unit,tempo_espera_dias,prioridade,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max,Volume_total,Peso_total
7129,7129,325,2023-11-07,548143461,309,202,16,0.110,5,CARTON_M,...,998688,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,4993440,0.550
7130,7130,325,2023-11-07,548143470,304,322,17,0.186,1,CARTON_M,...,1664096,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,1664096,0.186
7131,7131,325,2023-11-07,548143488,296,280,13,0.155,1,CARTON_M,...,1077440,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,1077440,0.155
7132,7132,325,2023-11-07,548143496,313,308,13,0.145,1,CARTON_M,...,1253252,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,1253252,0.145
7133,7133,325,2023-11-07,548143429,317,197,22,0.120,2,CARTON_M,...,1373878,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,2747756,0.240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61395,61395,3404,2023-11-22,626471971,381,179,44,0.253,1,CARTON_M,...,3000756,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,3000756,0.253
61396,61396,6199,2023-11-22,626472018,415,208,54,0.280,3,CARTON_M,...,4661280,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,13983840,0.840
61397,61397,7945,2023-11-22,626471998,407,188,43,0.217,3,CARTON_M,...,3290188,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,9870564,0.651
61398,61398,8427,2023-11-22,626471955,403,197,43,0.300,3,CARTON_M,...,3413813,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,10241439,0.900
61399,61399,10798,2023-11-22,626471947,400,185,61,0.315,4,CARTON_M,...,4514000,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,18056000,1.260

In [64]:
df_process_situacao1['Peças_max'].unique()

array([170, 512], dtype=int64)

In [65]:
df_process_situacao1.columns

Index(['Id', 'Ordem_de_produção', 'Data_da_ordem_de_produção', 'Produto',
       'Comprimento_unit', 'Largura_unit', 'Altura_unit', 'Peso_unit', 'Peças',
       'Caixa_padrão', 'Loja', 'Classe_de_onda', 'Tipo_de_buffer', 'Item_pai',
       'Cor', 'Tamanho', 'Inner', 'Rota', 'Capacidade_rota', 'pai_cor',
       'chave_loja_buffer_onda', 'Volume_unit', 'tempo_espera_dias',
       'prioridade', 'volume_util_caixa_Caixa_1', 'volume_util_caixa_Caixa_2',
       'volume_util_caixa_Caixa_3', 'volume_util_padrao', 'Peças_max',
       'Volume_total', 'Peso_total'],
      dtype='object')

#### 2.2.1.1- Entrada de dados no modelo

In [66]:
# Adicionar uma coluna para identificar cada item dentro de cada chave_loja_buffer_onda
df_process_situacao1['item_loja'] = df_process_situacao1.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Peso_unit'

df_matriz_peso = df_process_situacao1.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_peso.columns.name = None

df_matriz_peso

    item_loja  143_EN_1  25_EN_2  44_CX_3
0           1      0.13    0.160    0.110
1           2      0.11    0.220    0.186
2           3      0.13    0.270    0.155
3           4      0.12    0.120    0.145
4           5      0.25    0.113    0.120
..        ...       ...      ...      ...
73         74      0.00    0.253    0.000
74         75      0.00    0.280    0.000
75         76      0.00    0.217    0.000
76         77      0.00    0.300    0.000
77         78      0.00    0.315    0.000

[78 rows x 4 columns]

In [67]:
# Variável avaliada:
variavel_ik = 'Volume_unit'

df_matriz_volume = df_process_situacao1.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_volume.columns.name = None

df_matriz_volume

    item_loja   143_EN_1    25_EN_2    44_CX_3
0           1  2628096.0   859815.0   998688.0
1           2  2872584.0  1426230.0  1664096.0
2           3  3165864.0  2767910.0  1077440.0
3           4  2095510.0  1839120.0  1253252.0
4           5  4732892.0  1952896.0  1373878.0
..        ...        ...        ...        ...
73         74        0.0  3000756.0        0.0
74         75        0.0  4661280.0        0.0
75         76        0.0  3290188.0        0.0
76         77        0.0  3413813.0        0.0
77         78        0.0  4514000.0        0.0

[78 rows x 4 columns]

In [68]:
# Adicionar uma coluna para identificar cada item dentro de cada loja
df_process_situacao1['item_loja'] = df_process_situacao1.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Inner'

df_matriz_inner = df_process_situacao1.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_inner.columns.name = None

df_matriz_inner

    item_loja  143_EN_1  25_EN_2  44_CX_3
0           1       1.0      1.0      1.0
1           2       1.0      1.0      1.0
2           3       1.0      1.0      1.0
3           4       1.0      1.0      1.0
4           5       1.0      1.0      1.0
..        ...       ...      ...      ...
73         74       0.0      1.0      0.0
74         75       0.0      1.0      0.0
75         76       0.0      1.0      0.0
76         77       0.0      1.0      0.0
77         78       0.0      1.0      0.0

[78 rows x 4 columns]

In [69]:
# Adicionar uma coluna para identificar cada item dentro de cada loja
df_process_situacao1['item_loja'] = df_process_situacao1.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Peças'

df_matriz_pecas = df_process_situacao1.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_pecas.columns.name = None

df_matriz_pecas

    item_loja  143_EN_1  25_EN_2  44_CX_3
0           1      19.0      1.0      5.0
1           2      35.0      1.0      1.0
2           3       9.0      1.0      1.0
3           4      20.0      4.0      1.0
4           5       6.0      7.0      2.0
..        ...       ...      ...      ...
73         74       0.0      1.0      0.0
74         75       0.0      3.0      0.0
75         76       0.0      3.0      0.0
76         77       0.0      3.0      0.0
77         78       0.0      4.0      0.0

[78 rows x 4 columns]

Capacidade da caixa como variável

In [70]:
# Variável avaliada:
variavel_ik = 'Peças_max'

df_matriz_caixa_capacidade_pecas = df_process_situacao1.pivot_table(index='chave_loja_buffer_onda',  values= variavel_ik, fill_value=0).reset_index()

df_matriz_caixa_capacidade_pecas.columns.name = None

df_matriz_caixa_capacidade_pecas

  chave_loja_buffer_onda  Peças_max
0               143_EN_1      512.0
1                25_EN_2      512.0
2                44_CX_3      170.0

In [71]:
# Variável avaliada:
variavel_ik = 'volume_util_padrao'

df_matriz_caixa_capacidade_volume = df_process_situacao1.pivot_table(index='chave_loja_buffer_onda',  values= variavel_ik, fill_value=0).reset_index()

df_matriz_caixa_capacidade_volume.columns.name = None

df_matriz_caixa_capacidade_volume

  chave_loja_buffer_onda  volume_util_padrao
0               143_EN_1          75538008.0
1                25_EN_2          75538008.0
2                44_CX_3          83393894.4

Características das peças

In [72]:
peso =  df_matriz_peso
pecas = df_matriz_pecas  #demanda
volume = df_matriz_volume
inner = df_matriz_inner

Características da caixa

In [73]:
cp = 23
cv = df_matriz_caixa_capacidade_volume
np = df_matriz_caixa_capacidade_pecas

#### Parâmetros

In [74]:
cv['volume_util_padrao'].values

array([75538008.        , 75538008.        , 83393894.39999999])

In [75]:
ampl.param["n"] = len(pecas)   # tamanho da loja que tem mais itens

ampl.param["cp"] = cp
ampl.param["r"] = len(volume.columns) -1

cv_ = cv.drop(columns='chave_loja_buffer_onda')
np_ = np.drop(columns='chave_loja_buffer_onda')

v = volume.drop(columns='item_loja')
w = peso.drop(columns='item_loja')
d= pecas.drop(columns='item_loja')
inner_ = inner.drop(columns='item_loja')

ampl.param["w"] = {(i, k): w.iloc[i - 1][k - 1] for i in range(1, len(w)+1) for k in range(1, len(w.columns)+1)}
ampl.param["v"] = {(i, k): v.iloc[i - 1][k - 1] for i in range(1, len(v)+1) for k in range(1, len(v.columns)+1)}
ampl.param["d"] = {(i, k): d.iloc[i - 1][k - 1] for i in range(1, len(d)+1) for k in range(1, len(d.columns)+1)}
ampl.param["inner"] = {(i, k): inner_.iloc[i - 1][k - 1] for i in range(1, len(inner_)+1) for k in range(1, len(inner_.columns)+1)}

ampl.param["cv"] = {(k): cv_.iloc[k - 1] for k in range(1, len(cv_) + 1)}
ampl.param["np"] = {(k): np_.iloc[k - 1] for k in range(1, len(np_)+1)}

In [76]:
ampl.getValue('soma')

604

In [77]:
ampl.getValue('maxbins')

16

In [78]:
ampl.getValue('pecas_caixa')

40

#### 2.2.1.2- Solvers

##### Solver Highs

In [79]:
ampl.option["solver"] = "highs"
ampl.option["highs_options"] = "outlev=1 timelimit=300"
ampl.solve()

HiGHS 1.7.0:   tech:outlev = 1
  lim:time = 300
Running HiGHS 1.7.0 (git hash: 50670fd): Copyright (c) 2024 HiGHS under MIT licence terms
Coefficient ranges:
  Matrix [6e-02, 8e+07]
  Cost   [1e+00, 1e+00]
  Bound  [1e+00, 3e+01]
  RHS    [1e+00, 4e+01]
Presolving model
297 rows, 2496 cols, 9936 nonzeros  0s
297 rows, 2496 cols, 9936 nonzeros  0s
Objective function is integral with scale 1

Solving MIP model with:
   297 rows
   2496 cols (800 binary, 1696 integer, 0 implied int., 0 continuous)
   9936 nonzeros

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   0               inf                  inf        0      0      0         0     0.0s
 R       0       0         0   0.00%   19.28318802     29                33.51%        0      0      0       671     0.0s
 C       0       0         0   0.00%   19.28318802     28                31.13%      168     36      0       757     0.1s
 L       0       0         0   0.00%   19.5098654      20                 2.45%     1195    189      0      1398     0.4s

Solving report
  Status            Optimal
  Primal bound      20
  Dual bound        20
  Gap               0% (tolerance: 0.01%)
  Solution status   feasible
                    20 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            0.44 (total)
                    0.02 (presolve)
                    0.00 (postsolve)
  Nodes             1
  LP iterations     1819 (total)
                    0 (strong br.)
                    727 (separation)
                    421 (heuristics)
HiGHS 1.7.0: optimal solution; objective 20
1819 simplex iterations
1 branching nodes

In [80]:
%%ampl_eval
display d, w, v, inner;

:      d      w        v    inner    :=
1  1   19   0.13    2628100    1
1  2    1   0.16     859815    1
1  3    5   0.11     998688    1
2  1   35   0.11    2872580    1
2  2    1   0.22    1426230    1
2  3    1   0.186   1664100    1
3  1    9   0.13    3165860    1
3  2    1   0.27    2767910    1
3  3    1   0.155   1077440    1
4  1   20   0.12    2095510    1
4  2    4   0.12    1839120    1
4  3    1   0.145   1253250    1
5  1    6   0.25    4732890    1
5  2    7   0.113   1952900    1
5  3    2   0.12    1373880    1
6  1    9   0.23    3645000    1
6  2    4   0.107   1928640    1
6  3    1   0.135   1885670    1
7  1   14   0.22    2962500    1
7  2    4   0.127   1916220    1
7  3    1   0.126   1539650    1
8  1   12   0.2      792810    1
8  2    1   0.218   3741730    1
8  3    1   0.166   2169970    1
9  1    2   0.42    3144150    1
9  2    1   0.1     1915720    1
9  3    1   0.194   2142920    1
10 1    1   0.48    5152000    1
10 2    2   0.13    3721000    1
10 3    1   0.106    654225    1
11 1    1   0.42    5237520    1
11 2    2   0.17    3244020    1
11 3    1   0.186   2473860    1
12 1    1   0.38    5269320    1
12 2    2   0.057   1287420    1
12 3    3   0.53    3674300    1
13 1    2   0.1     4050000    1
13 2    1   0.09    1279390    1
13 3    2   0.166   1234100    1
14 1    2   0.124   2700000    1
14 2    2   0.09    1023980    1
14 3    2   0.15    2184480    1
15 1    2   0.29    2812320    1
15 2    1   0.09    1120830    1
15 3    1   0.173   1009560    1
16 1    1   0.2     4576000    1
16 2    1   0.073   1438490    1
16 3    1   0.214   1149120    1
17 1    1   0.23    1253620    1
17 2    1   0.14    2417760    1
17 3    3   0.14    2013480    1
18 1    1   0.16     625000    1
18 2    3   0.213   3191030    1
18 3    2   0.16    1786400    1
19 1    2   0.11    2509060    1
19 2    3   0.207   2814000    1
19 3    2   0.196   2589420    1
20 1    1   0.22    2779800    1
20 2    2   0.2     2245000    1
20 3    1   0.216   2362500    1
21 1    2   0.11    2068500    1
21 2    1   0.193   3023860    1
21 3    1   0.19    1755990    1
22 1    1   0.38    7934400    1
22 2    2   0.215   3194330    1
22 3   10   0.293   2075320    1
23 1    5   0.37    4690440    1
23 2    1   0.17    3115010    1
23 3    4   0.295   1997260    1
24 1    1   0.4     3665280    1
24 2    3   0.38    6888020    1
24 3   14   0.248   1836450    1
25 1    4   0.14    1697850    1
25 2    1   0.33    5715820    1
25 3    4   0.196   1360220    1
26 1    3   0.12    1723580    1
26 2    2   0.345   6307780    1
26 3   10   0.23    1774500    1
27 1    1   0.57    6293060    1
27 2    4   0.36    6364160    1
27 3    1   0.463   2596750    1
28 1    7   0.155    625000    1
28 2    1   0.315   5190770    1
28 3   13   0.095    814884    1
29 1    4   0.145    625000    1
29 2    2   0.25    4422730    1
29 3    9   0.095    814884    1
30 1    4   0.16     625000    1
30 2    2   0.21    4458160    1
30 3   11   0.095    814884    1
31 1    7   0.145   3734480    1
31 2    2   0.24    5721830    1
31 3   15   0.1     2411550    1
32 1    6   0.135   1874400    1
32 2    1   0.166   2065730    1
32 3   10   0.1     2337400    1
33 1    6   0.128   1867320    1
33 2    4   0.141   2132820    1
33 3   13   0.1     2610940    1
34 1    9   0.124   1582200    1
34 2    2   0.12    2036160    1
34 3   12   0.1     2493430    1
35 1    0   0             0    0
35 2    2   0.159   2043360    1
35 3   14   0.1     2466750    1
36 1    0   0             0    0
36 2    1   0.15    2711730    1
36 3    9   0.1     2288880    1
37 1    0   0             0    0
37 2    1   0.153   2270400    1
37 3    3   0.347   2277910    1
38 1    0   0             0    0
38 2    1   0.178   2493470    1
38 3    3   0.293   2497960    1
39 1    0   0             0    0
39 2    4   0.163   2464380    1
39 3    6   0.313   2150860    1
40 1    0   0             0    0
40 2    3   0.163   2464380    1
40 3    2   0.383   2488800    1
41 1    0   0             0    0
41 2    3   0.188   2579040    1
41 3    6   0.355   3108760    1
42 1    0   0             0    0
42 2    2   0.206   2883460    1
42 3    0   0             0    0
43 1    0   0             0    0
43 2    3   0.19    2665620    1
43 3    0   0             0    0
44 1    0   0             0    0
44 2    2   0.2     2374980    1
44 3    0   0             0    0
45 1    0   0             0    0
45 2    2   0.22    2381480    1
45 3    0   0             0    0
46 1    0   0             0    0
46 2    2   0.2     2324320    1
46 3    0   0             0    0
47 1    0   0             0    0
47 2    2   0.27    4170780    1
47 3    0   0             0    0
48 1    0   0             0    0
48 2    1   0.25    3068440    1
48 3    0   0             0    0
49 1    0   0             0    0
49 2    2   0.22    3006750    1
49 3    0   0             0    0
50 1    0   0             0    0
50 2    5   0.17    1942710    1
50 3    0   0             0    0
51 1    0   0             0    0
51 2    3   0.16    1827440    1
51 3    0   0             0    0
52 1    0   0             0    0
52 2    6   0.21    2521340    1
52 3    0   0             0    0
53 1    0   0             0    0
53 2    6   0.195   2400000    1
53 3    0   0             0    0
54 1    0   0             0    0
54 2    6   0.185   2400000    1
54 3    0   0             0    0
55 1    0   0             0    0
55 2    2   0.27    3142220    1
55 3    0   0             0    0
56 1    0   0             0    0
56 2    4   0.248   3285600    1
56 3    0   0             0    0
57 1    0   0             0    0
57 2    4   0.233   3517810    1
57 3    0   0             0    0
58 1    0   0             0    0
58 2    3   0.225   3597980    1
58 3    0   0             0    0
59 1    0   0             0    0
59 2    1   0.163   2337890    1
59 3    0   0             0    0
60 1    0   0             0    0
60 2    3   0.195   2768190    1
60 3    0   0             0    0
61 1    0   0             0    0
61 2    5   0.11    2123770    1
61 3    0   0             0    0
62 1    0   0             0    0
62 2    4   0.16    2059200    1
62 3    0   0             0    0
63 1    0   0             0    0
63 2    3   0.24    2967550    1
63 3    0   0             0    0
64 1    0   0             0    0
64 2    6   0.13    2351250    1
64 3    0   0             0    0
65 1    0   0             0    0
65 2    3   0.12    1948340    1
65 3    0   0             0    0
66 1    0   0             0    0
66 2    6   0.14    2025510    1
66 3    0   0             0    0
67 1    0   0             0    0
67 2    1   0.24    4517660    1
67 3    0   0             0    0
68 1    0   0             0    0
68 2    1   0.213   3269280    1
68 3    0   0             0    0
69 1    0   0             0    0
69 2    1   0.233   4037280    1
69 3    0   0             0    0
70 1    0   0             0    0
70 2    2   0.19    3015510    1
70 3    0   0             0    0
71 1    0   0             0    0
71 2    3   0.195   3231360    1
71 3    0   0             0    0
72 1    0   0             0    0
72 2    2   0.237   3622960    1
72 3    0   0             0    0
73 1    0   0             0    0
73 2    3   0.263   3918940    1
73 3    0   0             0    0
74 1    0   0             0    0
74 2    1   0.253   3000760    1
74 3    0   0             0    0
75 1    0   0             0    0
75 2    3   0.28    4661280    1
75 3    0   0             0    0
76 1    0   0             0    0
76 2    3   0.217   3290190    1
76 3    0   0             0    0
77 1    0   0             0    0
77 2    3   0.3     3413810    1
77 3    0   0             0    0
78 1    0   0             0    0
78 2    4   0.315   4514000    1
78 3    0   0             0    0
;

In [81]:
e_s1_highs = ampl.getVariable('e').getValues().toPandas()
e_s1_highs = e_s1_highs.reset_index()
e_s1_highs.columns = ['item_loja','caixa', 'chave_loja_buffer_onda', 'valor_multiplo']
e_s1_highs = e_s1_highs.query('valor_multiplo >0')
e_s1_highs#.head(20)

      item_loja  caixa  chave_loja_buffer_onda  valor_multiplo
2             1      1                       3               5
18            1      7                       1              17
19            1      7                       2               1
36            1     13                       1               2
69            2      8                       1              14
...         ...    ...                     ...             ...
3547         74     15                       2               1
3568         75      6                       2               3
3640         76     14                       2               3
3682         77     12                       2               3
3712         78      6                       2               4

[188 rows x 4 columns]

In [82]:
df_agrupamento_loja1_highs_s1 = e_s1_highs.query('chave_loja_buffer_onda == 1').pivot_table(index='item_loja', columns='caixa', values='valor_multiplo', fill_value=0)
df_agrupamento_loja1_highs_s1 = df_agrupamento_loja1_highs_s1.reset_index()
df_agrupamento_loja1_highs_s1.columns.name = None
df_agrupamento_loja1_highs_s1 # as colunas são as caixas

    item_loja    4     7     8    10    11    13   16
0           1  0.0  17.0   0.0   0.0   0.0   2.0  0.0
1           2  0.0   0.0  14.0   0.0  21.0   0.0  0.0
2           3  1.0   0.0   0.0   8.0   0.0   0.0  0.0
3           4  0.0   0.0   0.0  20.0   0.0   0.0  0.0
4           5  6.0   0.0   0.0   0.0   0.0   0.0  0.0
5           6  0.0   0.0   0.0   0.0   0.0   0.0  9.0
6           7  0.0   0.0   0.0   0.0   0.0  14.0  0.0
7           8  0.0   0.0  11.0   0.0   0.0   1.0  0.0
8           9  0.0   0.0   0.0   2.0   0.0   0.0  0.0
9          10  0.0   0.0   0.0   0.0   0.0   0.0  1.0
10         11  0.0   0.0   0.0   0.0   0.0   1.0  0.0
11         12  0.0   0.0   0.0   0.0   0.0   1.0  0.0
12         13  0.0   0.0   0.0   0.0   0.0   0.0  2.0
13         14  2.0   0.0   0.0   0.0   0.0   0.0  0.0
14         15  1.0   1.0   0.0   0.0   0.0   0.0  0.0
15         16  0.0   0.0   0.0   0.0   1.0   0.0  0.0
16         17  1.0   0.0   0.0   0.0   0.0   0.0  0.0
17         18  0.0   0.0   0.0   0.0   1.0   0.0  0.0
18         19  0.0   1.0   0.0   0.0   0.0   0.0  1.0
19         20  0.0   0.0   0.0   0.0   0.0   1.0  0.0
20         21  2.0   0.0   0.0   0.0   0.0   0.0  0.0
21         22  0.0   0.0   0.0   0.0   0.0   0.0  1.0
22         23  5.0   0.0   0.0   0.0   0.0   0.0  0.0
23         24  0.0   0.0   0.0   0.0   1.0   0.0  0.0
24         25  0.0   0.0   0.0   0.0   1.0   2.0  1.0
25         26  2.0   0.0   0.0   1.0   0.0   0.0  0.0
26         27  0.0   0.0   0.0   0.0   0.0   0.0  1.0
27         28  2.0   5.0   0.0   0.0   0.0   0.0  0.0
28         29  1.0   0.0   0.0   0.0   3.0   0.0  0.0
29         30  0.0   0.0   0.0   0.0   1.0   0.0  3.0
30         31  0.0   6.0   1.0   0.0   0.0   0.0  0.0
31         32  0.0   0.0   2.0   0.0   0.0   0.0  4.0
32         33  0.0   0.0   0.0   0.0   0.0   6.0  0.0
33         34  1.0   0.0   8.0   0.0   0.0   0.0  0.0

In [83]:
vetores_por_loja = {}

# Iterar sobre cada grupo (grupo de cada loja)
for nome_loja, grupo in df_process_situacao1.groupby('chave_loja_buffer_onda'):
    # Extrair os IDs do grupo como um vetor
    vetor_ids = grupo['Id'].tolist()
    # Adicionar o vetor à lista de vetores, usando o nome da loja como chave
    vetores_por_loja[nome_loja] = vetor_ids
    # Atribuir o vetor a uma variável com o nome da loja
    exec(f'vetor_{nome_loja} = vetor_ids')

In [84]:
# Lista dos caracteres finais dos nomes dos vetores
char_final = [col for col in w.columns[:3]]

# Criar o dicionário mapeando os caracteres finais aos vetores
vetores = {char: globals()[f'vetor_{char}'] for char in char_final}

In [85]:
df_agrupamento_loja1_highs_s1['Id'] = vetores[f"{w.columns[0]}"]
df_agrupamento_loja1_highs_s1['chave_loja_buffer_onda'] = list(w.columns)[0]

df_agrupamento_loja1_highs_s1

,item_loja,4,7,8,10,11,13,16,Id,chave_loja_buffer_onda
0,1,0.0,17.0,0.0,0.0,0.0,2.0,0.0,35743,143_EN_1
1,2,0.0,0.0,14.0,0.0,21.0,0.0,0.0,35744,143_EN_1
2,3,1.0,0.0,0.0,8.0,0.0,0.0,0.0,35745,143_EN_1
3,4,0.0,0.0,0.0,20.0,0.0,0.0,0.0,35746,143_EN_1
4,5,6.0,0.0,0.0,0.0,0.0,0.0,0.0,35747,143_EN_1
5,6,0.0,0.0,0.0,0.0,0.0,0.0,9.0,35748,143_EN_1
6,7,0.0,0.0,0.0,0.0,0.0,14.0,0.0,35749,143_EN_1
7,8,0.0,0.0,11.0,0.0,0.0,1.0,0.0,35750,143_EN_1
8,9,0.0,0.0,0.0,2.0,0.0,0.0,0.0,35751,143_EN_1
9,10,0.0,0.0,0.0,0.0,0.0,0.0,1.0,35752,143_EN_1
10,11,0.0,0.0,0.0,0.0,0.0,1.0,0.0,35753,143_EN_1
11,12,0.0,0.0,0.0,0.0,0.0,1.0,0.0,35754,143_EN_1
12,13,0.0,0.0,0.0,0.0,0.0,0.0,2.0,35755,143_EN_1
13,14,2.0,0.0,0.0,0.0,0.0,0.0,0.0,35756,143_EN_1
14,15,1.0,1.0,0.0,0.0,0.0,0.0,0.0,35757,143_EN_1
15,16,0.0,0.0,0.0,0.0,1.0,0.0,0.0,35758,143_EN_1
16,17,1.0,0.0,0.0,0.0,0.0,0.0,0.0,35759,143_EN_1
17,18,0.0,0.0,0.0,0.0,1.0,0.0,0.0,35760,143_EN_1
18,19,0.0,1.0,0.0,0.0,0.0,0.0,1.0,35761,143_EN_1
19,20,0.0,0.0,0.0,0.0,0.0,1.0,0.0,40004,143_EN_1
20,21,2.0,0.0,0.0,0.0,0.0,0.0,0.0,44958,143_EN_1
21,22,0.0,0.0,0.0,0.0,0.0,0.0,1.0,44959,143_EN_1
22,23,5.0,0.0,0.0,0.0,0.0,0.0,0.0,44960,143_EN_1
23,24,0.0,0.0,0.0,0.0,1.0,0.0,0.0,44961,143_EN_1
24,25,0.0,0.0,0.0,0.0,1.0,2.0,1.0,44962,143_EN_1
25,26,2.0,0.0,0.0,1.0,0.0,0.0,0.0,44963,143_EN_1
26,27,0.0,0.0,0.0,0.0,0.0,0.0,1.0,49193,143_EN_1
27,28,2.0,5.0,0.0,0.0,0.0,0.0,0.0,57714,143_EN_1
28,29,1.0,0.0,0.0,0.0,3.0,0.0,0.0,57715,143_EN_1
29,30,0.0,0.0,0.0,0.0,1.0,0.0,3.0,57716,143_EN_1
30,31,0.0,6.0,1.0,0.0,0.0,0.0,0.0,57717,143_EN_1
31,32,0.0,0.0,2.0,0.0,0.0,0.0,4.0,57718,143_EN_1
32,33,0.0,0.0,0.0,0.0,0.0,6.0,0.0,57719,143_EN_1
33,34,1.0,0.0,8.0,0.0,0.0,0.0,0.0,57720,143_EN_1

In [86]:
df_agrupamento_loja2_highs_s1 = e_s1_highs.query('chave_loja_buffer_onda == 2').pivot_table(index='item_loja', columns='caixa', values='valor_multiplo', fill_value=0)
df_agrupamento_loja2_highs_s1 = df_agrupamento_loja2_highs_s1.reset_index()
df_agrupamento_loja2_highs_s1.columns.name = None
df_agrupamento_loja2_highs_s1['Id'] = vetores[f"{w.columns[1]}"]
df_agrupamento_loja2_highs_s1['chave_loja_buffer_onda'] = list(w.columns)[1]

df_agrupamento_loja2_highs_s1

,item_loja,1,3,6,7,8,12,14,15,Id,chave_loja_buffer_onda
0,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,36663,25_EN_2
1,2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,40115,25_EN_2
2,3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,40116,25_EN_2
3,4,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,41031,25_EN_2
4,5,0.0,0.0,0.0,0.0,0.0,0.0,1.0,6.0,41032,25_EN_2
...,...,...,...,...,...,...,...,...,...,...,...
73,74,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,61395,25_EN_2
74,75,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,61396,25_EN_2
75,76,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,61397,25_EN_2
76,77,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,61398,25_EN_2
77,78,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,61399,25_EN_2

In [87]:
y_s1_highs = ampl.getVariable('y').getValues().toPandas()
y_s1_highs = y_s1_highs.reset_index()
y_s1_highs.columns = ['Caixa','chave_loja_buffer_onda', 'selecao']
y_s1_highs = y_s1_highs.query('selecao>0')

df_caixas_por_loja_highs_s1 = y_s1_highs.pivot_table(index='Caixa', columns='chave_loja_buffer_onda', values='selecao', fill_value=0)
df_caixas_por_loja_highs_s1 = df_caixas_por_loja_highs_s1.reset_index()
df_caixas_por_loja_highs_s1.columns.name = None
df_caixas_por_loja_highs_s1 # as colunas são as lojas

    Caixa    1    2    3
0       1  0.0  1.0  1.0
1       3  0.0  1.0  0.0
2       4  1.0  0.0  0.0
3       6  0.0  1.0  0.0
4       7  1.0  1.0  1.0
5       8  1.0  1.0  0.0
6       9  0.0  0.0  1.0
7      10  1.0  0.0  1.0
8      11  1.0  0.0  0.0
9      12  0.0  1.0  1.0
10     13  1.0  0.0  0.0
11     14  0.0  1.0  0.0
12     15  0.0  1.0  0.0
13     16  1.0  0.0  0.0

In [88]:
df_caixas_por_loja_highs_s1.columns = (['caixas'] + list(w.columns)) # os número das colunas são os nomes das lojas
df_caixas_por_loja_highs_s1

    caixas  143_EN_1  25_EN_2  44_CX_3
0        1       0.0      1.0      1.0
1        3       0.0      1.0      0.0
2        4       1.0      0.0      0.0
3        6       0.0      1.0      0.0
4        7       1.0      1.0      1.0
5        8       1.0      1.0      0.0
6        9       0.0      0.0      1.0
7       10       1.0      0.0      1.0
8       11       1.0      0.0      0.0
9       12       0.0      1.0      1.0
10      13       1.0      0.0      0.0
11      14       0.0      1.0      0.0
12      15       0.0      1.0      0.0
13      16       1.0      0.0      0.0

##### Caixas

In [89]:
print('Solver Highs')
total_caixas = 0
for col in w.columns:
    print(f'número de caixas para a chave_loja_buffer_onda "{col}": {df_caixas_por_loja_highs_s1[col].sum()}')
    total_caixas += df_caixas_por_loja_highs_s1[col].sum()
print(f'\ntotal de caixas: {total_caixas}')

Solver Highs
número de caixas para a chave_loja_buffer_onda "143_EN_1": 7.0
número de caixas para a chave_loja_buffer_onda "25_EN_2": 8.0
número de caixas para a chave_loja_buffer_onda "44_CX_3": 5.0

total de caixas: 20.0

### 2.2.2- Situação 2

In [90]:
df_process_situacao2 = df_ffd_s2

df_process_situacao2

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Volume_unit,tempo_espera_dias,prioridade,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max,Volume_total,Peso_total
3419,3419,325,2023-11-07,548143470,304,322,17,0.186,1,CARTON_M,...,1664096,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,1664096,0.186
3420,3420,325,2023-11-07,548143488,296,280,13,0.155,1,CARTON_M,...,1077440,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,1077440,0.155
3421,3421,325,2023-11-07,548143496,313,308,13,0.145,3,CARTON_M,...,1253252,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,3759756,0.435
3422,3422,325,2023-11-07,817850051,418,243,24,0.168,1,CARTON_M,...,2437776,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,2437776,0.168
3423,3423,325,2023-11-07,548143437,316,194,20,0.140,1,CARTON_M,...,1226080,15,78,27778950.0,83393894.4,75538008.0,83393894.4,170,1226080,0.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59941,59941,9768,2023-11-21,879747307,320,147,42,0.217,3,CARTON_M,...,1975680,1,78,27778950.0,83393894.4,75538008.0,75538008.0,512,5927040,0.651
59942,59942,9431,2023-11-21,879747260,314,155,67,0.290,3,CARTON_M,...,3260890,1,78,27778950.0,83393894.4,75538008.0,75538008.0,512,9782670,0.870
61368,61368,3016,2023-11-22,883911579,346,184,18,0.090,5,CARTON_M,...,1145952,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,5729760,0.450
61369,61369,8459,2023-11-22,883911587,349,180,19,0.090,9,CARTON_M,...,1193580,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,10742220,0.810
61370,61370,9346,2023-11-22,883911544,342,192,18,0.090,7,CARTON_M,...,1181952,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,8273664,0.630

#### 2.2.2.1- Entrada de dados no modelo

In [91]:
# Adicionar uma coluna para identificar cada item dentro de cada chave_loja_buffer_onda
df_process_situacao2['item_loja'] = df_process_situacao2.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Peso_unit'

df_matriz_peso = df_process_situacao2.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_peso.columns.name = None

df_matriz_peso

    item_loja  14_CX_3  25_EN_1  27_CX_3  82_EN_1  95_EN_4
0           1    0.186    0.120    0.186     0.13    0.260
1           2    0.155    0.250    0.155     0.11    0.253
2           3    0.145    0.230    0.140     0.13    0.253
3           4    0.168    0.136    0.156     0.25    0.280
4           5    0.140    0.100    0.135     0.23    0.267
..        ...      ...      ...      ...      ...      ...
75         76    0.000    0.000    0.000     0.00    0.240
76         77    0.000    0.000    0.000     0.00    0.203
77         78    0.000    0.000    0.000     0.00    0.230
78         79    0.000    0.000    0.000     0.00    0.217
79         80    0.000    0.000    0.000     0.00    0.290

[80 rows x 6 columns]

In [92]:
# Variável avaliada:
variavel_ik = 'Volume_unit'

df_matriz_volume = df_process_situacao2.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_volume.columns.name = None

df_matriz_volume

    item_loja    14_CX_3    25_EN_1    27_CX_3    82_EN_1    95_EN_4
0           1  1664096.0  2095510.0  1664096.0  2628096.0  3576430.0
1           2  1077440.0  4732892.0  1077440.0  2872584.0  3449628.0
2           3  1253252.0  3645000.0  1226080.0  3165864.0  3449628.0
3           4  2437776.0   625000.0  4084248.0  4732892.0  3536260.0
4           5  1226080.0  1975320.0  1885674.0  3645000.0  3532896.0
..        ...        ...        ...        ...        ...        ...
75         76        0.0        0.0        0.0        0.0  2108970.0
76         77        0.0        0.0        0.0        0.0  3133260.0
77         78        0.0        0.0        0.0        0.0  1725116.0
78         79        0.0        0.0        0.0        0.0  1975680.0
79         80        0.0        0.0        0.0        0.0  3260890.0

[80 rows x 6 columns]

In [93]:
# Adicionar uma coluna para identificar cada item dentro de cada loja
df_process_situacao2['item_loja'] = df_process_situacao2.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Inner'

df_matriz_inner = df_process_situacao2.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_inner.columns.name = None

df_matriz_inner

    item_loja  14_CX_3  25_EN_1  27_CX_3  82_EN_1  95_EN_4
0           1      1.0      1.0      1.0      1.0      1.0
1           2      1.0      1.0      1.0      1.0      1.0
2           3      1.0      1.0      1.0      1.0      1.0
3           4      1.0      1.0      1.0      1.0      1.0
4           5      1.0      1.0      1.0      1.0      1.0
..        ...      ...      ...      ...      ...      ...
75         76      0.0      0.0      0.0      0.0      1.0
76         77      0.0      0.0      0.0      0.0      1.0
77         78      0.0      0.0      0.0      0.0      1.0
78         79      0.0      0.0      0.0      0.0      1.0
79         80      0.0      0.0      0.0      0.0      1.0

[80 rows x 6 columns]

In [94]:
# Adicionar uma coluna para identificar cada item dentro de cada loja
df_process_situacao2['item_loja'] = df_process_situacao2.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Peças'

df_matriz_pecas = df_process_situacao2.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_pecas.columns.name = None

df_matriz_pecas

    item_loja  14_CX_3  25_EN_1  27_CX_3  82_EN_1  95_EN_4
0           1      1.0      3.0      2.0      2.0      1.0
1           2      1.0      1.0      3.0      8.0      1.0
2           3      3.0      2.0      3.0      4.0      2.0
3           4      1.0      1.0      2.0      1.0      1.0
4           5      1.0      3.0      2.0      3.0      3.0
..        ...      ...      ...      ...      ...      ...
75         76      0.0      0.0      0.0      0.0      4.0
76         77      0.0      0.0      0.0      0.0      1.0
77         78      0.0      0.0      0.0      0.0      5.0
78         79      0.0      0.0      0.0      0.0      3.0
79         80      0.0      0.0      0.0      0.0      3.0

[80 rows x 6 columns]

Capacidade da caixa como variável

In [95]:
# Variável avaliada:
variavel_ik = 'Peças_max'

df_matriz_caixa_capacidade_pecas = df_process_situacao2.pivot_table(index='chave_loja_buffer_onda',  values= variavel_ik, fill_value=0).reset_index()

df_matriz_caixa_capacidade_pecas.columns.name = None

df_matriz_caixa_capacidade_pecas

  chave_loja_buffer_onda  Peças_max
0                14_CX_3      170.0
1                25_EN_1      512.0
2                27_CX_3      170.0
3                82_EN_1      512.0
4                95_EN_4      512.0

In [96]:
# Variável avaliada:
variavel_ik = 'volume_util_padrao'

df_matriz_caixa_capacidade_volume = df_process_situacao2.pivot_table(index='chave_loja_buffer_onda',  values= variavel_ik, fill_value=0).reset_index()

df_matriz_caixa_capacidade_volume.columns.name = None

df_matriz_caixa_capacidade_volume

  chave_loja_buffer_onda  volume_util_padrao
0                14_CX_3          83393894.4
1                25_EN_1          75538008.0
2                27_CX_3          83393894.4
3                82_EN_1          75538008.0
4                95_EN_4          75538008.0

In [97]:
peso =  df_matriz_peso
pecas = df_matriz_pecas  #demanda
volume = df_matriz_volume
inner = df_matriz_inner

In [98]:
cp = 23
cv = df_matriz_caixa_capacidade_volume
np = df_matriz_caixa_capacidade_pecas

#### Parâmetros

In [99]:
ampl.param["n"] = len(pecas)   # tamanho da loja que tem mais itens

ampl.param["cp"] = cp
ampl.param["r"] = len(volume.columns) -1

cv_ = cv.drop(columns='chave_loja_buffer_onda')
np_ = np.drop(columns='chave_loja_buffer_onda')

v = volume.drop(columns='item_loja')
w = peso.drop(columns='item_loja')
d= pecas.drop(columns='item_loja')
inner_ = inner.drop(columns='item_loja')

ampl.param["w"] = {(i, k): w.iloc[i - 1][k - 1] for i in range(1, len(w)+1) for k in range(1, len(w.columns)+1)}
ampl.param["v"] = {(i, k): v.iloc[i - 1][k - 1] for i in range(1, len(v)+1) for k in range(1, len(v.columns)+1)}
ampl.param["d"] = {(i, k): d.iloc[i - 1][k - 1] for i in range(1, len(d)+1) for k in range(1, len(d.columns)+1)}
ampl.param["inner"] = {(i, k): inner_.iloc[i - 1][k - 1] for i in range(1, len(inner_)+1) for k in range(1, len(inner_.columns)+1)}

ampl.param["cv"] = {(k): cv_.iloc[k - 1] for k in range(1, len(cv_) + 1)}
ampl.param["np"] = {(k): np_.iloc[k - 1] for k in range(1, len(np_)+1)}

#### 2.2.2.2- Solvers

In [100]:
ampl.option["solver"] = "highs"
ampl.option["highs_options"] = "outlev=1 timelimit=300"
ampl.solve()

HiGHS 1.7.0:   tech:outlev = 1
  lim:time = 300
Running HiGHS 1.7.0 (git hash: 50670fd): Copyright (c) 2024 HiGHS under MIT licence terms
Coefficient ranges:
  Matrix [8e-02, 8e+07]
  Cost   [1e+00, 1e+00]
  Bound  [1e+00, 2e+01]
  RHS    [1e+00, 2e+01]
Presolving model
Presolve: Infeasible

Solving report
  Status            Infeasible
  Primal bound      inf
  Dual bound        -inf
  Gap               inf
  Solution status   -
  Timing            0.01 (total)
                    0.01 (presolve)
                    0.00 (postsolve)
  Nodes             0
  LP iterations     0 (total)
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
Coefficient ranges:
  Matrix [8e-02, 8e+07]
  Cost   [1e+00, 1e+00]
  Bound  [1e+00, 2e+01]
  RHS    [1e+00, 2e+01]
Presolving model
637 rows, 6399 cols, 25461 nonzeros  0s
637 rows, 6399 cols, 25461 nonzeros  0s
Objective function is integral with scale 1

Solving MIP model with:
   637 rows
   6399 cols (1863 binary, 4536 integer, 0 implied int., 0 continuous)
   25461 nonzeros

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   0               inf                  inf        0      0      0         0     0.0s
 R       0       0         0   0.00%   39.57040301     64                38.17%        0      0      0      1395     0.1s
 C       0       0         0   0.00%   39.57040301     63                37.19%      495    115      0      1720     0.2s
 L       0       0         0   0.00%   39.57040301     42                 5.78%     1399    388      0      2360     1.0s

Symmetry detection completed in 0.2s
Found 132 generators

 B      23       1         7  75.09%   39.57040301     41                 3.49%     1399    198     48      6082     3.4s
      2044     347       562  97.06%   39.57040301     41                 3.49%     2564    238   1748     41692     8.4s
      2725      14      1019  99.58%   39.57040301     41                 3.49%     3520    325   4087     69132    14.0s

Solving report
  Status            Optimal
  Primal bound      41
  Dual bound        41
  Gap               0% (tolerance: 0.01%)
  Solution status   feasible
                    41 (objective)
                    0 (bound viol.)
                    1.50990331349e-14 (int. viol.)
                    0 (row viol.)
  Timing            14.31 (total)
                    0.03 (presolve)
                    0.00 (postsolve)
  Nodes             2793
  LP iterations     70263 (total)
                    158 (strong br.)
                    5584 (separation)
                    8550 (heuristics)
HiGHS 1.7.0: optimal solution; objective 41
70263 simplex iterations
2793 branching nodes

In [101]:
e_s2_highs = ampl.getVariable('e').getValues().toPandas()
e_s2_highs = e_s2_highs.reset_index()
e_s2_highs.columns = ['item_loja','caixa', 'chave_loja_buffer_onda', 'valor_multiplo']
e_s2_highs = e_s2_highs.query('valor_multiplo >0')
e_s2_highs#.head(20)

       item_loja  caixa  chave_loja_buffer_onda  valor_multiplo
10             1      3                       1    3.745138e-15
13             1      3                       4    1.000000e+00
19             1      4                       5    1.000000e+00
27             1      6                       3    2.000000e+00
46             1     10                       2    1.000000e+00
...          ...    ...                     ...             ...
10399         78      1                       5    5.000000e+00
10421         78      6                       2    4.000000e+00
10624         79     19                       5    2.000000e+00
10649         79     24                       5    1.000000e+00
10699         80      7                       5    3.000000e+00

[430 rows x 4 columns]

In [102]:
y_s2_highs = ampl.getVariable('y').getValues().toPandas()
y_s2_highs = y_s2_highs.reset_index()
y_s2_highs.columns = ['Caixa','chave_loja_buffer_onda', 'selecao']
y_s2_highs = y_s2_highs.query('selecao>0')

df_caixas_por_loja_highs_s2 = y_s2_highs.pivot_table(index='Caixa', columns='chave_loja_buffer_onda', values='selecao', fill_value=0)
df_caixas_por_loja_highs_s2 = df_caixas_por_loja_highs_s2.reset_index()
df_caixas_por_loja_highs_s2.columns.name = None
df_caixas_por_loja_highs_s2 # as colunas são as lojas

    Caixa    1    2    3    4    5
0       1  0.0  0.0  0.0  0.0  1.0
1       3  1.0  0.0  1.0  1.0  1.0
2       4  0.0  0.0  0.0  0.0  1.0
3       5  0.0  0.0  0.0  0.0  1.0
4       6  0.0  0.0  1.0  0.0  1.0
5       7  0.0  0.0  0.0  0.0  1.0
6       8  0.0  1.0  0.0  0.0  1.0
7      10  0.0  1.0  0.0  0.0  1.0
8      11  1.0  0.0  1.0  0.0  1.0
9      12  0.0  0.0  1.0  0.0  1.0
10     13  0.0  0.0  0.0  0.0  1.0
11     14  0.0  0.0  0.0  0.0  1.0
12     15  0.0  1.0  0.0  1.0  0.0
13     16  0.0  1.0  0.0  1.0  0.0
14     17  1.0  1.0  0.0  0.0  1.0
15     19  0.0  0.0  0.0  0.0  1.0
16     20  0.0  0.0  0.0  0.0  1.0
17     21  0.0  0.0  1.0  0.0  1.0
18     22  0.0  1.0  0.0  0.0  1.0
19     23  1.0  0.0  0.0  1.0  0.0
20     24  0.0  0.0  0.0  1.0  1.0
21     25  0.0  0.0  0.0  1.0  1.0
22     26  1.0  0.0  0.0  0.0  0.0

In [103]:
df_caixas_por_loja_highs_s2.columns = (['caixas'] + list(w.columns)) # os número das colunas são os nomes das lojas
df_caixas_por_loja_highs_s2

    caixas  14_CX_3  25_EN_1  27_CX_3  82_EN_1  95_EN_4
0        1      0.0      0.0      0.0      0.0      1.0
1        3      1.0      0.0      1.0      1.0      1.0
2        4      0.0      0.0      0.0      0.0      1.0
3        5      0.0      0.0      0.0      0.0      1.0
4        6      0.0      0.0      1.0      0.0      1.0
5        7      0.0      0.0      0.0      0.0      1.0
6        8      0.0      1.0      0.0      0.0      1.0
7       10      0.0      1.0      0.0      0.0      1.0
8       11      1.0      0.0      1.0      0.0      1.0
9       12      0.0      0.0      1.0      0.0      1.0
10      13      0.0      0.0      0.0      0.0      1.0
11      14      0.0      0.0      0.0      0.0      1.0
12      15      0.0      1.0      0.0      1.0      0.0
13      16      0.0      1.0      0.0      1.0      0.0
14      17      1.0      1.0      0.0      0.0      1.0
15      19      0.0      0.0      0.0      0.0      1.0
16      20      0.0      0.0      0.0      0.0      1.0
17      21      0.0      0.0      1.0      0.0      1.0
18      22      0.0      1.0      0.0      0.0      1.0
19      23      1.0      0.0      0.0      1.0      0.0
20      24      0.0      0.0      0.0      1.0      1.0
21      25      0.0      0.0      0.0      1.0      1.0
22      26      1.0      0.0      0.0      0.0      0.0

#### Caixas

In [104]:
print('Solver Highs')
total_caixas = 0
for col in w.columns:
    print(f'número de caixas para a chave_loja_buffer_onda "{col}": {df_caixas_por_loja_highs_s2[col].sum()}')
    total_caixas += df_caixas_por_loja_highs_s2[col].sum()
print(f'\ntotal de caixas: {total_caixas}')

Solver Highs
número de caixas para a chave_loja_buffer_onda "14_CX_3": 5.0
número de caixas para a chave_loja_buffer_onda "25_EN_1": 6.0
número de caixas para a chave_loja_buffer_onda "27_CX_3": 5.0
número de caixas para a chave_loja_buffer_onda "82_EN_1": 6.0
número de caixas para a chave_loja_buffer_onda "95_EN_4": 19.0

total de caixas: 41.0

### 2.2.3- Situação 3

In [105]:
df_process_situacao3 = df_ffd_s3

df_process_situacao3

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Volume_unit,tempo_espera_dias,prioridade,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max,Volume_total,Peso_total
33666,33666,3135,2023-10-18,799851462,532,230,37,0.283,3,CARTON_M,...,4527320,35,78,27778950.0,83393894.4,75538008.0,75538008.0,512,13581960,0.849
33667,33667,10032,2023-10-18,799851471,519,218,38,0.263,3,CARTON_M,...,4299396,35,78,27778950.0,83393894.4,75538008.0,75538008.0,512,12898188,0.789
33668,33668,11487,2023-10-18,799851497,547,198,41,0.247,2,CARTON_M,...,4440546,35,78,27778950.0,83393894.4,75538008.0,75538008.0,512,8881092,0.494
33669,33669,496,2023-10-18,595814344,505,206,40,0.237,3,CARTON_M,...,4161200,35,78,27778950.0,83393894.4,75538008.0,75538008.0,512,12483600,0.711
33670,33670,376,2023-10-18,595814281,494,209,38,0.267,3,CARTON_M,...,3923348,35,78,27778950.0,83393894.4,75538008.0,75538008.0,512,11770044,0.801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61794,61794,1157,2023-11-22,873049031,450,306,23,0.287,4,CARTON_M,...,3167100,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,12668400,1.148
61795,61795,8666,2023-11-22,873049102,450,315,20,0.307,2,CARTON_M,...,2835000,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,5670000,0.614
61796,61796,9502,2023-11-22,873049049,450,329,25,0.280,3,CARTON_M,...,3701250,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,11103750,0.840
61797,61797,10907,2023-11-22,873049057,450,326,25,0.273,1,CARTON_M,...,3667500,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,3667500,0.273
62230,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,3156208,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,9468624,0.780

#### 2.2.3.1- Entrada de dados no modelo

In [106]:
# Adicionar uma coluna para identificar cada item dentro de cada chave_loja_buffer_onda
df_process_situacao3['item_loja'] = df_process_situacao3.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Peso_unit'

df_matriz_peso = df_process_situacao3.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_peso.columns.name = None

df_matriz_peso

     item_loja  14_EN_4  24_EN_3  34_EN_4  48_EN_3
0            1    0.160    0.283    0.260    0.220
1            2    0.170    0.263    0.300    0.207
2            3    0.330    0.247    0.180    0.180
3            4    0.307    0.237    0.253    0.170
4            5    0.213    0.267    0.253    0.190
..         ...      ...      ...      ...      ...
147        148    0.000    0.520    0.000    0.000
148        149    0.000    0.500    0.000    0.000
149        150    0.000    0.500    0.000    0.000
150        151    0.000    0.480    0.000    0.000
151        152    0.000    0.540    0.000    0.000

[152 rows x 5 columns]

In [107]:
# Variável avaliada:
variavel_ik = 'Volume_unit'

df_matriz_volume = df_process_situacao3.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_volume.columns.name = None

df_matriz_volume

     item_loja    14_EN_4    24_EN_3    34_EN_4    48_EN_3
0            1  2797520.0  4527320.0  3576430.0  3001320.0
1            2  2507560.0  4299396.0  3907240.0  3228148.0
2            3  4999365.0  4440546.0  2641720.0  2545893.0
3            4  2902500.0  4161200.0  3449628.0  2411200.0
4            5  2984040.0  3923348.0  3449628.0  2504656.0
..         ...        ...        ...        ...        ...
147        148        0.0  8646506.0        0.0        0.0
148        149        0.0  6992979.0        0.0        0.0
149        150        0.0  7533036.0        0.0        0.0
150        151        0.0  9380525.0        0.0        0.0
151        152        0.0  8173550.0        0.0        0.0

[152 rows x 5 columns]

In [108]:
# Adicionar uma coluna para identificar cada item dentro de cada loja
df_process_situacao3['item_loja'] = df_process_situacao3.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Inner'

df_matriz_inner = df_process_situacao3.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_inner.columns.name = None

df_matriz_inner

     item_loja  14_EN_4  24_EN_3  34_EN_4  48_EN_3
0            1      1.0      1.0      1.0      1.0
1            2      1.0      1.0      1.0      1.0
2            3      1.0      1.0      1.0      1.0
3            4      1.0      1.0      1.0      1.0
4            5      1.0      1.0      1.0      1.0
..         ...      ...      ...      ...      ...
147        148      0.0      1.0      0.0      0.0
148        149      0.0      1.0      0.0      0.0
149        150      0.0      1.0      0.0      0.0
150        151      0.0      1.0      0.0      0.0
151        152      0.0      1.0      0.0      0.0

[152 rows x 5 columns]

In [109]:
# Adicionar uma coluna para identificar cada item dentro de cada loja
df_process_situacao3['item_loja'] = df_process_situacao3.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Peças'

df_matriz_pecas = df_process_situacao3.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_pecas.columns.name = None

df_matriz_pecas

     item_loja  14_EN_4  24_EN_3  34_EN_4  48_EN_3
0            1      1.0      3.0      1.0      1.0
1            2      1.0      3.0      1.0      1.0
2            3      1.0      2.0      1.0      1.0
3            4      2.0      3.0      2.0      2.0
4            5      1.0      3.0      1.0      7.0
..         ...      ...      ...      ...      ...
147        148      0.0      2.0      0.0      0.0
148        149      0.0      3.0      0.0      0.0
149        150      0.0      2.0      0.0      0.0
150        151      0.0      1.0      0.0      0.0
151        152      0.0      3.0      0.0      0.0

[152 rows x 5 columns]

Capacidade da caixa como variável

In [110]:
# Variável avaliada:
variavel_ik = 'Peças_max'

df_matriz_caixa_capacidade_pecas = df_process_situacao3.pivot_table(index='chave_loja_buffer_onda',  values= variavel_ik, fill_value=0).reset_index()

df_matriz_caixa_capacidade_pecas.columns.name = None

df_matriz_caixa_capacidade_pecas

  chave_loja_buffer_onda  Peças_max
0                14_EN_4      512.0
1                24_EN_3      512.0
2                34_EN_4      512.0
3                48_EN_3      512.0

In [111]:
# Variável avaliada:
variavel_ik = 'volume_util_padrao'

df_matriz_caixa_capacidade_volume = df_process_situacao3.pivot_table(index='chave_loja_buffer_onda',  values= variavel_ik, fill_value=0).reset_index()

df_matriz_caixa_capacidade_volume.columns.name = None

df_matriz_caixa_capacidade_volume

  chave_loja_buffer_onda  volume_util_padrao
0                14_EN_4          75538008.0
1                24_EN_3          75538008.0
2                34_EN_4          75538008.0
3                48_EN_3          75538008.0

In [112]:
peso =  df_matriz_peso
pecas = df_matriz_pecas  #demanda
volume = df_matriz_volume
inner = df_matriz_inner

In [113]:
cp = 23
cv = df_matriz_caixa_capacidade_volume
np = df_matriz_caixa_capacidade_pecas

#### Parâmetros

In [114]:
ampl.param["n"] = len(pecas)   # tamanho da loja que tem mais itens

ampl.param["cp"] = cp
ampl.param["r"] = len(volume.columns) -1

cv_ = cv.drop(columns='chave_loja_buffer_onda')
np_ = np.drop(columns='chave_loja_buffer_onda')

v = volume.drop(columns='item_loja')
w = peso.drop(columns='item_loja')
d= pecas.drop(columns='item_loja')
inner_ = inner.drop(columns='item_loja')

ampl.param["w"] = {(i, k): w.iloc[i - 1][k - 1] for i in range(1, len(w)+1) for k in range(1, len(w.columns)+1)}
ampl.param["v"] = {(i, k): v.iloc[i - 1][k - 1] for i in range(1, len(v)+1) for k in range(1, len(v.columns)+1)}
ampl.param["d"] = {(i, k): d.iloc[i - 1][k - 1] for i in range(1, len(d)+1) for k in range(1, len(d.columns)+1)}
ampl.param["inner"] = {(i, k): inner_.iloc[i - 1][k - 1] for i in range(1, len(inner_)+1) for k in range(1, len(inner_.columns)+1)}

ampl.param["cv"] = {(k): cv_.iloc[k - 1] for k in range(1, len(cv_) + 1)}
ampl.param["np"] = {(k): np_.iloc[k - 1] for k in range(1, len(np_)+1)}

#### 2.2.3.2- Solvers

In [115]:
ampl.option["solver"] = "highs"
ampl.option["highs_options"] = "outlev=1 timelimit=600"
ampl.solve()

HiGHS 1.7.0:   tech:outlev = 1
  lim:time = 600
Running HiGHS 1.7.0 (git hash: 50670fd): Copyright (c) 2024 HiGHS under MIT licence terms
Coefficient ranges:
  Matrix [7e-02, 8e+07]
  Cost   [1e+00, 1e+00]
  Bound  [4e-16, 2e+01]
  RHS    [1e+00, 2e+01]
Presolving model
Presolve: Infeasible

Solving report
  Status            Infeasible
  Primal bound      inf
  Dual bound        -inf
  Gap               inf
  Solution status   -
  Timing            0.02 (total)
                    0.01 (presolve)
                    0.00 (postsolve)
  Nodes             0
  LP iterations     0 (total)
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
Coefficient ranges:
  Matrix [7e-02, 8e+07]
  Cost   [1e+00, 1e+00]
  Bound  [1e+00, 2e+01]
  RHS    [1e+00, 2e+01]
Presolving model
1262 rows, 32760 cols, 130800 nonzeros  0s
1262 rows, 32760 cols, 130800 nonzeros  0s
Objective function is integral with scale 1

Solving MIP model with:
   1262 rows
   32760 cols (11100 binary, 21660 integer, 0 implied int., 0 continuous)
   130800 nonzeros

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   0               inf                  inf        0      0      0         0     0.3s
 R       0       0         0   0.00%   94.73585092     135               29.83%        0      0      0      5501     0.9s
 C       0       0         0   0.00%   94.73585092     134               29.30%      527    133      0      5939     1.3s
 L       0       0         0   0.00%   95.05255182     96                 0.99%     1799    444      0      7228     6.3s

Solving report
  Status            Optimal
  Primal bound      96
  Dual bound        96
  Gap               0% (tolerance: 0.01%)
  Solution status   feasible
                    96 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            6.31 (total)
                    0.29 (presolve)
                    0.00 (postsolve)
  Nodes             1
  LP iterations     9764 (total)
                    0 (strong br.)
                    1727 (separation)
                    2536 (heuristics)
HiGHS 1.7.0: optimal solution; objective 96
9764 simplex iterations
1 branching nodes

In [116]:
e_s3_highs = ampl.getVariable('e').getValues().toPandas()
e_s3_highs = e_s3_highs.reset_index()
e_s3_highs.columns = ['item_loja','caixa', 'chave_loja_buffer_onda', 'valor_multiplo']
e_s3_highs = e_s3_highs.query('valor_multiplo >0')
e_s3_highs#.head(20)

       item_loja  caixa  chave_loja_buffer_onda  valor_multiplo
23             1      6                       4               1
49             1     13                       2               3
84             1     22                       1               1
102            1     26                       3               1
283            2     11                       4               1
...          ...    ...                     ...             ...
35689        149     43                       2               3
35909        150     38                       2               1
35961        150     51                       2               1
36145        151     37                       2               1
36405        152     42                       2               3

[715 rows x 4 columns]

In [117]:
y_s3_highs = ampl.getVariable('y').getValues().toPandas()
y_s3_highs = y_s3_highs.reset_index()
y_s3_highs.columns = ['Caixa','chave_loja_buffer_onda', 'selecao']
y_s3_highs = y_s3_highs.query('selecao>0')

df_caixas_por_loja_highs_s3 = y_s3_highs.pivot_table(index='Caixa', columns='chave_loja_buffer_onda', values='selecao', fill_value=0)
df_caixas_por_loja_highs_s3 = df_caixas_por_loja_highs_s3.reset_index()
df_caixas_por_loja_highs_s3.columns.name = None
df_caixas_por_loja_highs_s3 # as colunas são as lojas

    Caixa    1    2    3    4
0       1  0.0  1.0  1.0  1.0
1       2  0.0  1.0  1.0  0.0
2       3  1.0  0.0  1.0  1.0
3       4  0.0  1.0  1.0  0.0
4       5  0.0  0.0  1.0  0.0
5       6  0.0  0.0  1.0  1.0
6       8  0.0  1.0  0.0  0.0
7      10  0.0  1.0  0.0  1.0
8      11  1.0  0.0  0.0  1.0
9      12  1.0  0.0  0.0  0.0
10     13  1.0  1.0  1.0  0.0
11     14  0.0  1.0  1.0  0.0
12     15  1.0  0.0  0.0  0.0
13     16  1.0  0.0  1.0  1.0
14     17  1.0  1.0  0.0  0.0
15     18  1.0  1.0  0.0  0.0
16     19  1.0  0.0  0.0  0.0
17     20  0.0  1.0  0.0  0.0
18     21  1.0  0.0  0.0  0.0
19     22  1.0  0.0  0.0  0.0
20     23  1.0  0.0  0.0  1.0
21     24  1.0  0.0  1.0  0.0
22     25  1.0  0.0  1.0  0.0
23     26  1.0  0.0  1.0  0.0
24     28  1.0  0.0  1.0  1.0
25     29  0.0  1.0  1.0  0.0
26     31  0.0  0.0  0.0  1.0
27     32  0.0  0.0  1.0  0.0
28     33  0.0  0.0  0.0  1.0
29     34  1.0  0.0  1.0  0.0
30     35  1.0  1.0  1.0  1.0
31     36  1.0  0.0  1.0  1.0
32     37  1.0  1.0  0.0  0.0
33     38  0.0  1.0  1.0  0.0
34     39  0.0  1.0  0.0  0.0
35     40  1.0  1.0  1.0  0.0
36     41  0.0  1.0  1.0  1.0
37     42  1.0  1.0  0.0  0.0
38     43  0.0  1.0  0.0  0.0
39     44  0.0  0.0  0.0  1.0
40     46  0.0  0.0  1.0  0.0
41     49  0.0  1.0  1.0  0.0
42     50  1.0  1.0  1.0  0.0
43     51  0.0  1.0  1.0  0.0
44     52  1.0  0.0  1.0  0.0
45     54  1.0  1.0  0.0  1.0
46     56  1.0  0.0  0.0  1.0
47     57  0.0  0.0  1.0  0.0
48     58  0.0  0.0  1.0  0.0
49     59  0.0  0.0  1.0  1.0
50     60  0.0  0.0  1.0  0.0

In [118]:
df_caixas_por_loja_highs_s3.columns = (['caixas'] + list(w.columns)) # os número das colunas são os nomes das lojas
df_caixas_por_loja_highs_s3

    caixas  14_EN_4  24_EN_3  34_EN_4  48_EN_3
0        1      0.0      1.0      1.0      1.0
1        2      0.0      1.0      1.0      0.0
2        3      1.0      0.0      1.0      1.0
3        4      0.0      1.0      1.0      0.0
4        5      0.0      0.0      1.0      0.0
5        6      0.0      0.0      1.0      1.0
6        8      0.0      1.0      0.0      0.0
7       10      0.0      1.0      0.0      1.0
8       11      1.0      0.0      0.0      1.0
9       12      1.0      0.0      0.0      0.0
10      13      1.0      1.0      1.0      0.0
11      14      0.0      1.0      1.0      0.0
12      15      1.0      0.0      0.0      0.0
13      16      1.0      0.0      1.0      1.0
14      17      1.0      1.0      0.0      0.0
15      18      1.0      1.0      0.0      0.0
16      19      1.0      0.0      0.0      0.0
17      20      0.0      1.0      0.0      0.0
18      21      1.0      0.0      0.0      0.0
19      22      1.0      0.0      0.0      0.0
20      23      1.0      0.0      0.0      1.0
21      24      1.0      0.0      1.0      0.0
22      25      1.0      0.0      1.0      0.0
23      26      1.0      0.0      1.0      0.0
24      28      1.0      0.0      1.0      1.0
25      29      0.0      1.0      1.0      0.0
26      31      0.0      0.0      0.0      1.0
27      32      0.0      0.0      1.0      0.0
28      33      0.0      0.0      0.0      1.0
29      34      1.0      0.0      1.0      0.0
30      35      1.0      1.0      1.0      1.0
31      36      1.0      0.0      1.0      1.0
32      37      1.0      1.0      0.0      0.0
33      38      0.0      1.0      1.0      0.0
34      39      0.0      1.0      0.0      0.0
35      40      1.0      1.0      1.0      0.0
36      41      0.0      1.0      1.0      1.0
37      42      1.0      1.0      0.0      0.0
38      43      0.0      1.0      0.0      0.0
39      44      0.0      0.0      0.0      1.0
40      46      0.0      0.0      1.0      0.0
41      49      0.0      1.0      1.0      0.0
42      50      1.0      1.0      1.0      0.0
43      51      0.0      1.0      1.0      0.0
44      52      1.0      0.0      1.0      0.0
45      54      1.0      1.0      0.0      1.0
46      56      1.0      0.0      0.0      1.0
47      57      0.0      0.0      1.0      0.0
48      58      0.0      0.0      1.0      0.0
49      59      0.0      0.0      1.0      1.0
50      60      0.0      0.0      1.0      0.0

#### Caixas

In [119]:
print('Solver Highs')
total_caixas = 0
for col in w.columns:
    print(f'número de caixas para a chave_loja_buffer_onda "{col}": {df_caixas_por_loja_highs_s3[col].sum()}')
    total_caixas += df_caixas_por_loja_highs_s3[col].sum()
print(f'\ntotal de caixas: {total_caixas}')

Solver Highs
número de caixas para a chave_loja_buffer_onda "14_EN_4": 26.0
número de caixas para a chave_loja_buffer_onda "24_EN_3": 23.0
número de caixas para a chave_loja_buffer_onda "34_EN_4": 30.0
número de caixas para a chave_loja_buffer_onda "48_EN_3": 17.0

total de caixas: 96.0

### 2.2.4- Situação 4

In [63]:
df_process_situacao4 = df_ffd_s4

df_process_situacao4

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Volume_unit,tempo_espera_dias,prioridade,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max,Volume_total,Peso_total
515,515,1490,2023-11-03,542140454,300,237,32,0.230,3,CARTON_M,...,2275200,19,78,27778950.0,83393894.4,75538008.0,83393894.4,170,6825600,0.690
516,516,1053,2023-11-03,542140454,300,237,32,0.230,2,CARTON_M,...,2275200,19,78,27778950.0,83393894.4,75538008.0,83393894.4,170,4550400,0.460
517,517,1490,2023-11-03,542140446,422,216,23,0.187,3,CARTON_M,...,2096496,19,78,27778950.0,83393894.4,75538008.0,83393894.4,170,6289488,0.561
518,518,1490,2023-11-03,542140462,300,295,19,0.153,1,CARTON_M,...,1681500,19,78,27778950.0,83393894.4,75538008.0,83393894.4,170,1681500,0.153
519,519,1053,2023-11-03,542140462,300,295,19,0.153,1,CARTON_M,...,1681500,19,78,27778950.0,83393894.4,75538008.0,83393894.4,170,1681500,0.153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60096,60096,15,2023-11-22,881488746,491,301,17,0.210,20,CARTON_M,...,2512447,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,50248940,4.200
60097,60097,207,2023-11-22,881488762,454,316,22,0.260,6,CARTON_M,...,3156208,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,18937248,1.560
60098,60098,4833,2023-11-22,881488720,481,294,18,0.240,7,CARTON_M,...,2545452,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,17818164,1.680
60099,60099,6014,2023-11-22,881488738,477,289,19,0.220,18,CARTON_M,...,2619207,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,47145726,3.960
60100,60100,7219,2023-11-22,881488754,473,281,20,0.210,7,CARTON_M,...,2658260,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,18607820,1.470

#### 2.2.4.1- Entrada de dados no modelo

In [64]:
# Adicionar uma coluna para identificar cada item dentro de cada chave_loja_buffer_onda
df_process_situacao4['item_loja'] = df_process_situacao4.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Peso_unit'

df_matriz_peso = df_process_situacao4.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_peso.columns.name = None

df_matriz_peso

     item_loja  11_EN_3  17_CX_9  21_EN_3  30_EN_3  44_CX_4  62_EN_4  73_EN_4
0            1    0.220    0.230    0.200    0.240     0.78     0.30    0.360
1            2    0.207    0.230    0.247    0.213     0.52     0.28    0.325
2            3    0.140    0.187    0.207    0.164     0.32     0.28    0.360
3            4    0.167    0.153    0.167    0.156     0.29     0.66    0.300
4            5    0.240    0.153    0.167    0.185     0.49     0.57    0.280
..         ...      ...      ...      ...      ...      ...      ...      ...
164        165    0.000    0.000    0.500    0.000     0.00     0.00    0.000
165        166    0.000    0.000    0.460    0.000     0.00     0.00    0.000
166        167    0.000    0.000    0.440    0.000     0.00     0.00    0.000
167        168    0.000    0.000    0.410    0.000     0.00     0.00    0.000
168        169    0.000    0.000    0.380    0.000     0.00     0.00    0.000

[169 rows x 8 columns]

In [65]:
# Variável avaliada:
variavel_ik = 'Volume_unit'

df_matriz_volume = df_process_situacao4.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_volume.columns.name = None

df_matriz_volume

,item_loja,11_EN_3,17_CX_9,21_EN_3,30_EN_3,44_CX_4,62_EN_4,73_EN_4
0,1,3001320.0,2275200.0,1633230.0,2864650.0,6219275.0,4237839.0,3129385.0
1,2,3228148.0,2275200.0,3332070.0,2456160.0,6976800.0,3243240.0,3448182.0
2,3,2414425.0,2096496.0,3228148.0,1207720.0,5422560.0,4013658.0,3038868.0
3,4,2741220.0,1681500.0,2741220.0,1212300.0,4697784.0,2888550.0,4237839.0
4,5,2864650.0,1681500.0,2741220.0,2637180.0,3432780.0,2781900.0,3243240.0
...,...,...,...,...,...,...,...,...
164,165,0.0,0.0,5348480.0,0.0,0.0,0.0,0.0
165,166,0.0,0.0,4516050.0,0.0,0.0,0.0,0.0
166,167,0.0,0.0,4362732.0,0.0,0.0,0.0,0.0
167,168,0.0,0.0,4469256.0,0.0,0.0,0.0,0.0
168,169,0.0,0.0,4844169.0,0.0,0.0,0.0,0.0

In [66]:
# Adicionar uma coluna para identificar cada item dentro de cada loja
df_process_situacao4['item_loja'] = df_process_situacao4.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Inner'

df_matriz_inner = df_process_situacao4.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_inner.columns.name = None

df_matriz_inner

     item_loja  11_EN_3  17_CX_9  21_EN_3  30_EN_3  44_CX_4  62_EN_4  73_EN_4
0            1      1.0      1.0      1.0      1.0      1.0      1.0      1.0
1            2      1.0      1.0      1.0      1.0      1.0      1.0      1.0
2            3      1.0      1.0      1.0      1.0      1.0      1.0      1.0
3            4      1.0      1.0      1.0      1.0      1.0      1.0      1.0
4            5      1.0      1.0      1.0      1.0      1.0      1.0      1.0
..         ...      ...      ...      ...      ...      ...      ...      ...
164        165      0.0      0.0      1.0      0.0      0.0      0.0      0.0
165        166      0.0      0.0      1.0      0.0      0.0      0.0      0.0
166        167      0.0      0.0      1.0      0.0      0.0      0.0      0.0
167        168      0.0      0.0      1.0      0.0      0.0      0.0      0.0
168        169      0.0      0.0      1.0      0.0      0.0      0.0      0.0

[169 rows x 8 columns]

In [67]:
# Adicionar uma coluna para identificar cada item dentro de cada loja
df_process_situacao4['item_loja'] = df_process_situacao4.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Peças'

df_matriz_pecas = df_process_situacao4.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_pecas.columns.name = None

df_matriz_pecas

     item_loja  11_EN_3  17_CX_9  21_EN_3  30_EN_3  44_CX_4  62_EN_4  73_EN_4
0            1      1.0      3.0      1.0      1.0      1.0      2.0      5.0
1            2      1.0      2.0      1.0      1.0      1.0      1.0      3.0
2            3      1.0      3.0      1.0      1.0      2.0      1.0      9.0
3            4      2.0      1.0      1.0      1.0      1.0      2.0      2.0
4            5      1.0      1.0      3.0      3.0      1.0      2.0      3.0
..         ...      ...      ...      ...      ...      ...      ...      ...
164        165      0.0      0.0      1.0      0.0      0.0      0.0      0.0
165        166      0.0      0.0      2.0      0.0      0.0      0.0      0.0
166        167      0.0      0.0      5.0      0.0      0.0      0.0      0.0
167        168      0.0      0.0      2.0      0.0      0.0      0.0      0.0
168        169      0.0      0.0      1.0      0.0      0.0      0.0      0.0

[169 rows x 8 columns]

Capacidade da caixa como variável

In [68]:
# Variável avaliada:
variavel_ik = 'Peças_max'

df_matriz_caixa_capacidade_pecas = df_process_situacao4.pivot_table(index='chave_loja_buffer_onda',  values= variavel_ik, fill_value=0).reset_index()

df_matriz_caixa_capacidade_pecas.columns.name = None

df_matriz_caixa_capacidade_pecas

  chave_loja_buffer_onda  Peças_max
0                11_EN_3      512.0
1                17_CX_9      170.0
2                21_EN_3      512.0
3                30_EN_3      512.0
4                44_CX_4      170.0
5                62_EN_4      512.0
6                73_EN_4      512.0

In [69]:
# Variável avaliada:
variavel_ik = 'volume_util_padrao'

df_matriz_caixa_capacidade_volume = df_process_situacao4.pivot_table(index='chave_loja_buffer_onda',  values= variavel_ik, fill_value=0).reset_index()

df_matriz_caixa_capacidade_volume.columns.name = None

df_matriz_caixa_capacidade_volume

  chave_loja_buffer_onda  volume_util_padrao
0                11_EN_3          75538008.0
1                17_CX_9          83393894.4
2                21_EN_3          75538008.0
3                30_EN_3          75538008.0
4                44_CX_4          83393894.4
5                62_EN_4          75538008.0
6                73_EN_4          75538008.0

In [70]:
peso =  df_matriz_peso
pecas = df_matriz_pecas  #demanda
volume = df_matriz_volume
inner = df_matriz_inner

In [71]:
cp = 23
cv = df_matriz_caixa_capacidade_volume
np = df_matriz_caixa_capacidade_pecas

#### Parâmetros

In [72]:
ampl.param["n"] = len(pecas)   # tamanho da loja que tem mais itens

ampl.param["cp"] = cp
ampl.param["r"] = len(volume.columns) -1

cv_ = cv.drop(columns='chave_loja_buffer_onda')
np_ = np.drop(columns='chave_loja_buffer_onda')

v = volume.drop(columns='item_loja')
w = peso.drop(columns='item_loja')
d= pecas.drop(columns='item_loja')
inner_ = inner.drop(columns='item_loja')

ampl.param["w"] = {(i, k): w.iloc[i - 1][k - 1] for i in range(1, len(w)+1) for k in range(1, len(w.columns)+1)}
ampl.param["v"] = {(i, k): v.iloc[i - 1][k - 1] for i in range(1, len(v)+1) for k in range(1, len(v.columns)+1)}
ampl.param["d"] = {(i, k): d.iloc[i - 1][k - 1] for i in range(1, len(d)+1) for k in range(1, len(d.columns)+1)}
ampl.param["inner"] = {(i, k): inner_.iloc[i - 1][k - 1] for i in range(1, len(inner_)+1) for k in range(1, len(inner_.columns)+1)}

ampl.param["cv"] = {(k): cv_.iloc[k - 1] for k in range(1, len(cv_) + 1)}
ampl.param["np"] = {(k): np_.iloc[k - 1] for k in range(1, len(np_)+1)}

#### 2.2.4.2- Solvers

In [73]:
ampl.option["solver"] = "highs"
ampl.option["highs_options"] = "outlev=1"  # timelimit=900
ampl.solve()

HiGHS 1.7.0:   tech:outlev = 1
Running HiGHS 1.7.0 (git hash: 50670fd): Copyright (c) 2024 HiGHS under MIT licence terms
Coefficient ranges:
  Matrix [5e-02, 8e+07]
  Cost   [1e+00, 1e+00]
  Bound  [1e+00, 2e+01]
  RHS    [1e+00, 2e+01]
Presolving model
3429 rows, 111503 cols, 445179 nonzeros  0s
3429 rows, 111503 cols, 445179 nonzeros  2s
Objective function is integral with scale 1

Solving MIP model with:
   3429 rows
   111503 cols (38437 binary, 73066 integer, 0 implied int., 0 continuous)
   445179 nonzeros

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   0               inf                  inf        0      0      0         0     2.6s
 R       0       0         0   0.00%   160.9262693     257               37.38%        0      0      0     15132     7.3s
 C       0       0         0   0.00%   160.9262693     256               37.14%     1266    304      0     16470     8.8s
         0       0         0   0.00%   160.9262693     256               37.14%     3159   1084      0     18658    13.9s
 L       0       0         0   0.00%   160.9262693     167                3.64%     3159   1084      0     18658    31.9s

Symmetry detection completed in 29.3s
Found 568 generators and 4 full orbitope(s) acting on 1071 columns

 L       0       0         0   0.00%   160.9262693     166                3.06%     3159    545      0     27678    57.0s
 B       3       0         1  25.00%   160.9262693     165                2.47%     3159    545      6     41724   148.0s
      1706    1290         1  25.10%   160.9262693     165                2.47%     3160    545     11     62692   177.4s
      1950    1532         2  25.10%   160.9262693     165                2.47%     3445    707     15     71401   194.5s
      2960    2538         4  25.10%   160.9262693     165                2.47%     3706    834     59     85267   278.5s
      3713    3285         7  25.10%   160.9262693     165                2.47%     3960    492    114     96718   352.1s
      4855    4421        10  25.10%   160.9262693     165                2.47%     4098    598    166    107088   463.9s
      5339    4889        18  25.10%   160.9262693     165                2.47%     4238    731    179    113946   508.7s
      6005    5549        21  25.10%   160.9262693     165                2.47%     4436    861    209    122559   580.8s
      6747    6289        22  25.10%   160.9262693     165                2.47%     4639    997    213    132675   768.1s
      7278    6818        23  25.10%   160.9262693     165                2.47%     4824    426    214    141128   840.1s
      7872    7410        24  25.10%   160.9262693     165                2.47%     5017    524    215    151057  1637.5s
      8512    8048        25  25.10%   160.9262693     165                2.47%     5193    624    224    160310  1779.9s

Restarting search from the root node
Model after restart has 3429 rows, 111503 cols (38437 bin., 73066 int., 0 impl., 0 cont.), and 445179 nonzeros

      8512       0         0   0.00%   160.9262693     165                2.47%      624      0      0    160310  6139.0s
      8512       0         0   0.00%   160.9262693     165                2.47%      624     65      3    160733  6140.3s

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

      8512       0         0   0.00%   160.9262693     165                2.47%     2020    416      3    162285  6145.6s
      8512       0         0   0.00%   160.9262693     165                2.47%     3097    842      3    163743  6150.7s

Symmetry detection completed in 45.6s
Found 568 generators and 4 full orbitope(s) acting on 1071 columns

      8512       1         0   0.00%   160.9262693     165                2.47%     3372    571      3    164018  6184.7s
      8579       2         1   0.00%   160.9262693     165                2.47%     3373    571      4    166097  6191.9s
      9718    1199         3  50.00%   160.9262693     165                2.47%     3373    571     46    181062  6306.7s
     10840    2312         7  50.00%   160.9262693     165                2.47%     3525    626     55    196395  8169.5s
     10911    2339        25  50.00%   160.9262693     165                2.47%     3663    681     73    196968  8174.5s
     12088    3500        37  50.00%   160.9262693     165                2.47%     3767    720    109    213004  8330.3s
     12113    3500        39  50.00%   160.9262693     165                2.47%     3873    760    111    213764 12313.6s
     13052    4448        45  50.00%   160.9262693     165                2.47%     3874    760    126    225737 12483.3s
     13095    4451        49  50.00%   160.9262693     165                2.47%     3999    537    130    226774 12488.6s
     13582    4953        57  50.00%   160.9262693     165                2.47%     4000    537    141    234451 14899.8s
     14686    6050        60  50.00%   160.9262693     165                2.47%     3704    599    144    248492 15075.7s
     14798    6152        65  50.00%   160.9262693     165                2.47%     3672    620    155    251716 15090.6s
     14860    6153        70  50.00%   160.9262693     165                2.47%     3623    639    162    253611 15098.0s
     14923    6265        71  50.00%   160.9262693     165                2.47%     3624    639    168    256182 15108.2s
     15653    6987        75  50.00%   160.9262693     165                2.47%     3569    493    183    266580 15239.5s
     16452    7776        80  50.00%   160.9262693     165                2.47%     3591    504    194    277798 15379.5s
     16473    7776        84  70.31%   160.9262693     165                2.47%     3734    578    206    289617 15385.5s
     17264    8577        85  70.31%   160.9262693     165                2.47%     3735    578    212    299570 20161.4s

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

     18086    9391        89  70.31%   160.9262693     165                2.47%     3877    660    221    313874 20395.2s
     18776   10075        92  70.31%   160.9262693     165                2.47%     4019    434    283    325508 20617.0s
     18929   10221        95  70.31%   160.9262693     165                2.47%     4082    484    288    330471 20652.8s
     19824   11104       101  70.31%   160.9262693     165                2.47%     4008    527    314    342129 20911.5s
     19853   11105       106  70.31%   160.9262693     165                2.47%     3988    573    343    345049 20917.2s
     19980   11247       107  70.31%   160.9262693     165                2.47%     3989    573    349    349078 20950.3s
     20001   11246       113  70.31%   160.9262693     165                2.47%     3946    608    376    351671 20955.6s
     20046   11248       115  70.31%   160.9262693     165                2.47%     3947    608    378    352659 20962.8s
     20565   11809       117  70.31%   160.9262693     165                2.47%     3947    608    380    360164 21108.0s
     20592   11810       124  70.31%   160.9262693     165                2.47%     3950    461    422    362647 21113.6s
     21435   12661       126  70.31%   160.9262693     165                2.47%     3951    461    433    371348 21344.4s
     21487   12661       130  70.31%   160.9262693     165                2.47%     4000    492    457    373966 21352.4s
     21928   13138       133  70.31%   160.9262693     165                2.47%     4002    492    477    381090 24350.2s
     21985   13138       137  70.31%   160.9262693     165                2.47%     4011    523    488    384460 24365.5s
bad allocation

In [74]:
e_s4_highs = ampl.getVariable('e').getValues().toPandas()
e_s4_highs = e_s4_highs.reset_index()
e_s4_highs.columns = ['item_loja','caixa', 'chave_loja_buffer_onda', 'valor_multiplo']
e_s4_highs = e_s4_highs.query('valor_multiplo >0')
e_s4_highs#.head(20)

Empty DataFrame
Columns: [item_loja, caixa, chave_loja_buffer_onda, valor_multiplo]
Index: []

In [75]:
y_s4_highs = ampl.getVariable('y').getValues().toPandas()
y_s4_highs = y_s4_highs.reset_index()
y_s4_highs.columns = ['Caixa','chave_loja_buffer_onda', 'selecao']
y_s4_highs = y_s4_highs.query('selecao>0')

df_caixas_por_loja_highs_s4 = y_s4_highs.pivot_table(index='Caixa', columns='chave_loja_buffer_onda', values='selecao', fill_value=0)
df_caixas_por_loja_highs_s4 = df_caixas_por_loja_highs_s4.reset_index()
df_caixas_por_loja_highs_s4.columns.name = None
df_caixas_por_loja_highs_s4 # as colunas são as lojas

Empty DataFrame
Columns: [Caixa]
Index: []

In [76]:
df_caixas_por_loja_highs_s4.columns = (['caixas'] + list(w.columns)) # os número das colunas são os nomes das lojas
df_caixas_por_loja_highs_s4

ValueError: Length mismatch: Expected axis has 1 elements, new values have 8 elements

#### Caixas

In [ ]:
print('Solver Highs')
total_caixas = 0
for col in w.columns:
    print(f'número de caixas para a chave_loja_buffer_onda "{col}": {df_caixas_por_loja_highs_s4[col].sum()}')
    total_caixas += df_caixas_por_loja_highs_s4[col].sum()
print(f'\ntotal de caixas: {total_caixas}')

Solver Highs
número de caixas para a chave_loja_buffer_onda "11_EN_3": 17.0
número de caixas para a chave_loja_buffer_onda "17_CX_9": 14.0
número de caixas para a chave_loja_buffer_onda "21_EN_3": 21.0
número de caixas para a chave_loja_buffer_onda "30_EN_3": 25.0
número de caixas para a chave_loja_buffer_onda "44_CX_4": 17.0
número de caixas para a chave_loja_buffer_onda "62_EN_4": 33.0
número de caixas para a chave_loja_buffer_onda "73_EN_4": 38.0

total de caixas: 165.0

In [ ]:
f

### 2.2.5- Situação 5

In [ ]:
df_process_situacao5 = df_ffd_s5

df_process_situacao5

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Volume_unit,tempo_espera_dias,prioridade,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max,Volume_total,Peso_total
204,204,1306,2023-10-31,585574931,450,300,24,0.880,4,CARTON_M,...,3240000,22,78,27778950.0,83393894.4,75538008.0,83393894.4,170,12960000,3.520
205,205,1487,2023-10-31,585574893,450,300,40,0.780,1,CARTON_M,...,5400000,22,78,27778950.0,83393894.4,75538008.0,83393894.4,170,5400000,0.780
206,206,1487,2023-10-31,585574906,450,300,25,0.820,1,CARTON_M,...,3375000,22,78,27778950.0,83393894.4,75538008.0,83393894.4,170,3375000,0.820
207,207,1306,2023-10-31,585574893,450,300,40,0.780,2,CARTON_M,...,5400000,22,78,27778950.0,83393894.4,75538008.0,83393894.4,170,10800000,1.560
208,208,1306,2023-10-31,585574906,450,300,25,0.820,1,CARTON_M,...,3375000,22,78,27778950.0,83393894.4,75538008.0,83393894.4,170,3375000,0.820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60700,60700,1157,2023-11-22,873049031,450,306,23,0.287,4,CARTON_M,...,3167100,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,12668400,1.148
60701,60701,5671,2023-11-22,873049065,450,279,23,0.260,2,CARTON_M,...,2887650,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,5775300,0.520
60702,60702,8666,2023-11-22,873049102,450,315,20,0.307,1,CARTON_M,...,2835000,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,2835000,0.307
60703,60703,9502,2023-11-22,873049049,450,329,25,0.280,4,CARTON_M,...,3701250,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,14805000,1.120
60704,60704,10907,2023-11-22,873049057,450,326,25,0.273,4,CARTON_M,...,3667500,0,78,27778950.0,83393894.4,75538008.0,75538008.0,512,14670000,1.092

#### 2.2.5.1- Entrada de dados no modelo

In [ ]:
# Adicionar uma coluna para identificar cada item dentro de cada chave_loja_buffer_onda
df_process_situacao5['item_loja'] = df_process_situacao5.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Peso_unit'

df_matriz_peso = df_process_situacao5.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_peso.columns.name = None

df_matriz_peso

     item_loja  13_EN_4  20_CX_4  31_CX_6  65_EN_4  9_CX_7
0            1    0.323     0.88    0.240    0.300    0.26
1            2    0.303     0.78    0.240    0.180    0.24
2            3    0.295     0.82    0.275    0.180    0.26
3            4    0.328     0.78    0.390    0.253    0.22
4            5    0.310     0.82    0.390    0.253    0.94
..         ...      ...      ...      ...      ...     ...
207        208    0.273     0.86    0.000    0.000    0.00
208        209    0.000     0.88    0.000    0.000    0.00
209        210    0.000     0.86    0.000    0.000    0.00
210        211    0.000     0.86    0.000    0.000    0.00
211        212    0.000     0.82    0.000    0.000    0.00

[212 rows x 6 columns]

In [ ]:
# Variável avaliada:
variavel_ik = 'Volume_unit'

df_matriz_volume = df_process_situacao5.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_volume.columns.name = None

df_matriz_volume

     item_loja    13_EN_4    20_CX_4    31_CX_6    65_EN_4     9_CX_7
0            1  3553770.0  3240000.0  1506720.0  3907240.0  2933673.0
1            2  3303008.0  5400000.0  1506720.0  2641720.0  2508520.0
2            3  3297150.0  3375000.0   246960.0  2641720.0  2885440.0
3            4  3583140.0  5400000.0  1634640.0  3449628.0  1996400.0
4            5  3428352.0  3375000.0  1634640.0  3449628.0  6997046.0
..         ...        ...        ...        ...        ...        ...
207        208  3667500.0  6095603.0        0.0        0.0        0.0
208        209        0.0  5888160.0        0.0        0.0        0.0
209        210        0.0  5136992.0        0.0        0.0        0.0
210        211        0.0  7524000.0        0.0        0.0        0.0
211        212        0.0  4902256.0        0.0        0.0        0.0

[212 rows x 6 columns]

In [ ]:
# Adicionar uma coluna para identificar cada item dentro de cada loja
df_process_situacao5['item_loja'] = df_process_situacao5.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Inner'

df_matriz_inner = df_process_situacao5.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_inner.columns.name = None

df_matriz_inner

     item_loja  13_EN_4  20_CX_4  31_CX_6  65_EN_4  9_CX_7
0            1      1.0      1.0      1.0      1.0     1.0
1            2      1.0      1.0      1.0      1.0     1.0
2            3      1.0      1.0      1.0      1.0     1.0
3            4      1.0      1.0      1.0      1.0     1.0
4            5      1.0      1.0      1.0      1.0     1.0
..         ...      ...      ...      ...      ...     ...
207        208      1.0      1.0      0.0      0.0     0.0
208        209      0.0      1.0      0.0      0.0     0.0
209        210      0.0      1.0      0.0      0.0     0.0
210        211      0.0      1.0      0.0      0.0     0.0
211        212      0.0      1.0      0.0      0.0     0.0

[212 rows x 6 columns]

In [ ]:
# Adicionar uma coluna para identificar cada item dentro de cada loja
df_process_situacao5['item_loja'] = df_process_situacao5.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Peças'

df_matriz_pecas = df_process_situacao5.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_pecas.columns.name = None

df_matriz_pecas

     item_loja  13_EN_4  20_CX_4  31_CX_6  65_EN_4  9_CX_7
0            1      2.0      4.0      2.0      1.0     3.0
1            2      2.0      1.0      1.0      1.0     6.0
2            3      1.0      1.0      1.0      2.0     8.0
3            4      1.0      2.0     14.0      2.0     2.0
4            5      2.0      1.0     20.0      3.0     2.0
..         ...      ...      ...      ...      ...     ...
207        208      4.0      2.0      0.0      0.0     0.0
208        209      0.0      1.0      0.0      0.0     0.0
209        210      0.0      1.0      0.0      0.0     0.0
210        211      0.0      2.0      0.0      0.0     0.0
211        212      0.0      2.0      0.0      0.0     0.0

[212 rows x 6 columns]

Capacidade da caixa como variável

In [ ]:
# Variável avaliada:
variavel_ik = 'Peças_max'

df_matriz_caixa_capacidade_pecas = df_process_situacao5.pivot_table(index='chave_loja_buffer_onda',  values= variavel_ik, fill_value=0).reset_index()

df_matriz_caixa_capacidade_pecas.columns.name = None

df_matriz_caixa_capacidade_pecas

  chave_loja_buffer_onda  Peças_max
0                13_EN_4      512.0
1                20_CX_4      170.0
2                31_CX_6      170.0
3                65_EN_4      512.0
4                 9_CX_7      170.0

In [ ]:
# Variável avaliada:
variavel_ik = 'volume_util_padrao'

df_matriz_caixa_capacidade_volume = df_process_situacao5.pivot_table(index='chave_loja_buffer_onda',  values= variavel_ik, fill_value=0).reset_index()

df_matriz_caixa_capacidade_volume.columns.name = None

df_matriz_caixa_capacidade_volume

  chave_loja_buffer_onda  volume_util_padrao
0                13_EN_4          75538008.0
1                20_CX_4          83393894.4
2                31_CX_6          83393894.4
3                65_EN_4          75538008.0
4                 9_CX_7          83393894.4

In [ ]:
peso =  df_matriz_peso
pecas = df_matriz_pecas  #demanda
volume = df_matriz_volume
inner = df_matriz_inner

In [ ]:
cp = 23
cv = df_matriz_caixa_capacidade_volume
np = df_matriz_caixa_capacidade_pecas

#### Parâmetros

In [ ]:
ampl.param["n"] = len(pecas)   # tamanho da loja que tem mais itens

ampl.param["cp"] = cp
ampl.param["r"] = len(volume.columns) -1

cv_ = cv.drop(columns='chave_loja_buffer_onda')
np_ = np.drop(columns='chave_loja_buffer_onda')

v = volume.drop(columns='item_loja')
w = peso.drop(columns='item_loja')
d= pecas.drop(columns='item_loja')
inner_ = inner.drop(columns='item_loja')

ampl.param["w"] = {(i, k): w.iloc[i - 1][k - 1] for i in range(1, len(w)+1) for k in range(1, len(w.columns)+1)}
ampl.param["v"] = {(i, k): v.iloc[i - 1][k - 1] for i in range(1, len(v)+1) for k in range(1, len(v.columns)+1)}
ampl.param["d"] = {(i, k): d.iloc[i - 1][k - 1] for i in range(1, len(d)+1) for k in range(1, len(d.columns)+1)}
ampl.param["inner"] = {(i, k): inner_.iloc[i - 1][k - 1] for i in range(1, len(inner_)+1) for k in range(1, len(inner_.columns)+1)}

ampl.param["cv"] = {(k): cv_.iloc[k - 1] for k in range(1, len(cv_) + 1)}
ampl.param["np"] = {(k): np_.iloc[k - 1] for k in range(1, len(np_)+1)}

#### 2.2.5.2- Solvers

In [ ]:
ampl.option["solver"] = "highs"
ampl.option["highs_options"] = "outlev=1 timelimit=600"
ampl.solve()

HiGHS 1.7.0:   tech:outlev = 1
  lim:time = 600
Running HiGHS 1.7.0 (git hash: 50670fd): Copyright (c) 2024 HiGHS under MIT licence terms
Coefficient ranges:
  Matrix [2e-02, 8e+07]
  Cost   [1e+00, 1e+00]
  Bound  [1e-17, 9e+00]
  RHS    [1e+00, 6e+01]
Presolving model
Presolve: Infeasible

Solving report
  Status            Infeasible
  Primal bound      inf
  Dual bound        -inf
  Gap               inf
  Solution status   -
  Timing            0.03 (total)
                    0.02 (presolve)
                    0.00 (postsolve)
  Nodes             0
  LP iterations     0 (total)
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
Coefficient ranges:
  Matrix [2e-02, 8e+07]
  Cost   [1e+00, 1e+00]
  Bound  [1e+00, 6e+01]
  RHS    [1e+00, 6e+01]
Presolving model
2501 rows, 89815 cols, 358685 nonzeros  0s
2501 rows, 89815 cols, 358685 nonzeros  0s
Objective function is integral with scale 1

Solving MIP model with:
   2501 rows
   89815 cols (38065 binary, 51750 integer, 0 implied int., 0 continuous)
   358685 nonzeros

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   0               inf                  inf        0      0      0         0     1.2s
 R       0       0         0   0.00%   114.029896      201               43.27%        0      0      0     11059     4.4s
         0       0         0   0.00%   114.029896      201               43.27%     2783    498    944     13722     9.4s
 L       0       0         0   0.00%   114.029896      120                4.98%     2935    523    944     13905    20.0s

Symmetry detection completed in 28.0s
Found 596 generators

         0       1         0   0.00%   114.029896      120                4.98%     2935    439    944     19582    29.2s
         2       0         1  50.00%   114.029896      120                4.98%     2935    439    945     34933    75.5s
      1234    1213        10  84.77%   114.029896      120                4.98%     2937    439    963     53562   139.9s
      1408    1367        19  84.77%   114.029896      120                4.98%     3124    465    979     59849   155.0s
      1429    1370        27  84.82%   114.029896      120                4.98%     3426    512   1000     66101   160.6s
      1559    1490        31  84.82%   114.029896      120                4.98%     3427    512   1005     71315   173.9s
      1672    1587        39  84.83%   114.029896      120                4.98%     3526    613   1024     77473   186.0s
      1709    1587        47  85.01%   114.029896      120                4.98%     3766    404   1048     83386   191.7s
      1781    1661        54  85.01%   114.029896      120                4.98%     3768    404   1070     89494   200.1s
      1864    1662        59  85.01%   114.029896      120                4.98%     3996    476   1081     97178   208.0s
      1881    1736        64  85.01%   114.029896      120                4.98%     4001    476   1109     98279   216.4s
      1912    1736        73  85.01%   114.029896      120                4.98%     4273    539   1125    107136   223.0s
 B    1970    1738        75  85.01%   114.029896      119                4.18%     4274    539   1131    108532   288.9s
      3060    2633        75  85.01%   114.029896      119                4.18%     4275    539   1144    120263   353.8s
      3091    2634        84  85.01%   114.029896      119                4.18%     4486    601   1160    129043   360.2s
 T    3091    2592        84  85.01%   114.029896      118                3.36%     4486    601   1297    129043   451.4s

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

      4344    3354        85  85.01%   114.029896      118                3.36%     4487    601   1302    144135   518.8s
      4366    3353        93  85.01%   114.029896      118                3.36%     4662    663   1320    150262   524.8s
      4424    3354        98  85.01%   114.029896      118                3.36%     4666    663   1354    152756   531.0s
      4493    3472        99  85.01%   114.029896      118                3.36%     4667    663   1358    154266   547.5s
      4514    3472       106  85.01%   114.029896      118                3.36%     4881    365   1370    159802   552.6s
      4663    3610       114  85.01%   114.029896      118                3.36%     4883    365   1380    165254   574.5s
      4681    3609       122  85.01%   114.029896      118                3.36%     5054    415   1392    169347   579.6s
      4821    3739       126  85.01%   114.029896      118                3.36%     5057    415   1405    175071   601.8s

Solving report
  Status            Time limit reached
  Primal bound      118
  Dual bound        115
  Gap               2.54% (tolerance: 0.01%)
  Solution status   feasible
                    118 (objective)
                    0 (bound viol.)
                    5.39568389968e-14 (int. viol.)
                    0 (row viol.)
  Timing            601.96 (total)
                    1.05 (presolve)
                    0.00 (postsolve)
  Nodes             4822
  LP iterations     175071 (total)
                    2371 (strong br.)
                    4533 (separation)
                    21028 (heuristics)
  Warning code 1 for call Highs_run(lp())
HiGHS 1.7.0: time limit, feasible solution
175071 simplex iterations
4822 branching nodes
absmipgap=3, relmipgap=0.0254237

In [ ]:
e_s5_highs = ampl.getVariable('e').getValues().toPandas()
e_s5_highs = e_s5_highs.reset_index()
e_s5_highs.columns = ['item_loja','caixa', 'chave_loja_buffer_onda', 'valor_multiplo']
e_s5_highs = e_s5_highs.query('valor_multiplo >0')
e_s5_highs#.head(20)

        item_loja  caixa  chave_loja_buffer_onda  valor_multiplo
36              1      8                       2    8.401265e-17
86              1     18                       2    4.000000e+00
284             1     57                       5    2.000000e+00
393             1     79                       4    1.000000e+00
394             1     79                       5    1.000000e+00
...           ...    ...                     ...             ...
120066        209     94                       2    1.000000e+00
120736        210    113                       2    1.000000e+00
121121        211     75                       2    2.000000e+00
121411        212     18                       2    1.000000e+00
121806        212     97                       2    1.000000e+00

[1455 rows x 4 columns]

In [ ]:
y_s5_highs = ampl.getVariable('y').getValues().toPandas()
y_s5_highs = y_s5_highs.reset_index()
y_s5_highs.columns = ['Caixa','chave_loja_buffer_onda', 'selecao']
y_s5_highs = y_s5_highs.query('selecao>0')

df_caixas_por_loja_highs_s5 = y_s5_highs.pivot_table(index='Caixa', columns='chave_loja_buffer_onda', values='selecao', fill_value=0)
df_caixas_por_loja_highs_s5 = df_caixas_por_loja_highs_s5.reset_index()
df_caixas_por_loja_highs_s5.columns.name = None
df_caixas_por_loja_highs_s5 # as colunas são as lojas

    Caixa    1    2    3    4    5
0       6  0.0  0.0  0.0  0.0  1.0
1       7  0.0  1.0  0.0  0.0  0.0
2       8  0.0  1.0  0.0  0.0  0.0
3      18  0.0  1.0  0.0  0.0  0.0
4      23  0.0  1.0  0.0  0.0  0.0
..    ...  ...  ...  ...  ...  ...
60    111  1.0  0.0  0.0  1.0  0.0
61    112  0.0  0.0  0.0  1.0  0.0
62    113  0.0  1.0  1.0  1.0  0.0
63    114  0.0  1.0  1.0  1.0  1.0
64    115  1.0  0.0  1.0  1.0  0.0

[65 rows x 6 columns]

In [ ]:
df_caixas_por_loja_highs_s5.columns = (['caixas'] + list(w.columns)) # os número das colunas são os nomes das lojas
df_caixas_por_loja_highs_s5

    caixas  13_EN_4  20_CX_4  31_CX_6  65_EN_4  9_CX_7
0        6      0.0      0.0      0.0      0.0     1.0
1        7      0.0      1.0      0.0      0.0     0.0
2        8      0.0      1.0      0.0      0.0     0.0
3       18      0.0      1.0      0.0      0.0     0.0
4       23      0.0      1.0      0.0      0.0     0.0
..     ...      ...      ...      ...      ...     ...
60     111      1.0      0.0      0.0      1.0     0.0
61     112      0.0      0.0      0.0      1.0     0.0
62     113      0.0      1.0      1.0      1.0     0.0
63     114      0.0      1.0      1.0      1.0     1.0
64     115      1.0      0.0      1.0      1.0     0.0

[65 rows x 6 columns]

#### Caixas

In [ ]:
print('Solver Highs')
total_caixas = 0
for col in w.columns:
    print(f'número de caixas para a chave_loja_buffer_onda "{col}": {df_caixas_por_loja_highs_s5[col].sum()}')
    total_caixas += df_caixas_por_loja_highs_s5[col].sum()
print(f'\ntotal de caixas: {total_caixas}')

Solver Highs
número de caixas para a chave_loja_buffer_onda "13_EN_4": 29.0
número de caixas para a chave_loja_buffer_onda "20_CX_4": 21.0
número de caixas para a chave_loja_buffer_onda "31_CX_6": 5.0
número de caixas para a chave_loja_buffer_onda "65_EN_4": 37.0
número de caixas para a chave_loja_buffer_onda "9_CX_7": 26.0

total de caixas: 118.0