# 0- Imports

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
try:
    from amplpy import AMPL, tools
except ImportError:
    # Caso ocorra um erro ao importar, instala amplpy e tenta importar novamente
    %pip install amplpy
    from amplpy import AMPL, tools

In [3]:
licenca ="default"

In [4]:

ampl = tools.ampl_notebook(
    modules=["highs", "gokestrel", "gurobi", "cplex"],  # Módulos a serem instalados
    license_uuid=licenca,  # Licença a ser utilizada
    g=globals()  # Instancia o objeto AMPL e registra os comandos mágicos
)

VBox(children=(Output(), HBox(children=(Text(value='', description='License UUID:', style=TextStyle(descriptio…

# 1- Base

Importando a base pré-processada com o limite de produção diário de:
<ul>
    <li>120.000 peças para o “Tipo de buffer” CX e </li>
    <li>100.000 peças para o “Tipo de buffer” EN.</li>
 </ul>

In [5]:
df_process = pd.read_excel('../../01-Data/ordens_pre_process_revisado.xlsx')

df_process

,Unnamed: 0,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Tipo_de_buffer,Item_pai,Cor,Tamanho,Inner,Rota,Capacidade,pai_cor,chave_loja_buffer_onda,Volume_unit
0,0,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,...,CX,1865,6.0,27,1,1,inf,1865_6.0,26_CX_5,3092300
1,1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,...,CX,1865,6.0,21,1,1,inf,1865_6.0,26_CX_5,3321500
2,2,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,...,CX,1865,6.0,4,1,1,inf,1865_6.0,26_CX_5,3537200
3,3,9002,2023-10-16,804068334,116,106,19,0.082,1,CARTON_S,...,CX,2489,674.0,179,1,3,inf,2489_674.0,116_CX_6,233624
4,4,11552,2023-10-16,825051881,235,110,30,0.092,10,CARTON_M,...,CX,2988,451.0,109,1,1,inf,2988_451.0,16_CX_2,775500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62226,62226,6095,2023-11-22,623412941,420,278,28,0.213,2,CARTON_M,...,EN,1863,2.0,38,1,15,4.000000e+10,1863_2.0,48_EN_2,3269280
62227,62227,5591,2023-11-22,623412950,427,305,31,0.233,1,CARTON_M,...,EN,1863,2.0,58,1,15,4.000000e+10,1863_2.0,48_EN_2,4037285
62228,62228,11858,2023-11-22,623412933,408,264,30,0.195,2,CARTON_M,...,EN,1863,2.0,16,1,15,4.000000e+10,1863_2.0,48_EN_2,3231360
62229,62229,10583,2023-11-22,622808371,371,233,49,0.323,1,CARTON_M,...,EN,713,275.0,16,1,15,4.000000e+10,713_275.0,48_EN_2,4235707
62230,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,EN,15,9.0,6,1,15,4.000000e+10,15_9.0,48_EN_3,3156208

In [6]:
df_process = df_process.rename(columns={'Unnamed: 0': "Id"})

In [7]:
df_process = df_process.rename(columns={'Capacidade': "Capacidade_rota"})

In [8]:
df_process.columns

Index(['Id', 'Ordem_de_produção', 'Data_da_ordem_de_produção', 'Produto',
       'Comprimento_unit', 'Largura_unit', 'Altura_unit', 'Peso_unit', 'Peças',
       'Caixa_padrão', 'Loja', 'Classe_de_onda', 'Tipo_de_buffer', 'Item_pai',
       'Cor', 'Tamanho', 'Inner', 'Rota', 'Capacidade_rota', 'pai_cor',
       'chave_loja_buffer_onda', 'Volume_unit'],
      dtype='object')

In [9]:
df_process.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62231 entries, 0 to 62230
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         62231 non-null  int64
 1   Ordem_de_produção          62231 non-null  int64
 2   Data_da_ordem_de_produção  62231 non-null  datetime64[ns]
 3   Produto                    62231 non-null  int64
 4   Comprimento_unit           62231 non-null  int64
 5   Largura_unit               62231 non-null  int64
 6   Altura_unit                62231 non-null  int64
 7   Peso_unit                  62231 non-null  float64
 8   Peças                      62231 non-null  int64
 9   Caixa_padrão               62231 non-null  object
 10  Loja                       62231 non-null  int64
 11  Classe_de_onda             62231 non-null  int64
 12  Tipo_de_buffer             62231 non-null  object
 13  Item_pai                   62231 non-null  int64
 14  Cor                        62231 non-null  float64
 15  Tamanho                    62231 non-null  int64
 16  Inner                      62231 non-null  int64
 17  Rota                       62231 non-null  int64
 18  Capacidade_rota            62231 non-null  float64
 19  pai_cor                    62231 non-null  object
 20  chave_loja_buffer_onda     62231 non-null  object
 21  Volume_unit                62231 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(14), object(4)
memory usage: 10.4+ MB

## Caixa padrão

In [10]:
df_caixas_tipo = pd.read_excel('../../01-Data/Dados - desafio disciplina RPVMM_edit.xlsx', sheet_name='Tipos de caixa')
df_caixas_tipo

,Tipo,Tipo de buffer,Comprimento,Largura,Altura,Fator de ocupação,Peças max,Peso max (kg)
0,Caixa 1,CX,380,285,285,0.9,170,23
1,Caixa 2,CX,586,436,272,1.2,170,23
2,Caixa 3,CX,728,427,270,0.9,170,23
3,Caixa 1,EN,380,285,285,0.9,512,23
4,Caixa 2,EN,586,436,272,1.2,512,23
5,Caixa 3,EN,728,427,270,0.9,512,23

In [11]:
df_caixas_tipo.columns = df_caixas_tipo.columns.str.replace(' ', '_')

In [12]:
df_caixas_tipo['volume_util_caixa'] = df_caixas_tipo['Comprimento'] * df_caixas_tipo['Largura'] * df_caixas_tipo['Altura'] * df_caixas_tipo['Fator_de_ocupação']

df_caixas_tipo

,Tipo,Tipo_de_buffer,Comprimento,Largura,Altura,Fator_de_ocupação,Peças_max,Peso_max_(kg),volume_util_caixa
0,Caixa 1,CX,380,285,285,0.9,170,23,27778950.0
1,Caixa 2,CX,586,436,272,1.2,170,23,83393894.4
2,Caixa 3,CX,728,427,270,0.9,170,23,75538008.0
3,Caixa 1,EN,380,285,285,0.9,512,23,27778950.0
4,Caixa 2,EN,586,436,272,1.2,512,23,83393894.4
5,Caixa 3,EN,728,427,270,0.9,512,23,75538008.0

In [13]:
df_caixas_tipo.pivot(index='Tipo_de_buffer', columns=['Tipo','volume_util_caixa'], values=['Peças_max', 'volume_util_caixa']).reset_index()

                  Tipo_de_buffer  Peças_max                        \
Tipo                                Caixa 1    Caixa 2    Caixa 3
volume_util_caixa                27778950.0 83393894.4 75538008.0
0                             CX      170.0      170.0      170.0
1                             EN      512.0      512.0      512.0

                  volume_util_caixa
Tipo                        Caixa 1     Caixa 2     Caixa 3
volume_util_caixa        27778950.0  83393894.4  75538008.0
0                        27778950.0  83393894.4  75538008.0
1                        27778950.0  83393894.4  75538008.0

In [14]:
df_caixas_tipo.pivot(index='Tipo_de_buffer', columns='Tipo', values='volume_util_caixa').add_prefix('volume_util_caixa_').reset_index()

Tipo,Tipo_de_buffer,volume_util_caixa_Caixa 1,volume_util_caixa_Caixa 2,volume_util_caixa_Caixa 3
0,CX,27778950.0,83393894.4,75538008.0
1,EN,27778950.0,83393894.4,75538008.0

In [15]:
df_caixas_tipo.pivot(index='Tipo_de_buffer', columns='Tipo', values='Peças_max').add_prefix('Peças_max_').reset_index()

Tipo Tipo_de_buffer  Peças_max_Caixa 1  Peças_max_Caixa 2  Peças_max_Caixa 3
0                CX                170                170                170
1                EN                512                512                512

In [16]:
df_caixas_tipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tipo               6 non-null      object
 1   Tipo_de_buffer     6 non-null      object
 2   Comprimento        6 non-null      int64
 3   Largura            6 non-null      int64
 4   Altura             6 non-null      int64
 5   Fator_de_ocupação  6 non-null      float64
 6   Peças_max          6 non-null      int64
 7   Peso_max_(kg)      6 non-null      int64
 8   volume_util_caixa  6 non-null      float64
dtypes: float64(2), int64(5), object(2)
memory usage: 564.0+ bytes

In [17]:
df_caixas_tipo.columns

Index(['Tipo', 'Tipo_de_buffer', 'Comprimento', 'Largura', 'Altura',
       'Fator_de_ocupação', 'Peças_max', 'Peso_max_(kg)', 'volume_util_caixa'],
      dtype='object')

Temos um tipo de caixa padrão para cada tipo de buffer

In [18]:
df_caixas_padrao = df_caixas_tipo.loc[[1, 5]]
df_caixas_padrao

,Tipo,Tipo_de_buffer,Comprimento,Largura,Altura,Fator_de_ocupação,Peças_max,Peso_max_(kg),volume_util_caixa
1,Caixa 2,CX,586,436,272,1.2,170,23,83393894.4
5,Caixa 3,EN,728,427,270,0.9,512,23,75538008.0

Levar a capacidade das caixas para cada ordem de produção:

O **número de peças máximo** varia com o buffer. Já o *volume* é igual para ambos os tipos, mudando apenas para o **tipo de caixa**

In [19]:
df_caixa_volume_max= df_caixas_tipo.pivot(index='Tipo_de_buffer', columns='Tipo', values='volume_util_caixa').add_prefix('volume_util_caixa_').reset_index()

df_caixa_volume_max

Tipo,Tipo_de_buffer,volume_util_caixa_Caixa 1,volume_util_caixa_Caixa 2,volume_util_caixa_Caixa 3
0,CX,27778950.0,83393894.4,75538008.0
1,EN,27778950.0,83393894.4,75538008.0

In [20]:
df_process_capacitado = df_process.merge(df_caixa_volume_max, on='Tipo_de_buffer', how='inner')

df_process_capacitado

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Tamanho,Inner,Rota,Capacidade_rota,pai_cor,chave_loja_buffer_onda,Volume_unit,volume_util_caixa_Caixa 1,volume_util_caixa_Caixa 2,volume_util_caixa_Caixa 3
0,0,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,...,27,1,1,inf,1865_6.0,26_CX_5,3092300,27778950.0,83393894.4,75538008.0
1,1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,...,21,1,1,inf,1865_6.0,26_CX_5,3321500,27778950.0,83393894.4,75538008.0
2,2,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,...,4,1,1,inf,1865_6.0,26_CX_5,3537200,27778950.0,83393894.4,75538008.0
3,3,9002,2023-10-16,804068334,116,106,19,0.082,1,CARTON_S,...,179,1,3,inf,2489_674.0,116_CX_6,233624,27778950.0,83393894.4,75538008.0
4,4,11552,2023-10-16,825051881,235,110,30,0.092,10,CARTON_M,...,109,1,1,inf,2988_451.0,16_CX_2,775500,27778950.0,83393894.4,75538008.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62226,62226,6095,2023-11-22,623412941,420,278,28,0.213,2,CARTON_M,...,38,1,15,4.000000e+10,1863_2.0,48_EN_2,3269280,27778950.0,83393894.4,75538008.0
62227,62227,5591,2023-11-22,623412950,427,305,31,0.233,1,CARTON_M,...,58,1,15,4.000000e+10,1863_2.0,48_EN_2,4037285,27778950.0,83393894.4,75538008.0
62228,62228,11858,2023-11-22,623412933,408,264,30,0.195,2,CARTON_M,...,16,1,15,4.000000e+10,1863_2.0,48_EN_2,3231360,27778950.0,83393894.4,75538008.0
62229,62229,10583,2023-11-22,622808371,371,233,49,0.323,1,CARTON_M,...,16,1,15,4.000000e+10,713_275.0,48_EN_2,4235707,27778950.0,83393894.4,75538008.0
62230,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,6,1,15,4.000000e+10,15_9.0,48_EN_3,3156208,27778950.0,83393894.4,75538008.0

In [21]:
df_process_capacitado.columns = df_process_capacitado.columns.str.replace(' ', '_')

In [22]:
import numpy as np
df_process_capacitado['volume_util_padrao'] = np.where(df_process_capacitado['Tipo_de_buffer'] == "EN", df_process_capacitado['volume_util_caixa_Caixa_3'], df_process_capacitado['volume_util_caixa_Caixa_2'])

In [23]:
df_process_capacitado = df_process_capacitado.merge(df_caixas_padrao[['Tipo_de_buffer', 'Peças_max']], on='Tipo_de_buffer', how='inner')
df_process_capacitado

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Rota,Capacidade_rota,pai_cor,chave_loja_buffer_onda,Volume_unit,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max
0,0,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,...,1,inf,1865_6.0,26_CX_5,3092300,27778950.0,83393894.4,75538008.0,83393894.4,170
1,1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,...,1,inf,1865_6.0,26_CX_5,3321500,27778950.0,83393894.4,75538008.0,83393894.4,170
2,2,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,...,1,inf,1865_6.0,26_CX_5,3537200,27778950.0,83393894.4,75538008.0,83393894.4,170
3,3,9002,2023-10-16,804068334,116,106,19,0.082,1,CARTON_S,...,3,inf,2489_674.0,116_CX_6,233624,27778950.0,83393894.4,75538008.0,83393894.4,170
4,4,11552,2023-10-16,825051881,235,110,30,0.092,10,CARTON_M,...,1,inf,2988_451.0,16_CX_2,775500,27778950.0,83393894.4,75538008.0,83393894.4,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62226,62226,6095,2023-11-22,623412941,420,278,28,0.213,2,CARTON_M,...,15,4.000000e+10,1863_2.0,48_EN_2,3269280,27778950.0,83393894.4,75538008.0,75538008.0,512
62227,62227,5591,2023-11-22,623412950,427,305,31,0.233,1,CARTON_M,...,15,4.000000e+10,1863_2.0,48_EN_2,4037285,27778950.0,83393894.4,75538008.0,75538008.0,512
62228,62228,11858,2023-11-22,623412933,408,264,30,0.195,2,CARTON_M,...,15,4.000000e+10,1863_2.0,48_EN_2,3231360,27778950.0,83393894.4,75538008.0,75538008.0,512
62229,62229,10583,2023-11-22,622808371,371,233,49,0.323,1,CARTON_M,...,15,4.000000e+10,713_275.0,48_EN_2,4235707,27778950.0,83393894.4,75538008.0,75538008.0,512
62230,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,15,4.000000e+10,15_9.0,48_EN_3,3156208,27778950.0,83393894.4,75538008.0,75538008.0,512

In [24]:
df_process_capacitado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62231 entries, 0 to 62230
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         62231 non-null  int64
 1   Ordem_de_produção          62231 non-null  int64
 2   Data_da_ordem_de_produção  62231 non-null  datetime64[ns]
 3   Produto                    62231 non-null  int64
 4   Comprimento_unit           62231 non-null  int64
 5   Largura_unit               62231 non-null  int64
 6   Altura_unit                62231 non-null  int64
 7   Peso_unit                  62231 non-null  float64
 8   Peças                      62231 non-null  int64
 9   Caixa_padrão               62231 non-null  object
 10  Loja                       62231 non-null  int64
 11  Classe_de_onda             62231 non-null  int64
 12  Tipo_de_buffer             62231 non-null  object
 13  Item_pai                   62231 non-null  int64
 14  Cor                        62231 non-null  float64
 15  Tamanho                    62231 non-null  int64
 16  Inner                      62231 non-null  int64
 17  Rota                       62231 non-null  int64
 18  Capacidade_rota            62231 non-null  float64
 19  pai_cor                    62231 non-null  object
 20  chave_loja_buffer_onda     62231 non-null  object
 21  Volume_unit                62231 non-null  int64
 22  volume_util_caixa_Caixa_1  62231 non-null  float64
 23  volume_util_caixa_Caixa_2  62231 non-null  float64
 24  volume_util_caixa_Caixa_3  62231 non-null  float64
 25  volume_util_padrao         62231 non-null  float64
 26  Peças_max                  62231 non-null  int64
dtypes: datetime64[ns](1), float64(7), int64(15), object(4)
memory usage: 12.8+ MB

In [25]:
df_process_capacitado['chave_loja_buffer_onda'].nunique()

1508

In [26]:
df_process_capacitado.groupby('chave_loja_buffer_onda')['Peças'].sum().sort_values(ascending=False).head(20)

chave_loja_buffer_onda
10_EN_3    3459
28_EN_4    3187
16_EN_3    2093
2_EN_3     2086
10_CX_1    1948
31_EN_3    1802
33_EN_3    1786
3_CX_9     1690
8_EN_4     1620
3_CX_1     1555
10_EN_4    1509
9_EN_4     1464
10_CX_4    1441
3_EN_3     1403
25_EN_4    1367
31_CX_1    1366
18_EN_4    1360
48_EN_4    1355
8_EN_3     1348
10_EN_1    1329
Name: Peças, dtype: int64

In [27]:
(df_process_capacitado.groupby('chave_loja_buffer_onda')['Peças'].sum().sort_values(ascending=False).head(20)).index

Index(['10_EN_3', '28_EN_4', '16_EN_3', '2_EN_3', '10_CX_1', '31_EN_3',
       '33_EN_3', '3_CX_9', '8_EN_4', '3_CX_1', '10_EN_4', '9_EN_4', '10_CX_4',
       '3_EN_3', '25_EN_4', '31_CX_1', '18_EN_4', '48_EN_4', '8_EN_3',
       '10_EN_1'],
      dtype='object', name='chave_loja_buffer_onda')

In [28]:
lojas_selecionadas_maiores = list((df_process_capacitado.groupby('chave_loja_buffer_onda')['Peças'].sum().sort_values(ascending=False).head(20)).index)
lojas_selecionadas_maiores

['10_EN_3',
 '28_EN_4',
 '16_EN_3',
 '2_EN_3',
 '10_CX_1',
 '31_EN_3',
 '33_EN_3',
 '3_CX_9',
 '8_EN_4',
 '3_CX_1',
 '10_EN_4',
 '9_EN_4',
 '10_CX_4',
 '3_EN_3',
 '25_EN_4',
 '31_CX_1',
 '18_EN_4',
 '48_EN_4',
 '8_EN_3',
 '10_EN_1']

In [29]:
df_process_capacitado.query(f"chave_loja_buffer_onda in ({lojas_selecionadas_maiores})")

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Rota,Capacidade_rota,pai_cor,chave_loja_buffer_onda,Volume_unit,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max
14,14,1429,2023-10-24,534996762,364,167,90,0.090,1,CARTON_M,...,8,4.000000e+10,777_1.0,10_CX_1,5470920,27778950.0,83393894.4,75538008.0,83393894.4,170
15,15,1499,2023-10-24,534996762,364,167,90,0.090,1,CARTON_M,...,8,4.000000e+10,777_1.0,10_CX_1,5470920,27778950.0,83393894.4,75538008.0,83393894.4,170
16,16,1499,2023-10-24,539354355,250,100,70,0.200,2,CARTON_M,...,8,4.000000e+10,777_95.0,10_CX_1,1750000,27778950.0,83393894.4,75538008.0,83393894.4,170
17,17,909,2023-10-24,539354355,250,100,70,0.200,2,CARTON_M,...,8,4.000000e+10,777_95.0,10_CX_1,1750000,27778950.0,83393894.4,75538008.0,83393894.4,170
18,18,1499,2023-10-24,539354347,250,100,55,0.180,1,CARTON_M,...,8,4.000000e+10,777_95.0,10_CX_1,1375000,27778950.0,83393894.4,75538008.0,83393894.4,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61584,61584,8067,2023-11-22,878451301,431,234,19,0.215,24,CARTON_M,...,10,2.720000e+10,930_283.0,28_EN_4,1916226,27778950.0,83393894.4,75538008.0,75538008.0,512
61585,61585,9984,2023-11-22,878451328,424,245,18,0.187,15,CARTON_M,...,10,2.720000e+10,930_283.0,28_EN_4,1869840,27778950.0,83393894.4,75538008.0,75538008.0,512
61586,61586,1157,2023-11-22,873049031,450,306,23,0.287,2,CARTON_M,...,10,2.720000e+10,943_18.0,28_EN_4,3167100,27778950.0,83393894.4,75538008.0,75538008.0,512
61587,61587,8666,2023-11-22,873049102,450,315,20,0.307,2,CARTON_M,...,10,2.720000e+10,943_18.0,28_EN_4,2835000,27778950.0,83393894.4,75538008.0,75538008.0,512
61588,61588,9502,2023-11-22,873049049,450,329,25,0.280,11,CARTON_M,...,10,2.720000e+10,943_18.0,28_EN_4,3701250,27778950.0,83393894.4,75538008.0,75538008.0,512

In [30]:
df_process_capacitado.query(f"chave_loja_buffer_onda in ({lojas_selecionadas_maiores})")['Peças'].sum()

35168

# 2- Modelagem

## 2.1- CSP - Limitação da caixa predecessora

Vamos adicionar uma condição em que o tipo de buffer varia conforme a chave da loja

<p>O peso máximo é mesmo, indenpendente o tipo de buffer. Além disso, nesse momento iremos utilizar o volume padrão para cada buffer</p>

Modelagem matemática 

Dado que temos $n$ tipos de itens $i$ para empacotar, para $k$ lojas, cada um com peso $w_{i k}$, um volume $v_{i k}$, um múltiplo $inner_{i k}$ da quantidade de itens a serem selecionados uma demanda $d_{i k}$, para todo $i \in \{1,...,n\}$ e $k \in \{1,...,r\}$, e um número $m$ de mochilas (caixas) $j$ diferentes com capacidade volumétrica $cv_{k}$, uma capacidade de peso $cp$ e uma capacidade em número de peças $np_{k}$, então temos:

$$
\begin{aligned}
\text{minimizar} \quad &\sum_{j = 1}^{m} \sum_{k = 1}^{r} y_{j k} \\
\text{sujeito a} \quad &\sum_{i = 1}^{n} w_{i k} \xi_{i j k}*inner_{i k} \leq cp*y_{j k} \quad \forall j \in \{1,...,m\} , k \in \{1,...,r\}\\
&\sum_{i = 1}^{n} v_{i k} \xi_{i j k} *inner_{i k} \leq cv_{k}*y_{j k} \quad \forall j \in \{1,...,m\} , k \in \{1,...,r\} \\
&\sum_{i = 1}^{n} \xi_{i j k} *inner_{i k} \leq np_{k}*y_{j k} \quad \forall j \in \{1,...,m\} , k \in \{1,...,r\} \\
&\sum_{j = 1}^{m} \xi_{i j k} *inner_{i k} = d_{i k} \quad \forall i \in \{1,...,n\}, k \in \{1,...,r\}\\
&y_{j k} \geq y_{j+1,k} \quad \forall j \in \{1,...,m\} , k \in \{1,...,r\} \\
&\xi_{i j k} \geq0 \in \mathbb{Z} \quad \forall i \in \{1,...,n\}, j \in \{1,...,m\} , k \in \{1,...,r\} \\
&y_{j k} \in \{0,1\} \quad \forall j \in \{1,...,m\}, k \in \{1,...,r\}
\end{aligned}
$$


 Seja $\quad$ $\xi_{i j k}$= número de itens tipo $i$ adicionados na mochila $j$, para a loja $k$.

In [31]:
%%ampl_eval
reset;

param n;  # número de tipos de itens
param cp; # capacidade de peso de cada caixa
param r;  # número de lojas (rotas)

suffix master IN, binary;
suffix block IN, integer;

set I = 1..n ordered; # tipos de itens
set K = 1..r ordered; # lojas (rotas)
param w {I,K} >= 0; # peso do item tipo i para a loja k
param v {I,K} >= 0; # volume do item tipo i para a loja k
param inner{I,K} >= 0; # múltiplo da quantidade de itens a serem selecionados
param d {I,K} >= 0; # demanda de itens tipo i para a loja k

param cv {K} >= 0; # capacidade volumétrica de cada loja (rota)
param np {K} >= 0; # capacidade em número de peças para cada loja (rota)

param maxVal := max {i in I, k in K} w[i,k];

param maxVal_peso := max {i in I, k in K} w[i,k];
param pecas_caixa:= floor(cp / maxVal_peso);

param soma := sum{i in I, k in K} d[i, k];
param maxbins := ceil(soma / pecas_caixa);

set J = 1..maxbins ordered;

var e {I,J,K} integer >= 0; # número de itens tipo i na caixa j para a chave loja k
var y {J,K} binary; # 1 se a caixa j é usada para a loja k

minimize FO:  sum {j in J, k in K} y[j,k];

s.t. R1_capacidade_mochila_peso {j in J, k in K}:
   sum {i in I} w[i,k] * e[i,j,k] * inner[i,k] <= cp * y[j,k] suffix block j;

s.t. R2_capacidade_mochila_volume {j in J, k in K}:
   sum {i in I} v[i,k] * e[i,j,k] * inner[i,k] <= cv[k] * y[j,k] suffix block j;

s.t. R3_capacidade_mochila_pecas {j in J, k in K}:
   sum {i in I} e[i,j,k] * inner[i,k] <= np[k] * y[j,k] suffix block k;

s.t. R4_quantidade_demanda {i in I, k in K}:
   sum {j in J} e[i,j,k]* inner[i,k] = d[i,k] suffix master 1;

s.t. R5_predecessor_caixas {j in 1..maxbins-1, k in K}:
   y[j,k] >= y[j+1,k];

### 2.1.1- Importar dados

In [32]:
df_process_situacao2 = df_process_capacitado.query("chave_loja_buffer_onda in ('25_EN_2', '143_EN_1', '44_CX_3')")

df_process_situacao2

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Rota,Capacidade_rota,pai_cor,chave_loja_buffer_onda,Volume_unit,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max
7129,7129,325,2023-11-07,548143461,309,202,16,0.110,5,CARTON_M,...,1,inf,1155_1.0,44_CX_3,998688,27778950.0,83393894.4,75538008.0,83393894.4,170
7130,7130,325,2023-11-07,548143470,304,322,17,0.186,1,CARTON_M,...,1,inf,1155_1.0,44_CX_3,1664096,27778950.0,83393894.4,75538008.0,83393894.4,170
7131,7131,325,2023-11-07,548143488,296,280,13,0.155,1,CARTON_M,...,1,inf,1155_1.0,44_CX_3,1077440,27778950.0,83393894.4,75538008.0,83393894.4,170
7132,7132,325,2023-11-07,548143496,313,308,13,0.145,1,CARTON_M,...,1,inf,1155_1.0,44_CX_3,1253252,27778950.0,83393894.4,75538008.0,83393894.4,170
7133,7133,325,2023-11-07,548143429,317,197,22,0.120,2,CARTON_M,...,1,inf,1155_3.0,44_CX_3,1373878,27778950.0,83393894.4,75538008.0,83393894.4,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61395,61395,3404,2023-11-22,626471971,381,179,44,0.253,1,CARTON_M,...,6,2.720000e+10,920_2.0,25_EN_2,3000756,27778950.0,83393894.4,75538008.0,75538008.0,512
61396,61396,6199,2023-11-22,626472018,415,208,54,0.280,3,CARTON_M,...,6,2.720000e+10,920_2.0,25_EN_2,4661280,27778950.0,83393894.4,75538008.0,75538008.0,512
61397,61397,7945,2023-11-22,626471998,407,188,43,0.217,3,CARTON_M,...,6,2.720000e+10,920_2.0,25_EN_2,3290188,27778950.0,83393894.4,75538008.0,75538008.0,512
61398,61398,8427,2023-11-22,626471955,403,197,43,0.300,3,CARTON_M,...,6,2.720000e+10,920_2.0,25_EN_2,3413813,27778950.0,83393894.4,75538008.0,75538008.0,512
61399,61399,10798,2023-11-22,626471947,400,185,61,0.315,4,CARTON_M,...,6,2.720000e+10,920_2.0,25_EN_2,4514000,27778950.0,83393894.4,75538008.0,75538008.0,512

In [33]:
df_process_situacao2['Peças_max'].unique()

array([170, 512], dtype=int64)

In [34]:
df_process_situacao2.columns

Index(['Id', 'Ordem_de_produção', 'Data_da_ordem_de_produção', 'Produto',
       'Comprimento_unit', 'Largura_unit', 'Altura_unit', 'Peso_unit', 'Peças',
       'Caixa_padrão', 'Loja', 'Classe_de_onda', 'Tipo_de_buffer', 'Item_pai',
       'Cor', 'Tamanho', 'Inner', 'Rota', 'Capacidade_rota', 'pai_cor',
       'chave_loja_buffer_onda', 'Volume_unit', 'volume_util_caixa_Caixa_1',
       'volume_util_caixa_Caixa_2', 'volume_util_caixa_Caixa_3',
       'volume_util_padrao', 'Peças_max'],
      dtype='object')

### 2.1.2- Entrada de dados no modelo

In [35]:
# Adicionar uma coluna para identificar cada item dentro de cada chave_loja_buffer_onda
df_process_situacao2['item_loja'] = df_process_situacao2.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Peso_unit'

df_matriz_peso = df_process_situacao2.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_peso.columns.name = None

df_matriz_peso

    item_loja  143_EN_1  25_EN_2  44_CX_3
0           1      0.13    0.160    0.110
1           2      0.11    0.220    0.186
2           3      0.13    0.270    0.155
3           4      0.12    0.120    0.145
4           5      0.25    0.113    0.120
..        ...       ...      ...      ...
73         74      0.00    0.253    0.000
74         75      0.00    0.280    0.000
75         76      0.00    0.217    0.000
76         77      0.00    0.300    0.000
77         78      0.00    0.315    0.000

[78 rows x 4 columns]

In [36]:
# Variável avaliada:
variavel_ik = 'Volume_unit'

df_matriz_volume = df_process_situacao2.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_volume.columns.name = None

df_matriz_volume

    item_loja   143_EN_1    25_EN_2    44_CX_3
0           1  2628096.0   859815.0   998688.0
1           2  2872584.0  1426230.0  1664096.0
2           3  3165864.0  2767910.0  1077440.0
3           4  2095510.0  1839120.0  1253252.0
4           5  4732892.0  1952896.0  1373878.0
..        ...        ...        ...        ...
73         74        0.0  3000756.0        0.0
74         75        0.0  4661280.0        0.0
75         76        0.0  3290188.0        0.0
76         77        0.0  3413813.0        0.0
77         78        0.0  4514000.0        0.0

[78 rows x 4 columns]

In [37]:
# Adicionar uma coluna para identificar cada item dentro de cada loja
df_process_situacao2['item_loja'] = df_process_situacao2.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Inner'

df_matriz_inner = df_process_situacao2.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_inner.columns.name = None

df_matriz_inner

    item_loja  143_EN_1  25_EN_2  44_CX_3
0           1       1.0      1.0      1.0
1           2       1.0      1.0      1.0
2           3       1.0      1.0      1.0
3           4       1.0      1.0      1.0
4           5       1.0      1.0      1.0
..        ...       ...      ...      ...
73         74       0.0      1.0      0.0
74         75       0.0      1.0      0.0
75         76       0.0      1.0      0.0
76         77       0.0      1.0      0.0
77         78       0.0      1.0      0.0

[78 rows x 4 columns]

In [38]:
# Adicionar uma coluna para identificar cada item dentro de cada loja
df_process_situacao2['item_loja'] = df_process_situacao2.groupby('chave_loja_buffer_onda').cumcount() + 1

# Variável avaliada:
variavel_ik = 'Peças'

df_matriz_pecas = df_process_situacao2.pivot_table(index='item_loja', columns='chave_loja_buffer_onda', values= variavel_ik, fill_value=0).reset_index()

df_matriz_pecas.columns.name = None

df_matriz_pecas

    item_loja  143_EN_1  25_EN_2  44_CX_3
0           1      19.0      1.0      5.0
1           2      35.0      1.0      1.0
2           3       9.0      1.0      1.0
3           4      20.0      4.0      1.0
4           5       6.0      7.0      2.0
..        ...       ...      ...      ...
73         74       0.0      1.0      0.0
74         75       0.0      3.0      0.0
75         76       0.0      3.0      0.0
76         77       0.0      3.0      0.0
77         78       0.0      4.0      0.0

[78 rows x 4 columns]

In [39]:
df_process_situacao2

,Id,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Capacidade_rota,pai_cor,chave_loja_buffer_onda,Volume_unit,volume_util_caixa_Caixa_1,volume_util_caixa_Caixa_2,volume_util_caixa_Caixa_3,volume_util_padrao,Peças_max,item_loja
7129,7129,325,2023-11-07,548143461,309,202,16,0.110,5,CARTON_M,...,inf,1155_1.0,44_CX_3,998688,27778950.0,83393894.4,75538008.0,83393894.4,170,1
7130,7130,325,2023-11-07,548143470,304,322,17,0.186,1,CARTON_M,...,inf,1155_1.0,44_CX_3,1664096,27778950.0,83393894.4,75538008.0,83393894.4,170,2
7131,7131,325,2023-11-07,548143488,296,280,13,0.155,1,CARTON_M,...,inf,1155_1.0,44_CX_3,1077440,27778950.0,83393894.4,75538008.0,83393894.4,170,3
7132,7132,325,2023-11-07,548143496,313,308,13,0.145,1,CARTON_M,...,inf,1155_1.0,44_CX_3,1253252,27778950.0,83393894.4,75538008.0,83393894.4,170,4
7133,7133,325,2023-11-07,548143429,317,197,22,0.120,2,CARTON_M,...,inf,1155_3.0,44_CX_3,1373878,27778950.0,83393894.4,75538008.0,83393894.4,170,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61395,61395,3404,2023-11-22,626471971,381,179,44,0.253,1,CARTON_M,...,2.720000e+10,920_2.0,25_EN_2,3000756,27778950.0,83393894.4,75538008.0,75538008.0,512,74
61396,61396,6199,2023-11-22,626472018,415,208,54,0.280,3,CARTON_M,...,2.720000e+10,920_2.0,25_EN_2,4661280,27778950.0,83393894.4,75538008.0,75538008.0,512,75
61397,61397,7945,2023-11-22,626471998,407,188,43,0.217,3,CARTON_M,...,2.720000e+10,920_2.0,25_EN_2,3290188,27778950.0,83393894.4,75538008.0,75538008.0,512,76
61398,61398,8427,2023-11-22,626471955,403,197,43,0.300,3,CARTON_M,...,2.720000e+10,920_2.0,25_EN_2,3413813,27778950.0,83393894.4,75538008.0,75538008.0,512,77
61399,61399,10798,2023-11-22,626471947,400,185,61,0.315,4,CARTON_M,...,2.720000e+10,920_2.0,25_EN_2,4514000,27778950.0,83393894.4,75538008.0,75538008.0,512,78

Capacidade da caixa como variável

In [40]:
# Variável avaliada:
variavel_ik = 'Peças_max'

df_matriz_caixa_capacidade_pecas = df_process_situacao2.pivot_table(index='chave_loja_buffer_onda',  values= variavel_ik, fill_value=0).reset_index()

df_matriz_caixa_capacidade_pecas.columns.name = None

df_matriz_caixa_capacidade_pecas

  chave_loja_buffer_onda  Peças_max
0               143_EN_1      512.0
1                25_EN_2      512.0
2                44_CX_3      170.0

In [41]:
# Variável avaliada:
variavel_ik = 'volume_util_padrao'

df_matriz_caixa_capacidade_volume = df_process_situacao2.pivot_table(index='chave_loja_buffer_onda',  values= variavel_ik, fill_value=0).reset_index()

df_matriz_caixa_capacidade_volume.columns.name = None

df_matriz_caixa_capacidade_volume

  chave_loja_buffer_onda  volume_util_padrao
0               143_EN_1          75538008.0
1                25_EN_2          75538008.0
2                44_CX_3          83393894.4

Características das peças

In [42]:
peso =  df_matriz_peso
pecas = df_matriz_pecas  #demanda
volume = df_matriz_volume
inner = df_matriz_inner

Características da caixa

In [43]:
cp = 23
cv = df_matriz_caixa_capacidade_volume
np = df_matriz_caixa_capacidade_pecas

#### Parâmetros

In [44]:
ampl.param["n"] = len(pecas)   # tamanho da loja que tem mais itens

ampl.param["cp"] = cp
ampl.param["r"] = len(volume.columns) -1

cv_ = cv.drop(columns='chave_loja_buffer_onda')
np_ = np.drop(columns='chave_loja_buffer_onda')

v = volume.drop(columns='item_loja')
w = peso.drop(columns='item_loja')
d= pecas.drop(columns='item_loja')
inner_ = inner.drop(columns='item_loja')

ampl.param["w"] = {(i, k): w.iloc[i - 1][k - 1] for i in range(1, len(w)+1) for k in range(1, len(w.columns)+1)}
ampl.param["v"] = {(i, k): v.iloc[i - 1][k - 1] for i in range(1, len(v)+1) for k in range(1, len(v.columns)+1)}
ampl.param["d"] = {(i, k): d.iloc[i - 1][k - 1] for i in range(1, len(d)+1) for k in range(1, len(d.columns)+1)}
ampl.param["inner"] = {(i, k): inner_.iloc[i - 1][k - 1] for i in range(1, len(inner_)+1) for k in range(1, len(inner_.columns)+1)}

ampl.param["cv"] = {(k): cv_.iloc[k - 1] for k in range(1, len(cv_) + 1)}
ampl.param["np"] = {(k): np_.iloc[k - 1] for k in range(1, len(np_)+1)}

In [45]:
ampl.getValue('soma')

604

In [46]:
ampl.getValue('maxbins')

16

In [47]:
ampl.getValue('pecas_caixa')

40

### 2.1.3- Solvers

#### Solver Highs

In [48]:
ampl.option["solver"] = "highs"
ampl.option["highs_options"] = "outlev=1 timelimit=600"
ampl.solve()

HiGHS 1.7.0:   tech:outlev = 1
  lim:time = 600
Running HiGHS 1.7.0 (git hash: 50670fd): Copyright (c) 2024 HiGHS under MIT licence terms
Coefficient ranges:
  Matrix [6e-02, 8e+07]
  Cost   [1e+00, 1e+00]
  Bound  [1e+00, 3e+01]
  RHS    [1e+00, 4e+01]
Presolving model
342 rows, 2496 cols, 10026 nonzeros  0s
330 rows, 2489 cols, 9733 nonzeros  0s
Objective function is integral with scale 1

Solving MIP model with:
   330 rows
   2489 cols (793 binary, 1696 integer, 0 implied int., 0 continuous)
   9733 nonzeros

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   7               inf                  inf        0      0      0         0     0.0s
         0       0         0   0.00%   19.28318803     inf                  inf        0      0     11       526     0.1s
 L       0       0         0   0.00%   19.5098654      20                 2.45%     1038    169   1407      1004     0.4s

Solving report
  Status            Optimal
  Primal bound      20
  Dual bound        20
  Gap               0% (tolerance: 0.01%)
  Solution status   feasible
                    20 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            0.37 (total)
                    0.03 (presolve)
                    0.00 (postsolve)
  Nodes             1
  LP iterations     1108 (total)
                    0 (strong br.)
                    478 (separation)
                    104 (heuristics)
HiGHS 1.7.0: optimal solution; objective 20
1108 simplex iterations
1 branching nodes

In [49]:
%%ampl_eval
display FO;

FO = 20

In [50]:
%%ampl_eval
display R3_capacidade_mochila_pecas;

R3_capacidade_mochila_pecas [*,*]
:    1   2   3    :=
1    0   0   0
2    0   0   0
3    0   0   0
4    0   0   0
5    0   0   0
6    0   0   0
7    0   0   0
8    0   0   0
9    0   0   0
10   0   0   0
11   0   0   0
12   0   0   0
13   0   0   0
14   0   0   0
15   0   0   0
16   0   0   0
;

In [51]:
e_s2_highs = ampl.getVariable('e').getValues().toPandas()
e_s2_highs = e_s2_highs.reset_index()
e_s2_highs.columns = ['item_loja','caixa', 'chave_loja_buffer_onda', 'valor_multiplo']
e_s2_highs = e_s2_highs.query('valor_multiplo >0')
e_s2_highs#.head(20)

      item_loja  caixa  chave_loja_buffer_onda  valor_multiplo
0             1      1                       1              19
11            1      4                       3               5
13            1      5                       2               1
51            2      2                       1              20
56            2      3                       3               1
...         ...    ...                     ...             ...
3514         74      4                       2               1
3568         75      6                       2               3
3607         76      3                       2               3
3664         77      6                       2               3
3709         78      5                       2               4

[174 rows x 4 columns]

In [52]:
df_agrupamento_loja1_highs_s2 = e_s2_highs.query('chave_loja_buffer_onda == 1').pivot_table(index='item_loja', columns='caixa', values='valor_multiplo', fill_value=0)
df_agrupamento_loja1_highs_s2 = df_agrupamento_loja1_highs_s2.reset_index()
df_agrupamento_loja1_highs_s2.columns.name = None
df_agrupamento_loja1_highs_s2 # as colunas são as caixas

    item_loja     1     2     3     4    5     6    7
0           1  19.0   0.0   0.0   0.0  0.0   0.0  0.0
1           2   0.0  20.0   0.0  14.0  0.0   1.0  0.0
2           3   0.0   0.0   0.0   0.0  0.0   9.0  0.0
3           4   0.0   0.0  11.0   0.0  0.0   0.0  9.0
4           5   0.0   0.0   6.0   0.0  0.0   0.0  0.0
5           6   0.0   0.0   0.0   0.0  9.0   0.0  0.0
6           7   8.0   6.0   0.0   0.0  0.0   0.0  0.0
7           8   0.0   0.0   0.0   0.0  0.0  12.0  0.0
8           9   0.0   0.0   0.0   0.0  2.0   0.0  0.0
9          10   0.0   0.0   0.0   1.0  0.0   0.0  0.0
10         11   0.0   0.0   0.0   1.0  0.0   0.0  0.0
11         12   0.0   0.0   0.0   1.0  0.0   0.0  0.0
12         13   0.0   0.0   0.0   0.0  0.0   0.0  2.0
13         14   0.0   0.0   0.0   2.0  0.0   0.0  0.0
14         15   0.0   0.0   0.0   0.0  0.0   2.0  0.0
15         16   0.0   0.0   1.0   0.0  0.0   0.0  0.0
16         17   0.0   0.0   0.0   0.0  0.0   1.0  0.0
17         18   0.0   0.0   0.0   1.0  0.0   0.0  0.0
18         19   0.0   0.0   1.0   1.0  0.0   0.0  0.0
19         20   0.0   0.0   0.0   1.0  0.0   0.0  0.0
20         21   0.0   0.0   0.0   0.0  0.0   0.0  2.0
21         22   0.0   0.0   1.0   0.0  0.0   0.0  0.0
22         23   0.0   0.0   0.0   0.0  5.0   0.0  0.0
23         24   0.0   0.0   0.0   1.0  0.0   0.0  0.0
24         25   0.0   0.0   0.0   0.0  0.0   4.0  0.0
25         26   0.0   0.0   0.0   0.0  0.0   3.0  0.0
26         27   0.0   0.0   0.0   0.0  0.0   0.0  1.0
27         28   0.0   0.0   0.0   0.0  7.0   0.0  0.0
28         29   0.0   0.0   2.0   0.0  0.0   2.0  0.0
29         30   0.0   0.0   0.0   3.0  1.0   0.0  0.0
30         31   0.0   0.0   0.0   0.0  0.0   0.0  7.0
31         32   0.0   0.0   0.0   0.0  0.0   0.0  6.0
32         33   0.0   0.0   0.0   1.0  4.0   1.0  0.0
33         34   1.0   0.0   0.0   0.0  0.0   8.0  0.0

In [53]:
vetores_por_loja = {}

# Iterar sobre cada grupo (grupo de cada loja)
for nome_loja, grupo in df_process_situacao2.groupby('chave_loja_buffer_onda'):
    # Extrair os IDs do grupo como um vetor
    vetor_ids = grupo['Id'].tolist()
    # Adicionar o vetor à lista de vetores, usando o nome da loja como chave
    vetores_por_loja[nome_loja] = vetor_ids
    # Atribuir o vetor a uma variável com o nome da loja
    exec(f'vetor_{nome_loja} = vetor_ids')

In [54]:
# Lista dos caracteres finais dos nomes dos vetores
char_final = [col for col in w.columns[:3]]

# Criar o dicionário mapeando os caracteres finais aos vetores
vetores = {char: globals()[f'vetor_{char}'] for char in char_final}

In [55]:
df_agrupamento_loja1_highs_s2['Id'] = vetores[f"{w.columns[0]}"]
df_agrupamento_loja1_highs_s2['chave_loja_buffer_onda'] = list(w.columns)[0]

df_agrupamento_loja1_highs_s2

,item_loja,1,2,3,4,5,6,7,Id,chave_loja_buffer_onda
0,1,19.0,0.0,0.0,0.0,0.0,0.0,0.0,35743,143_EN_1
1,2,0.0,20.0,0.0,14.0,0.0,1.0,0.0,35744,143_EN_1
2,3,0.0,0.0,0.0,0.0,0.0,9.0,0.0,35745,143_EN_1
3,4,0.0,0.0,11.0,0.0,0.0,0.0,9.0,35746,143_EN_1
4,5,0.0,0.0,6.0,0.0,0.0,0.0,0.0,35747,143_EN_1
5,6,0.0,0.0,0.0,0.0,9.0,0.0,0.0,35748,143_EN_1
6,7,8.0,6.0,0.0,0.0,0.0,0.0,0.0,35749,143_EN_1
7,8,0.0,0.0,0.0,0.0,0.0,12.0,0.0,35750,143_EN_1
8,9,0.0,0.0,0.0,0.0,2.0,0.0,0.0,35751,143_EN_1
9,10,0.0,0.0,0.0,1.0,0.0,0.0,0.0,35752,143_EN_1
10,11,0.0,0.0,0.0,1.0,0.0,0.0,0.0,35753,143_EN_1
11,12,0.0,0.0,0.0,1.0,0.0,0.0,0.0,35754,143_EN_1
12,13,0.0,0.0,0.0,0.0,0.0,0.0,2.0,35755,143_EN_1
13,14,0.0,0.0,0.0,2.0,0.0,0.0,0.0,35756,143_EN_1
14,15,0.0,0.0,0.0,0.0,0.0,2.0,0.0,35757,143_EN_1
15,16,0.0,0.0,1.0,0.0,0.0,0.0,0.0,35758,143_EN_1
16,17,0.0,0.0,0.0,0.0,0.0,1.0,0.0,35759,143_EN_1
17,18,0.0,0.0,0.0,1.0,0.0,0.0,0.0,35760,143_EN_1
18,19,0.0,0.0,1.0,1.0,0.0,0.0,0.0,35761,143_EN_1
19,20,0.0,0.0,0.0,1.0,0.0,0.0,0.0,40004,143_EN_1
20,21,0.0,0.0,0.0,0.0,0.0,0.0,2.0,44958,143_EN_1
21,22,0.0,0.0,1.0,0.0,0.0,0.0,0.0,44959,143_EN_1
22,23,0.0,0.0,0.0,0.0,5.0,0.0,0.0,44960,143_EN_1
23,24,0.0,0.0,0.0,1.0,0.0,0.0,0.0,44961,143_EN_1
24,25,0.0,0.0,0.0,0.0,0.0,4.0,0.0,44962,143_EN_1
25,26,0.0,0.0,0.0,0.0,0.0,3.0,0.0,44963,143_EN_1
26,27,0.0,0.0,0.0,0.0,0.0,0.0,1.0,49193,143_EN_1
27,28,0.0,0.0,0.0,0.0,7.0,0.0,0.0,57714,143_EN_1
28,29,0.0,0.0,2.0,0.0,0.0,2.0,0.0,57715,143_EN_1
29,30,0.0,0.0,0.0,3.0,1.0,0.0,0.0,57716,143_EN_1
30,31,0.0,0.0,0.0,0.0,0.0,0.0,7.0,57717,143_EN_1
31,32,0.0,0.0,0.0,0.0,0.0,0.0,6.0,57718,143_EN_1
32,33,0.0,0.0,0.0,1.0,4.0,1.0,0.0,57719,143_EN_1
33,34,1.0,0.0,0.0,0.0,0.0,8.0,0.0,57720,143_EN_1

In [56]:
df_agrupamento_loja2_highs_s2 = e_s2_highs.query('chave_loja_buffer_onda == 2').pivot_table(index='item_loja', columns='caixa', values='valor_multiplo', fill_value=0)
df_agrupamento_loja2_highs_s2 = df_agrupamento_loja2_highs_s2.reset_index()
df_agrupamento_loja2_highs_s2.columns.name = None
df_agrupamento_loja2_highs_s2['Id'] = vetores[f"{w.columns[1]}"]
df_agrupamento_loja2_highs_s2['chave_loja_buffer_onda'] = list(w.columns)[1]

df_agrupamento_loja2_highs_s2

,item_loja,1,2,3,4,5,6,7,8,Id,chave_loja_buffer_onda
0,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,36663,25_EN_2
1,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,40115,25_EN_2
2,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,40116,25_EN_2
3,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,41031,25_EN_2
4,5,0.0,0.0,0.0,6.0,1.0,0.0,0.0,0.0,41032,25_EN_2
...,...,...,...,...,...,...,...,...,...,...,...
73,74,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,61395,25_EN_2
74,75,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,61396,25_EN_2
75,76,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,61397,25_EN_2
76,77,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,61398,25_EN_2
77,78,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,61399,25_EN_2

In [57]:
y_s2_highs = ampl.getVariable('y').getValues().toPandas()
y_s2_highs = y_s2_highs.reset_index()
y_s2_highs.columns = ['Caixa','chave_loja_buffer_onda', 'selecao']
y_s2_highs = y_s2_highs.query('selecao>0')

df_caixas_por_loja_highs_s2 = y_s2_highs.pivot_table(index='Caixa', columns='chave_loja_buffer_onda', values='selecao', fill_value=0)
df_caixas_por_loja_highs_s2 = df_caixas_por_loja_highs_s2.reset_index()
df_caixas_por_loja_highs_s2.columns.name = None
df_caixas_por_loja_highs_s2 # as colunas são as lojas

   Caixa    1    2    3
0      1  1.0  1.0  1.0
1      2  1.0  1.0  1.0
2      3  1.0  1.0  1.0
3      4  1.0  1.0  1.0
4      5  1.0  1.0  1.0
5      6  1.0  1.0  0.0
6      7  1.0  1.0  0.0
7      8  0.0  1.0  0.0

In [58]:
df_caixas_por_loja_highs_s2.columns = (['caixas'] + list(w.columns)) # os número das colunas são os nomes das lojas
df_caixas_por_loja_highs_s2

   caixas  143_EN_1  25_EN_2  44_CX_3
0       1       1.0      1.0      1.0
1       2       1.0      1.0      1.0
2       3       1.0      1.0      1.0
3       4       1.0      1.0      1.0
4       5       1.0      1.0      1.0
5       6       1.0      1.0      0.0
6       7       1.0      1.0      0.0
7       8       0.0      1.0      0.0

In [59]:
print('Solver Highs')
for col in w.columns:
    print(f'número de caixas para a chave_loja_buffer_onda "{col}": {df_caixas_por_loja_highs_s2[f"{col}"].sum()}')

Solver Highs
número de caixas para a chave_loja_buffer_onda "143_EN_1": 7.0
número de caixas para a chave_loja_buffer_onda "25_EN_2": 8.0
número de caixas para a chave_loja_buffer_onda "44_CX_3": 5.0

#### Solver SCIP

In [60]:
ampl.option["solver"] = "scip"
ampl.option["scip_options"] = "outlev=1 timelimit=600"
ampl.solve()

SCIP 9.0.0:   tech:outlev = 1
  lim:time = 600
presolving:
(round 1, fast)       0 del vars, 0 del conss, 0 add conss, 0 chg bounds, 0 chg sides, 32 chg coeffs, 0 upgd conss, 0 impls, 92 clqs
(round 2, exhaustive) 0 del vars, 0 del conss, 0 add conss, 0 chg bounds, 0 chg sides, 32 chg coeffs, 92 upgd conss, 0 impls, 92 clqs
   (0.0s) probing cycle finished: starting next cycle
(round 3, exhaustive) 7 del vars, 0 del conss, 0 add conss, 0 chg bounds, 0 chg sides, 32 chg coeffs, 92 upgd conss, 10890 impls, 5102 clqs
(round 4, fast)       7 del vars, 12 del conss, 0 add conss, 0 chg bounds, 2 chg sides, 32 chg coeffs, 92 upgd conss, 10890 impls, 5102 clqs
   (0.0s) probing: 40/793 (5.0%) - 7 fixings, 0 aggregations, 15942 implications, 0 bound changes
   (0.0s) probing aborted: 50/50 successive totally useless probings
   (0.0s) symmetry computation started: requiring (bin +, int +, cont +), (fixed: bin -, int -, cont -)
   (0.0s) symmetry computation finished: 4 generators found (max: 1500, log10 of symmetry group size: 1.4) (symcode time: 0.00)
dynamic symmetry handling statistics:
   orbitopal reduction:       no components
   orbital reduction:         no components
   lexicographic reduction:    2 permutations with support sizes 156, 82
handled 3 out of 3 symmetry components
(round 5, exhaustive) 10 del vars, 12 del conss, 1 add conss, 0 chg bounds, 2 chg sides, 32 chg coeffs, 92 upgd conss, 10890 impls, 5102 clqs
   (0.0s) probing: 46/793 (5.8%) - 7 fixings, 0 aggregations, 15942 implications, 0 bound changes
   (0.0s) probing aborted: 50/50 successive totally useless probings
presolving (6 rounds: 6 fast, 4 medium, 4 exhaustive):
 10 deleted vars, 12 deleted constraints, 1 added constraints, 0 tightened bounds, 0 added holes, 2 changed sides, 32 changed coefficients
 10890 implications, 5102 cliques
presolved problem has 2486 variables (790 bin, 1696 int, 0 impl, 0 cont) and 331 constraints
     85 constraints of type <setppc>
    245 constraints of type <linear>
      1 constraints of type <orbitope>
transformed objective value is always integral (scale: 1)
Presolving Time: 0.00

 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl.
p 0.0s|     1 |     0 |    18 |     - |shiftand|   0 |2486 | 332 | 330 |   0 |  0 |   0 |   0 | 7.000000e+00 | 4.800000e+01 | 585.71%| unknown
i 0.0s|     1 |     0 |    18 |     - |  oneopt|   0 |2486 | 332 | 330 |   0 |  0 |   0 |   0 | 7.000000e+00 | 2.900000e+01 | 314.29%| unknown
  0.0s|     1 |     0 |  1203 |     - |    39M |   0 |2486 | 332 | 330 |   0 |  0 |   0 |   0 | 1.928319e+01 | 2.900000e+01 |  50.39%| unknown
  0.0s|     1 |     0 |  1324 |     - |    40M |   0 |2486 | 332 | 375 |  45 |  1 |   0 |   0 | 1.928319e+01 | 2.900000e+01 |  50.39%| unknown
  0.0s|     1 |     0 |  1413 |     - |    41M |   0 |2486 | 332 | 417 |  87 |  2 |   0 |   0 | 1.928319e+01 | 2.900000e+01 |  50.39%| unknown
  0.0s|     1 |     0 |  1513 |     - |    41M |   0 |2486 | 332 | 456 | 126 |  3 |   0 |   0 | 1.928319e+01 | 2.900000e+01 |  50.39%| unknown
  0.0s|     1 |     0 |  1659 |     - |    42M |   0 |2486 | 333 | 493 | 163 |  4 |   1 |   0 | 1.928319e+01 | 2.900000e+01 |  50.39%| unknown
  0.0s|     1 |     0 |  1763 |     - |    42M |   0 |2486 | 333 | 531 | 201 |  5 |   1 |   0 | 1.928319e+01 | 2.900000e+01 |  50.39%| unknown
  0.0s|     1 |     0 |  1880 |     - |    42M |   0 |2486 | 333 | 567 | 237 |  6 |   1 |   0 | 1.928319e+01 | 2.900000e+01 |  50.39%| unknown
  0.0s|     1 |     0 |  1943 |     - |    43M |   0 |2486 | 333 | 603 | 273 |  7 |   1 |   0 | 1.928319e+01 | 2.900000e+01 |  50.39%| unknown
  0.0s|     1 |     0 |  2013 |     - |    43M |   0 |2486 | 333 | 629 | 299 |  8 |   1 |   0 | 1.928319e+01 | 2.900000e+01 |  50.39%| unknown
  0.0s|     1 |     0 |  2092 |     - |    44M |   0 |2486 | 333 | 659 | 329 |  9 |   1 |   0 | 1.928319e+01 | 2.900000e+01 |  50.39%| unknown
r 0.0s|     1 |     0 |  2092 |     - |shifting|   0 |2486 | 333 | 659 | 329 |  9 |   1 |   0 | 1.928319e+01 | 2.800000e+01 |  45.20%| unknown
  0.0s|     1 |     0 |  2189 |     - |    44M |   0 |2486 | 333 | 682 | 352 | 10 |   1 |   0 | 1.928319e+01 | 2.800000e+01 |  45.20%| unknown
i 0.0s|     1 |     0 |  2189 |     - |  oneopt|   0 |2486 | 333 | 682 | 352 | 10 |   1 |   0 | 1.928319e+01 | 2.600000e+01 |  34.83%| unknown
 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl.
  0.0s|     1 |     0 |  2276 |     - |    44M |   0 |2486 | 333 | 704 | 374 | 11 |   1 |   0 | 1.928319e+01 | 2.600000e+01 |  34.83%| unknown
L 0.0s|     1 |     0 |  2702 |     - |    alns|   0 |2486 | 333 | 704 | 374 | 11 |   1 |   0 | 1.963137e+01 | 2.300000e+01 |  17.16%| unknown
L 0.0s|     1 |     0 |  2702 |     - |    alns|   0 |2486 | 333 | 704 | 374 | 11 |   1 |   0 | 1.963137e+01 | 2.200000e+01 |  12.07%| unknown
  0.0s|     1 |     0 |  2702 |     - |    45M |   0 |2486 | 289 | 704 | 374 | 11 |   1 |   0 | 1.963137e+01 | 2.200000e+01 |  12.07%| unknown
  0.0s|     1 |     0 |  2734 |     - |    45M |   0 |2486 | 289 | 717 | 387 | 12 |   1 |   0 | 1.963137e+01 | 2.200000e+01 |  12.07%| unknown
  0.0s|     1 |     0 |  2757 |     - |    45M |   0 |2486 | 289 | 723 | 393 | 13 |   1 |   0 | 1.963137e+01 | 2.200000e+01 |  12.07%| unknown
(run 1, node 1) restarting after 433 global fixings of integer variables

(restart) converted 393 cuts from the global cut pool into linear constraints

presolving:
(round 1, fast)       433 del vars, 96 del conss, 0 add conss, 0 chg bounds, 7 chg sides, 7 chg coeffs, 0 upgd conss, 10890 impls, 1829 clqs
(round 2, exhaustive) 433 del vars, 103 del conss, 0 add conss, 0 chg bounds, 14 chg sides, 7 chg coeffs, 0 upgd conss, 10890 impls, 1829 clqs
(round 3, exhaustive) 433 del vars, 103 del conss, 0 add conss, 0 chg bounds, 14 chg sides, 7 chg coeffs, 181 upgd conss, 10890 impls, 1829 clqs
(round 4, medium)     433 del vars, 120 del conss, 26 add conss, 0 chg bounds, 14 chg sides, 7 chg coeffs, 181 upgd conss, 10890 impls, 1829 clqs
(round 5, exhaustive) 433 del vars, 122 del conss, 26 add conss, 0 chg bounds, 14 chg sides, 7 chg coeffs, 181 upgd conss, 10890 impls, 1829 clqs
presolving (6 rounds: 6 fast, 5 medium, 4 exhaustive):
 851 deleted vars, 291 deleted constraints, 26 added constraints, 0 tightened bounds, 0 added holes, 14 changed sides, 7 changed coefficients
 10890 implications, 1280 cliques
presolved problem has 1635 variables (491 bin, 1144 int, 0 impl, 0 cont) and 417 constraints
     84 constraints of type <varbound>
     84 constraints of type <setppc>
    247 constraints of type <linear>
      1 constraints of type <orbitope>
      1 constraints of type <bounddisjunction>
transformed objective value is always integral (scale: 1)
Presolving Time: 1.00

 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl.
  1.0s|     1 |     0 |  3391 |     - |    46M |   0 |1635 | 342 | 340 |   0 |  0 |   1 |   0 | 1.985805e+01 | 2.200000e+01 |  10.79%| unknown
  1.0s|     1 |     0 |  3394 |     - |    46M |   0 |1635 | 342 | 306 |   0 |  0 |   1 |   0 | 1.985805e+01 | 2.200000e+01 |  10.79%| unknown
  1.0s|     1 |     0 |  3420 |     - |    46M |   0 |1635 | 323 | 282 |  15 |  1 |   1 |   0 | 1.985805e+01 | 2.200000e+01 |  10.79%| unknown
  1.0s|     1 |     0 |  3430 |     - |    46M |   0 |1635 | 321 | 290 |  23 |  2 |   1 |   0 | 1.985805e+01 | 2.200000e+01 |  10.79%| unknown
  1.0s|     1 |     0 |  3435 |     - |    46M |   0 |1635 | 321 | 294 |  27 |  3 |   1 |   0 | 1.985805e+01 | 2.200000e+01 |  10.79%| unknown
  1.0s|     1 |     0 |  3440 |     - |    46M |   0 |1635 | 321 | 298 |  31 |  4 |   1 |   0 | 1.985805e+01 | 2.200000e+01 |  10.79%| unknown
  1.0s|     1 |     0 |  3451 |     - |    46M |   0 |1635 | 321 | 302 |  35 |  5 |   1 |   0 | 1.985805e+01 | 2.200000e+01 |  10.79%| unknown
  1.0s|     1 |     0 |  3459 |     - |    46M |   0 |1635 | 321 | 306 |  39 |  6 |   1 |   0 | 1.985805e+01 | 2.200000e+01 |  10.79%| unknown
  1.0s|     1 |     0 |  3466 |     - |    46M |   0 |1635 | 322 | 311 |  44 |  7 |   2 |   0 | 1.985805e+01 | 2.200000e+01 |  10.79%| unknown
r 1.0s|     1 |     0 |  3466 |     - |shifting|   0 |1635 | 322 | 311 |  44 |  7 |   2 |   0 | 1.985805e+01 | 2.000000e+01 |   0.71%| unknown
  1.0s|     1 |     0 |  3466 |     - |    46M |   0 |1635 | 322 | 311 |  44 |  7 |   2 |   0 | 2.000000e+01 | 2.000000e+01 |   0.00%| unknown

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 1.00
Solving Nodes      : 1 (total of 2 nodes in 2 runs)
Primal Bound       : +2.00000000000000e+01 (7 solutions)
Dual Bound         : +2.00000000000000e+01
Gap                : 0.00 %
WARNING: No dual information available when presolving was performed.
SCIP 9.0.0: optimal solution; objective 20
2999 simplex iterations
1 branching nodes

In [61]:
%%ampl_eval
display FO;

FO = 20

In [62]:
e_s2_scip = ampl.getVariable('e').getValues().toPandas()
e_s2_scip = e_s2_scip.reset_index()
e_s2_scip.columns = ['item_loja','caixa', 'chave_loja_buffer_onda', 'valor_multiplo']
e_s2_scip = e_s2_scip.query('valor_multiplo >0')
e_s2_scip#.head(20)

      item_loja  caixa  chave_loja_buffer_onda  valor_multiplo
2             1      1                       3             5.0
3             1      2                       1             6.0
6             1      3                       1             1.0
7             1      3                       2             1.0
18            1      7                       1            12.0
...         ...    ...                     ...             ...
3514         74      4                       2             1.0
3568         75      6                       2             3.0
3622         76      8                       2             3.0
3661         77      5                       2             3.0
3718         78      8                       2             4.0

[171 rows x 4 columns]

In [63]:
df_agrupamento_loja1_scip_s2 = e_s2_scip.query('chave_loja_buffer_onda == 1').pivot_table(index='item_loja', columns='caixa', values='valor_multiplo', fill_value=0)
df_agrupamento_loja1_scip_s2 = df_agrupamento_loja1_scip_s2.reset_index()
df_agrupamento_loja1_scip_s2.columns.name = None
df_agrupamento_loja1_scip_s2['Id'] = vetores[f"{w.columns[0]}"]
df_agrupamento_loja1_scip_s2['chave_loja_buffer_onda'] = list(w.columns)[0]

df_agrupamento_loja1_scip_s2

,item_loja,1,2,3,4,5,6,7,Id,chave_loja_buffer_onda
0,1,0.0,6.0,1.0,0.000000e+00,0.0,0.0,12.0,35743,143_EN_1
1,2,0.0,14.0,0.0,0.000000e+00,21.0,0.0,0.0,35744,143_EN_1
2,3,0.0,0.0,0.0,0.000000e+00,0.0,9.0,0.0,35745,143_EN_1
3,4,0.0,0.0,0.0,2.000000e+01,0.0,0.0,0.0,35746,143_EN_1
4,5,0.0,0.0,4.0,0.000000e+00,2.0,0.0,0.0,35747,143_EN_1
5,6,0.0,0.0,0.0,0.000000e+00,0.0,9.0,0.0,35748,143_EN_1
6,7,14.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,35749,143_EN_1
7,8,0.0,0.0,0.0,1.200000e+01,0.0,0.0,0.0,35750,143_EN_1
8,9,0.0,0.0,2.0,0.000000e+00,0.0,0.0,0.0,35751,143_EN_1
9,10,0.0,0.0,0.0,0.000000e+00,1.0,0.0,0.0,35752,143_EN_1
10,11,1.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,35753,143_EN_1
11,12,1.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,35754,143_EN_1
12,13,2.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,35755,143_EN_1
13,14,0.0,2.0,0.0,0.000000e+00,0.0,0.0,0.0,35756,143_EN_1
14,15,0.0,2.0,0.0,0.000000e+00,0.0,0.0,0.0,35757,143_EN_1
15,16,1.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,35758,143_EN_1
16,17,0.0,0.0,0.0,1.000000e+00,0.0,0.0,0.0,35759,143_EN_1
17,18,0.0,0.0,0.0,1.000000e+00,0.0,0.0,0.0,35760,143_EN_1
18,19,0.0,2.0,0.0,0.000000e+00,0.0,0.0,0.0,35761,143_EN_1
19,20,0.0,0.0,0.0,0.000000e+00,0.0,1.0,0.0,40004,143_EN_1
20,21,0.0,1.0,1.0,0.000000e+00,0.0,0.0,0.0,44958,143_EN_1
21,22,0.0,0.0,0.0,6.661338e-16,0.0,0.0,1.0,44959,143_EN_1
22,23,0.0,0.0,0.0,0.000000e+00,0.0,0.0,5.0,44960,143_EN_1
23,24,0.0,0.0,1.0,0.000000e+00,0.0,0.0,0.0,44961,143_EN_1
24,25,0.0,0.0,4.0,0.000000e+00,0.0,0.0,0.0,44962,143_EN_1
25,26,0.0,0.0,3.0,0.000000e+00,0.0,0.0,0.0,44963,143_EN_1
26,27,0.0,0.0,0.0,0.000000e+00,0.0,1.0,0.0,49193,143_EN_1
27,28,4.0,0.0,0.0,3.000000e+00,0.0,0.0,0.0,57714,143_EN_1
28,29,0.0,0.0,0.0,4.000000e+00,0.0,0.0,0.0,57715,143_EN_1
29,30,0.0,0.0,0.0,4.000000e+00,0.0,0.0,0.0,57716,143_EN_1
30,31,2.0,0.0,5.0,0.000000e+00,0.0,0.0,0.0,57717,143_EN_1
31,32,0.0,0.0,6.0,0.000000e+00,0.0,0.0,0.0,57718,143_EN_1
32,33,0.0,0.0,0.0,0.000000e+00,0.0,0.0,6.0,57719,143_EN_1
33,34,0.0,0.0,0.0,9.000000e+00,0.0,0.0,0.0,57720,143_EN_1

In [64]:
df_agrupamento_loja2_scip_s2 = e_s2_scip.query('chave_loja_buffer_onda == 2').pivot_table(index='item_loja', columns='caixa', values='valor_multiplo', fill_value=0)
df_agrupamento_loja2_scip_s2 = df_agrupamento_loja2_scip_s2.reset_index()
df_agrupamento_loja2_scip_s2.columns.name = None
df_agrupamento_loja2_scip_s2['Id'] = vetores[f"{w.columns[1]}"]
df_agrupamento_loja2_scip_s2['chave_loja_buffer_onda'] = list(w.columns)[1]

df_agrupamento_loja2_scip_s2

,item_loja,1,2,3,4,5,6,7,8,Id,chave_loja_buffer_onda
0,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,36663,25_EN_2
1,2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,40115,25_EN_2
2,3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,40116,25_EN_2
3,4,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41031,25_EN_2
4,5,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41032,25_EN_2
...,...,...,...,...,...,...,...,...,...,...,...
73,74,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,61395,25_EN_2
74,75,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,61396,25_EN_2
75,76,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,61397,25_EN_2
76,77,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,61398,25_EN_2
77,78,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,61399,25_EN_2

In [65]:
df_agrupamento_loja3_scip_s2 = e_s2_scip.query('chave_loja_buffer_onda == 3').pivot_table(index='item_loja', columns='caixa', values='valor_multiplo', fill_value=0)
df_agrupamento_loja3_scip_s2 = df_agrupamento_loja3_scip_s2.reset_index()
df_agrupamento_loja3_scip_s2.columns.name = None
df_agrupamento_loja3_scip_s2['Id'] = vetores[f"{w.columns[2]}"]
df_agrupamento_loja3_scip_s2['chave_loja_buffer_onda'] = list(w.columns)[2]

df_agrupamento_loja3_scip_s2

    item_loja     1     2     3     4     5     Id chave_loja_buffer_onda
0           1   5.0   0.0   0.0   0.0   0.0   7129                44_CX_3
1           2   0.0   1.0   0.0   0.0   0.0   7130                44_CX_3
2           3   0.0   1.0   0.0   0.0   0.0   7131                44_CX_3
3           4   0.0   1.0   0.0   0.0   0.0   7132                44_CX_3
4           5   0.0   2.0   0.0   0.0   0.0   7133                44_CX_3
5           6   0.0   1.0   0.0   0.0   0.0   7134                44_CX_3
6           7   0.0   1.0   0.0   0.0   0.0   7135                44_CX_3
7           8   0.0   1.0   0.0   0.0   0.0   7136                44_CX_3
8           9   0.0   0.0   0.0   1.0   0.0   7137                44_CX_3
9          10   0.0   1.0   0.0   0.0   0.0   7138                44_CX_3
10         11   0.0   1.0   0.0   0.0   0.0   7139                44_CX_3
11         12   0.0   1.0   0.0   0.0   2.0   7140                44_CX_3
12         13   2.0   0.0   0.0   0.0   0.0   7141                44_CX_3
13         14   1.0   1.0   0.0   0.0   0.0   7142                44_CX_3
14         15   0.0   0.0   0.0   0.0   1.0   7143                44_CX_3
15         16   0.0   0.0   0.0   0.0   1.0   7144                44_CX_3
16         17   3.0   0.0   0.0   0.0   0.0   7145                44_CX_3
17         18   2.0   0.0   0.0   0.0   0.0   7146                44_CX_3
18         19   0.0   0.0   0.0   2.0   0.0   7147                44_CX_3
19         20   1.0   0.0   0.0   0.0   0.0   7148                44_CX_3
20         21   1.0   0.0   0.0   0.0   0.0   7149                44_CX_3
21         22  10.0   0.0   0.0   0.0   0.0   7150                44_CX_3
22         23   4.0   0.0   0.0   0.0   0.0   7151                44_CX_3
23         24   0.0  14.0   0.0   0.0   0.0   7152                44_CX_3
24         25   4.0   0.0   0.0   0.0   0.0   7153                44_CX_3
25         26  10.0   0.0   0.0   0.0   0.0   7154                44_CX_3
26         27   0.0   1.0   0.0   0.0   0.0  13972                44_CX_3
27         28   0.0   0.0   0.0  13.0   0.0  13973                44_CX_3
28         29   0.0   9.0   0.0   0.0   0.0  13974                44_CX_3
29         30   9.0   0.0   0.0   0.0   2.0  13975                44_CX_3
30         31   0.0   0.0  14.0   0.0   1.0  13976                44_CX_3
31         32   0.0   0.0  10.0   0.0   0.0  13977                44_CX_3
32         33   0.0   0.0   0.0   8.0   5.0  13978                44_CX_3
33         34   0.0   0.0   0.0  12.0   0.0  13979                44_CX_3
34         35   0.0   0.0   3.0   0.0  11.0  13980                44_CX_3
35         36   0.0   9.0   0.0   0.0   0.0  13981                44_CX_3
36         37   0.0   0.0   0.0   3.0   0.0  18120                44_CX_3
37         38   0.0   0.0   0.0   3.0   0.0  18121                44_CX_3
38         39   0.0   0.0   0.0   0.0   6.0  18122                44_CX_3
39         40   0.0   2.0   0.0   0.0   0.0  18123                44_CX_3
40         41   0.0   0.0   6.0   0.0   0.0  18124                44_CX_3

In [66]:
y_s2_scip = ampl.getVariable('y').getValues().toPandas()
y_s2_scip = y_s2_scip.reset_index()
y_s2_scip.columns = ['Caixa','chave_loja_buffer_onda', 'selecao']
y_s2_scip = y_s2_scip.query('selecao>0')

df_caixas_por_loja_scip_s2 = y_s2_scip.pivot_table(index='Caixa', columns='chave_loja_buffer_onda', values='selecao', fill_value=0)
df_caixas_por_loja_scip_s2 = df_caixas_por_loja_scip_s2.reset_index()
df_caixas_por_loja_scip_s2.columns.name = None
df_caixas_por_loja_scip_s2 # as colunas são as lojas

   Caixa    1    2    3
0      1  1.0  1.0  1.0
1      2  1.0  1.0  1.0
2      3  1.0  1.0  1.0
3      4  1.0  1.0  1.0
4      5  1.0  1.0  1.0
5      6  1.0  1.0  0.0
6      7  1.0  1.0  0.0
7      8  0.0  1.0  0.0

In [67]:
df_caixas_por_loja_scip_s2.columns = (['caixas'] + list(w.columns)) # os número das colunas são os nomes das lojas
df_caixas_por_loja_scip_s2

   caixas  143_EN_1  25_EN_2  44_CX_3
0       1       1.0      1.0      1.0
1       2       1.0      1.0      1.0
2       3       1.0      1.0      1.0
3       4       1.0      1.0      1.0
4       5       1.0      1.0      1.0
5       6       1.0      1.0      0.0
6       7       1.0      1.0      0.0
7       8       0.0      1.0      0.0

In [68]:
print('Solver SCIP')
for col in w.columns:
    print(f'número de caixas para a chave_loja_buffer_onda "{col}": {df_caixas_por_loja_scip_s2[f"{col}"].sum()}')

Solver SCIP
número de caixas para a chave_loja_buffer_onda "143_EN_1": 7.0
número de caixas para a chave_loja_buffer_onda "25_EN_2": 8.0
número de caixas para a chave_loja_buffer_onda "44_CX_3": 5.0