# 0- Imports

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import locale

import warnings
warnings.filterwarnings("ignore")

# 1- Base

In [3]:
df_output = pd.read_excel('../../01-Data/results.xlsx')
df_output

,id,Ordem_de_produÃ§Ã£o,Data_da_ordem_de_produÃ§Ã£o,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,PeÃ§as,Caixa_padrÃ£o,...,Capacidade,pai_cor,chave_loja_buffer_onda,Volume_unit,Volume_total,Peso_total,item_loja,Bin,Amt_in_bin,bin_index
0,0,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,...,inf,1865_6.0,26_CX_5,3092300,6184600,1.120000e+00,1,0,2,0
1,1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,...,inf,1865_6.0,26_CX_5,3321500,9964500,1.800000e+16,2,0,3,0
2,1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,...,inf,1865_6.0,26_CX_5,3321500,9964500,1.800000e+16,2,5614,3,5614
3,1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,...,inf,1865_6.0,26_CX_5,3321500,9964500,1.800000e+16,2,5614,3,5614
4,2,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,...,inf,1865_6.0,26_CX_5,3537200,3537200,5.800000e-01,3,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109994,62226,6095,2023-11-22,623412941,420,278,28,0.213,2,CARTON_M,...,4.000000e+10,1863_2.0,48_EN_2,3269280,6538560,4.260000e-01,1048,6418,2,6418
109995,62227,5591,2023-11-22,623412950,427,305,31,0.233,1,CARTON_M,...,4.000000e+10,1863_2.0,48_EN_2,4037285,4037285,2.330000e-01,1049,6418,1,6418
109996,62228,11858,2023-11-22,623412933,408,264,30,0.195,2,CARTON_M,...,4.000000e+10,1863_2.0,48_EN_2,3231360,6462720,3.900000e-01,1050,6418,2,6418
109997,62229,10583,2023-11-22,622808371,371,233,49,0.323,1,CARTON_M,...,4.000000e+10,713_275.0,48_EN_2,4235707,4235707,3.230000e-01,1051,6418,1,6418
109998,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,4.000000e+10,15_9.0,48_EN_3,3156208,9468624,7.800000e-01,1052,6709,3,6709

In [9]:
df_output.columns

Index(['id', 'Ordem_de_produÃ§Ã£o', 'Data_da_ordem_de_produÃ§Ã£o', 'Produto',
       'Comprimento_unit', 'Largura_unit', 'Altura_unit', 'Peso_unit',
       'PeÃ§as', 'Caixa_padrÃ£o', 'Loja', 'Classe_de_onda', 'Tipo_de_buffer',
       'Item_pai', 'Cor', 'Tamanho', 'Inner', 'Rota', 'Capacidade', 'pai_cor',
       'chave_loja_buffer_onda', 'Volume_unit', 'Volume_total', 'Peso_total',
       'item_loja', 'Bin', 'Amt_in_bin', 'bin_index'],
      dtype='object')

In [12]:
df_output.query('id ==10')[['id', 'Ordem_de_produÃ§Ã£o', 'Data_da_ordem_de_produÃ§Ã£o', 'PeÃ§as', 'Produto','chave_loja_buffer_onda',
       'item_loja', 'Bin', 'Amt_in_bin', 'bin_index']]

,id,Ordem_de_produÃ§Ã£o,Data_da_ordem_de_produÃ§Ã£o,PeÃ§as,Produto,chave_loja_buffer_onda,item_loja,Bin,Amt_in_bin,bin_index
58,10,11552,2023-10-16,10,825051881,33_CX_2,1,5,10,5
59,10,11552,2023-10-16,10,825051881,33_CX_2,1,3998,10,3998
60,10,11552,2023-10-16,10,825051881,33_CX_2,1,3998,10,3998
61,10,11552,2023-10-16,10,825051881,33_CX_2,1,3998,10,3998
62,10,11552,2023-10-16,10,825051881,33_CX_2,1,3998,10,3998
63,10,11552,2023-10-16,10,825051881,33_CX_2,1,3998,10,3998
64,10,11552,2023-10-16,10,825051881,33_CX_2,1,3998,10,3998
65,10,11552,2023-10-16,10,825051881,33_CX_2,1,3998,10,3998
66,10,11552,2023-10-16,10,825051881,33_CX_2,1,3998,10,3998
67,10,11552,2023-10-16,10,825051881,33_CX_2,1,3998,10,3998

## 2.1- Input

In [13]:
df_input = pd.read_excel('../../01-Data/ordens_pre_process_revisado.xlsx')
df_input

,Unnamed: 0,Ordem_de_produção,Data_da_ordem_de_produção,Produto,Comprimento_unit,Largura_unit,Altura_unit,Peso_unit,Peças,Caixa_padrão,...,Tipo_de_buffer,Item_pai,Cor,Tamanho,Inner,Rota,Capacidade,pai_cor,chave_loja_buffer_onda,Volume_unit
0,0,4522,2023-08-16,633674988,428,289,25,0.560,2,CARTON_M,...,CX,1865,6.0,27,1,1,inf,1865_6.0,26_CX_5,3092300
1,1,7928,2023-08-16,633675008,455,292,25,0.600,3,CARTON_M,...,CX,1865,6.0,21,1,1,inf,1865_6.0,26_CX_5,3321500
2,2,9224,2023-08-16,633674996,478,296,25,0.580,1,CARTON_M,...,CX,1865,6.0,4,1,1,inf,1865_6.0,26_CX_5,3537200
3,3,9002,2023-10-16,804068334,116,106,19,0.082,1,CARTON_S,...,CX,2489,674.0,179,1,3,inf,2489_674.0,116_CX_6,233624
4,4,11552,2023-10-16,825051881,235,110,30,0.092,10,CARTON_M,...,CX,2988,451.0,109,1,1,inf,2988_451.0,16_CX_2,775500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62226,62226,6095,2023-11-22,623412941,420,278,28,0.213,2,CARTON_M,...,EN,1863,2.0,38,1,15,4.000000e+10,1863_2.0,48_EN_2,3269280
62227,62227,5591,2023-11-22,623412950,427,305,31,0.233,1,CARTON_M,...,EN,1863,2.0,58,1,15,4.000000e+10,1863_2.0,48_EN_2,4037285
62228,62228,11858,2023-11-22,623412933,408,264,30,0.195,2,CARTON_M,...,EN,1863,2.0,16,1,15,4.000000e+10,1863_2.0,48_EN_2,3231360
62229,62229,10583,2023-11-22,622808371,371,233,49,0.323,1,CARTON_M,...,EN,713,275.0,16,1,15,4.000000e+10,713_275.0,48_EN_2,4235707
62230,62230,207,2023-11-22,881488762,454,316,22,0.260,3,CARTON_M,...,EN,15,9.0,6,1,15,4.000000e+10,15_9.0,48_EN_3,3156208

## 2- EDA

In [5]:
df_output['bin_index'].nunique()

9943

In [14]:
df_input['Peças'].sum()

np.int64(219995)

In [17]:
df_output['Amt_in_bin'].sum()

np.int64(782219)